### ISSUE TITLE
Issue about SEBE visualisation

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#107]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/107) by Anonymous.**

----------------------------------------

Hello,

I would lke to ask is the latest version of SEBE visualisation not supporting QGIS3 yet?

Also when I was trying to install UMEP on QGIS2, SSL Handshake Error would occour. I was wondering what caused this error? It was on university lab win10 PCs.

Many thanks,
Samson

**Comment by biglimp** [comment]
SEBE (Visualisation) now available as from 3.13.1. Plugin still experimental.
