### ISSUE TITLE
SEBE: Energyyearwall.txt How can I view this file?

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#116]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/116) by Redlich Garcia (Bitbucket: [Redlich Garcia](https://bitbucket.org/Redlich Garcia), ).**

----------------------------------------

Greetings Fredrik,

My question is about the output in SEBE because the model saves two mandatory datasets:

1. The GeoTIFF: Energyyearroof.tif
2. The Energyyearwall.txt \(this is my problem, because how can I view this document in QGIS 3.4.12? without visualization? What is your recommendation?\)

Thank you!!

**Comment by biglimp** [comment]
SEBE (Visualisation) now available as from 3.13.1. Plugin still experimental.
