### ISSUE TITLE
Gridlayout for LandCoverFraction etc.

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#12]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/12) by Fredrik Lindberg (Bitbucket: [fredrik_ucg](https://bitbucket.org/fredrik_ucg), ).**

----------------------------------------

The LandCoverFractionGrid is only working with squared (or rectangular) polygon grids allinged with the CRS used. This will be fixed so that any shape of grids can be used.

**Comment by DimitrisTsi** [comment]
Hello
I would like to ask a question regarding the use of non rectangular grids.
I want to run the morphometric calculator for the DSM as seen in the attached image for the area denoted by the red polygon.
If i run the morphometric calculator using the polygon in red as the 'vector polygon grid' i get the error 
" LINE 216 "if np.sum(dsm_array) == (dsm_array.shape[0] * dsm_array.shape[1] * nd):" 
             ERROR MESSAGE: unsupported operand type(s) for *: 'int' and 'NoneType' "
So i would like to ask which is the correct way to do this. 
Should i mask all values outside the red polygon (assigning them to nan), and run the process using the purple rectangle (it's the red polygons extracted extent) ?
I know this is not a bug but a technical question, however any help would be greatly appreciated!
Thanks! 
![Στιγμιότυπο 2021-07-13, 9 49 38 πμ](https://user-images.githubusercontent.com/20373671/125406526-98ff6600-e3c1-11eb-93d1-3cb104159b01.png)
