### ISSUE TITLE
is it possible to calculate Daily shadow on facade?

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#121]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/121) by Anonymous.**

----------------------------------------

Similar to "Solar Radiation: Solar Energy on Building Envelopes" module which provide solar irradiance for both horizontal surface and walls, is it possible to calculate shadows on wall using "Solar Radiation: Daily Shadow Pattern" module?

**Comment by biglimp** [comment]
Capabilities to save shadow heights on facades are included as from 3.13.1
