### ISSUE TITLE
OHM coefficients

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#144]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/144) by Emmanouil Panagiotakis (Bitbucket: [Emmanouil Panagiotakis](https://bitbucket.org/Emmanouil Panagiotakis), ).**

The original report had attachments: UFgrid.rar

----------------------------------------

Hello, i used 901 code for paved and the results are not the expected in this diagram the blue line is the ΔQs of a pixel with only paved and the the orange is the calculated via Q\* with equation and coefficients 901 manually \(901 0.36 0.23 -19.3 ! Asphalt Narita et al. \(1984\)\)

![](https://bitbucket.org/repo/866jAG/images/465310814-image.png)
‌

**Comment by Empanag** [comment]
i run it again and seems to be fine now, if it happen again i will contact
