### ISSUE TITLE
ERA5 - Missing Python Packages

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#151]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/151) by Luis Felipe Duarte (Bitbucket: [Luis Felipe Duarte](https://bitbucket.org/Luis Felipe Duarte), ).**

The original report had attachments: 2.PNG, 1.PNG

----------------------------------------

I have an issue while trying to use the ERA5 tool to download meteorological data. Whenever I try to use it, I get the warning emerging window that says: “This plugin requires the supy package to be installed OR upgraded. Please consult the FAQ in the manual for further information on how to install missing python packages.”

‌

However, I already tried to install the pandas package using the OSGeo4W installer \(the first and most recommendable option\) and after seeing it didn’t work, I tried again installing it by means of the OSGeo4W Shell. After running the code lines for installing pandas, scipy, and NetCDF4 the shell indicates that they’re already installed \(requirement already satisfied – as in the screenshot I’m attaching here\).

‌

I would like to get some help from you in order to find the meteorological. Thank you for any help you might provide.

‌

Luis D.

**Comment by sunt05** [comment]
Just noticed your detailed reply: many thanks @rarygit !
(And as you may have noticed, we re-allocated UMEP to GH: so we can better use the synergy of our UMEP/SUEWS repos on GH).

**Comment by lf-duarte11** [comment]
Thank you so much @rarygit you helped me a lot. I couldn't thank you before because somehow I lost access to my bitbucket post. But now that is here, I hope I can let you know you really helped me!! 
Despite the ERA5 tool still isn't working on QGIS directly, your code helped me to download the data from the OSGeo4W shell.

**Comment by sunt05** [comment]
Thanks both @lf-duarte11 @rarygit for the discussion and contributions!
