### ISSUE TITLE
more land cover classes

### ISSUE THREAD

**Issue by Christian-think** [UMEP-dev/UMEP#156]
Right now, SOLWEIG supports only 7 UMEP land cover classes. Is there a possibility to add more land cover classes, like light asphalt? I tried already to edit the “landcoverclasses_2016a.txt” (added a new class with Code=8 for Light_asphalt) and created a land cover grid with a value of 8 but got an error message that the values are not appropriate.

**Comment by biglimp** [comment]
The tool is designed as user-friendly and easy-to-use as possible. That is one reason why we only use 7 LC-classes. If you like to use more LC-classed you comment out (use #) line 887-889 in **solweig.py** and then restart QGIS and try again with your additional LC-classes. solweig.py is located in _C:\Users\yourusername\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\SOLWEIG_ if you are using Windows.

**Comment by biglimp** [comment]
Capabilities to use more than 7 calsses now possible, as from 3.13.1
