### ISSUE TITLE
SEBE visualization not working

### ISSUE THREAD

**Issue by shayeldad** [UMEP-dev/UMEP#158]
Hi,

I'm trying to use SEBE visualization but I receive the following message. I would be grateful if anyone could help by checking what's wrong with my run/plugin.

_Traceback (most recent call last):
  File "C:/Users/Shay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBEVisual\sun.py", line 503, in visualize
    dataset = gdal.Open(self.plugin_dir + '/data/temp.tif')
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\osgeo\gdal.py", line 3173, in Open
    return _gdal.Open(*args)
RuntimeError: C:/Users/Shay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBEVisual/data/temp.tif: No such file or directory_

![image](https://user-images.githubusercontent.com/51439953/80305398-0b882400-87c5-11ea-9165-e3382b7e7f5c.png)

**Comment by biglimp** [comment]
Sorry for the late reply. Issues where not reported to me since we moved our repo.

Could you please give me some more info. 
- What version of UMEP are you using?
- When is the error occuring?

**Comment by biglimp** [comment]
This is probably resolved in new version 3.14. I will close this issue. Resubmit if error still exist.

**Comment by shayeldad** [comment]
Works perfectly, thank you!


Shay Eldad M.Sc.
Environmental Consultant
Amphibio Ltd.
[cid:00d801cc93dd$dea5e010$1901a8c0@yaounde]
Phone: 972-3-736-9972 ext. 4
Fax: 972-3-725-2774
1 Hayasmin St., Efal Seminar
Beit Ziva building
PO box 9108
Ramat Efal, Ramat Gan 52190
Israel
Email: shay@amphibio.co.il<mailto:shay@amphibio.co.il>
www.amphibio-ltd.co.il<http://www.amphibio-ltd.co.il/>
