### ISSUE TITLE
SUEWS Advanced generates error with updated QGIS and Panda Packages

### ISSUE THREAD

**Issue by RebWiegels** [UMEP-dev/UMEP#160]
![image](https://user-images.githubusercontent.com/62548605/82831299-5b3b3780-9eb8-11ea-938d-6909d34bd829.png)

After updating QGIS to the latest long term version 3.10.6, newly adding panda packages and updating UMEP to 3.13.1 I generate an error with SUEWS Advanced, with data I was already able to generate an outcome with. 

Do you have an idea how to solve this error?

Thank you a lot in advance!

**Comment by sunt05** [comment]
@biglimp this might be due to the recent update in SuPy with kernel 2020a, which introduced some changes in input files.
We might need to consider how to consolidate the SUEWS preparation part of UMEP and SuPy-shipped input files.
But I'll have a look later today and update us more on this.

**Comment by RebWiegels** [comment]
Hello sunt05,
thank you for looking into the error. Today I tried to run SUEWS within UMEP on a different computer (still having QGIS 3.4 Madeira installed) and already had problems downloading the tool UMEP in QGIS. I generated the following error, also after downloading the missing panda packages as explained in UMEP Manual (2.3).
![image](https://user-images.githubusercontent.com/62548605/83491497-26c80c80-a4b2-11ea-87fe-b5cade8e6b37.png)
Maybe this has to do with shiped files? I thought it might help, thank you again!

**Comment by biglimp** [comment]
I assume that 3.4 is a too old version for UMEP 3.13.1. I will soon update UMEP to work with SuPy 2020a. If you cannot wait, you can try to downgrade Supy to e.g. 2020.3.18 (pip install supy==2020.3.18).

**Comment by biglimp** [comment]
Resolved in 3.14

**Comment by RebWiegels** [comment]
Thank you for your help so far. How can I install the newest release (3.14) of UMEP? 
![image](https://user-images.githubusercontent.com/62548605/84135117-d7ea1c00-aa49-11ea-884a-f5ccc32cde41.png)
I can only find the old version 3.13, for which most of my runs with SUEWS Advanced QGIS crashes.

**Comment by biglimp** [comment]
Ops. I see now that it is still not approved by QGIS. I will check. Should probably be up in a couple of days.

**Comment by RebWiegels** [comment]
Thank you :)
