### ISSUE TITLE
UMEP shadow pattern and GRASS r.sun.incidout diff

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [UMEP-dev/UMEP#161]
This is such a cool tool so I wanted to compare it with GRASS r.sun in QGIS.
I used the following settings for UMEP and GRASS respectively

![Screenshot from 2020-05-25 22-50-39](https://user-images.githubusercontent.com/1564038/82843049-2e991700-9edc-11ea-9c4a-9191bfa98a24.png)
![Screenshot from 2020-05-25 22-52-12](https://user-images.githubusercontent.com/1564038/82843050-2f31ad80-9edc-11ea-82d6-5a661f1c643d.png)

May the 24th is the 144th day of the year https://en.wikipedia.org/wiki/May_24
I used the 12 local solar time on both (I think since no UTC offset or daylight savings was used in UMEP)

Still the difference in the angle is quite large, did I do something wrong?

![diff_umep_grass](https://user-images.githubusercontent.com/1564038/82843168-994a5280-9edc-11ea-82e9-8b4b73eb0693.gif)

The white/black image is UMEP, the grayscale is GRASS

**Comment by SimonsUnikaNamn** [comment]
It seems like the time 11 for UMEP corresponds much better to GRASS 12, why is that?

**Comment by biglimp** [comment]
There must be something related to timezone.
In UMEP you need to set the UTC based on location so if you are in e.g. Sweden UTC should be 1. Where are your location?

**Comment by SimonsUnikaNamn** [comment]
This is in Norway, but I thought if I use UTC 0 and no `Daylight Saving Time` I would use [solar time](https://en.wikipedia.org/wiki/Solar_time) just like in GRASS r.sun

When I get back home I will try to use UTC+1 and daylight savings time on both UMEP and GRASS and see if it makes sense :)

**Comment by biglimp** [comment]
Testa UTC=1 och se vad resultatet blir.

**Comment by SimonsUnikaNamn** [comment]
Vet inte om jag ska skriva på svenska eller engelska :D

![diff_umep_grass_summertime](https://user-images.githubusercontent.com/1564038/82943100-57cbad00-9f99-11ea-8284-a9c03db9090d.gif)
![Screenshot from 2020-05-26 21-38-57](https://user-images.githubusercontent.com/1564038/82943113-5e5a2480-9f99-11ea-8c61-dce582aa6aa6.png)


So I used the same settings excecpt I put the GRASS sun to +2 civil time ([summertime](http://www.tidszon.se/lista-tidszoner.php) gives +2 in sweden/norway)

In UMEP i put +1 but clicked the `Daylight Savings Time?` checkbox, which I guess should put the +1 to +2.

The difference is now larger as far as I can see it :/

**Comment by SimonsUnikaNamn** [comment]
![diff_umep_grass_summertime_1h](https://user-images.githubusercontent.com/1564038/82943840-826a3580-9f9a-11ea-9f17-d8c74f276b9c.gif)

Tried to make them match and I do so by setting UMEP to 12 and GRASS to 11, so still off by one hour. Any explanation to how this could be?

**Comment by biglimp** [comment]
So your last try is seems that the shadow are almost similar but your settings between the software is 1 hour difference? I think there are two things to check:
1. lat lon of the raster you use as extracted by the two tools.
2. The calculated sun position

I know how to get tis info from UMEP but not from GRASS. Do you?

What version of QGIS and GRASS and UMEP are you using?

Also, what tool are you using in GRASS? I dont find r.sun in the QGIS toolbox but instead r.sun.incident etc...

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by SimonsUnikaNamn** [comment]
Yes, I did some testing and even though there is a discrepancy of 1h that I can not explain it seemed like UMEP was the correct one :)
