### ISSUE TITLE
SUEWS prepare doesn't run

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/UMEP#162]
Describe the bug
i prepare all the inputs and then use SUEWS prepare plugin and don work

To Reproduce
[mediumlarge.zip](https://github.com/UMEP-dev/UMEP/files/4713546/mediumlarge.zip)

Expected behavior

Screenshots
![image](https://user-images.githubusercontent.com/61833032/83456491-7f72b780-a468-11ea-83e5-b127d427b7cb.png)

Version and platform (please complete the following information):

SUEWS version: 3.13.1
OS: Windows 10
Additional context

**Comment by biglimp** [comment]
You found a typo in the code (**fLCF_bu** should be **LCF_BU**). We will include fix in upcoming update.

**Comment by biglimp** [comment]
Resolved in 3.14
