### ISSUE TITLE
SUEWS analyzer product problem

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/UMEP#164]
hello,

i use SUEWS analyzer to create a tif with Air Temperature at 2m and the output has values like "-9999" inside and outside the grid.
![image](https://user-images.githubusercontent.com/61833032/83925003-bdd0e500-a78e-11ea-8831-e866f4ddb6ca.png)

pink pixels are the "-9999" values and green blocks is the grid that i work. I tried some different random days and hour to run the analyzer and always i had in the output this pink row in the bottom(outside the original grid that i work) and random blocks inside the grid with the same value.

**Comment by biglimp** [comment]
More info is required to resolve this.

- What version of QGIS, UMEP and Supy?
- Please provide grid ID, SiteSelect.txt and output file (filecode_YYYY_SUEWS_MM.txt) for the pink colored grid at [9,6]

**Comment by sunt05** [comment]
Please check the FAI (frontal area index) of your problematic grids.

**Comment by Empanag** [comment]
Versions 
- QGIS 3.12.3,
-  UMEP 3.13.1

I used this command to install supy that you suggested in previous issues
-  pip install supy==2020.3.18

output file for the pink ( the id is 89)
[yosh389_2018_SUEWS_60.txt](https://github.com/UMEP-dev/UMEP/files/4746451/yosh389_2018_SUEWS_60.txt)
the grid that i use
[hersmall100_grid.zip](https://github.com/UMEP-dev/UMEP/files/4746457/hersmall100_grid.zip)
and siteselext.txt
[SUEWS_SiteSelect.txt](https://github.com/UMEP-dev/UMEP/files/4746475/SUEWS_SiteSelect.txt)

the FAI is 0 for buldings and trees.

**Comment by sunt05** [comment]
> the FAI is 0 for buldings and trees.

This will for sure cause issues for grids with buildings and trees in calculating near surface meteorology (e.g., `T2`): please correct FAI to reasonable values.

**Comment by biglimp** [comment]
Did you use SUEWSPrepare to generate input data? If so, I will add a check so that FAI cannot be zero if there are buildings or trees present in a grid.

**Comment by Empanag** [comment]
Yes i have used the SUEWS prepare and i had the issue that i mentioned in issue #162 
so i tried to use old data that i had process

i tried again the analyzer for fluxes and the result was fine. I will find correct FAI output from previous run and i will inform you. I m waiting for 3.14 version for new ones.

**Comment by biglimp** [comment]
Ops. I see now that 3.14 is still not approved by QGIS. I will check. Should probably be up in a couple of days.

**Comment by biglimp** [comment]
New version now out. Please re-run and report back.

**Comment by Empanag** [comment]
i tried with the new version to do the process from the beginning and the problem still remains.
the two pixel inside the grid have the value -9999
and the raw below the grid has the value of 0.


[mediumlarge2.zip](https://github.com/UMEP-dev/UMEP/files/4758971/mediumlarge2.zip)

**Comment by biglimp** [comment]
OK, thanks. Can you please attach your geodata (DSM, DEM, CDSM and landcover)

**Comment by Empanag** [comment]
I use DSM with only 3D objects, so i use 3 tiff 

one for trees
one for buildings
one for landcover
i couldn't upload it here so this is the dropbox link to download them
https://www.dropbox.com/sh/68jdinyvz9eduv8/AAD9fhFYl9WFingqyXkwi4Kha?dl=0

**Comment by biglimp** [comment]
I have re-opened this issue.
I am confused. The pink grid shown above is not 89 but 114 according to the files in mediumlarge2.zip. Please clarify.

**Comment by Empanag** [comment]
Sorry, i didn't mentioned that this is a new run with the last update of SUEWS. So the problem is not in pixel 89 but in pixels 212 and 380.

![image](https://user-images.githubusercontent.com/61833032/84380779-9d6eb380-abf0-11ea-98d5-e89122a049aa.png)

**Comment by biglimp** [comment]
Ok, Now I see. I will fix this in up-coming version. As a quick-fix, set fai to 0.001 in your SiteSelect.txt for grid 212 and 380. Why that bottom row is strange I have no idea. Values looks ok. @sunt05 , do you have any idea, for example ID 21?

**Comment by sunt05** [comment]
The bottom row might some QGIS display error: 21 rows * 24 columns = 504 as in the siteselect file while 22 rows displayed in your posted figure here:
> 
> ![image](https://user-images.githubusercontent.com/61833032/84380779-9d6eb380-abf0-11ea-98d5-e89122a049aa.png)

**Comment by Empanag** [comment]
I updated the model to 3.14.1 but the problem remain. One raw of zeros on the bottom and random tiles with "-999" value. I tried to produce different grids but didn't solve it.

![image](https://user-images.githubusercontent.com/61833032/86474826-4a4dd380-bd4c-11ea-96bc-319780cb472a.png)

This is a different grid run that simulated with 3.14.1 version of UMEP

**Comment by biglimp** [comment]
Have you updated SuPY?

**Comment by Empanag** [comment]
No i didn't update anything else. Only UMEP from plugins inside QGIS.

**Comment by biglimp** [comment]
Then try upgrade supy also

**Comment by Empanag** [comment]
I tried using osgeo84 shell and pip install supy --upgrade for every version of QGIS(3.4;3.10;3.12). Still remains the problem.

**Comment by biglimp** [comment]
Ok thanks.
Could you please submit your inout and output data again for us to test. Also include your polygon grid and input file for SUEWSPrepare. Thanks.

**Comment by Empanag** [comment]
[mediumlarge3p.zip](https://github.com/UMEP-dev/UMEP/files/4884939/mediumlarge3p.zip)

**Comment by biglimp** [comment]
You didnt include any output data from your SUEWS run. Please do.

**Comment by Empanag** [comment]
https://www.dropbox.com/s/ojnmih1xa5m3l8y/output.zip?dl=0

**Comment by biglimp** [comment]
Thanks. 
I was able to replicate your issue.

The issue you have are actually two-folded:
1. The extra row of grids at the bottom as an issue when the vector grid is converted to raster. I think it is a rounding error and I will look into this. There are two work arounds available. i) Write the output to the polygon attribute table instead. Then you can visualise the vector dataset instead. You need to reload the vector dataset to see the changes in the attribute table. ii) Change the raster resolution to something much smaller, e.g. 2 meter. Then to bottom row will go away. Otherwise, the other grids seems fine.
2. @sunt05, Grid 212 and 380 are actual SUEWS issues. I ran the model with the data attached and got -999 for T2 for these two grids. I cannot see why. I leave that to you.

**Comment by sunt05** [comment]
@biglimp Can you please check for me: which SuPy version is used for this run?

**Comment by biglimp** [comment]
2020.6.30

**Comment by biglimp** [comment]
Actually, I just found the issue with the extra line in the raster data. I will include a fix in the next version. I will upload a development release to this repo if you would like to use now.

**Comment by sunt05** [comment]
had just gone through the input, there are two issues I can see:
- critical: the problematic grids are set with FAI=0, the main reason for invalid T2 (and other surface diagnostics);
- measurement height is always 3*Zh, which might not be sensible.

Setting a non-zero FAI would resolve the -999 issue but grid 380 still would observe abnormal T2 values.

I'll think about this case and put more suggestions here or in the SUEWS/SuPy repo, which might more relevant.

Anyway, thanks for providing this *interesting* case!

**Comment by sunt05** [comment]
@biglimp I think we can close this issue as the UMEP has been resolved while the other is a more fundamental issue related to:
1.  user input informed by more helpful guide/manual;
2.  SUEWS physics.

**Comment by Empanag** [comment]
> had just gone through the input, there are two issues I can see:
> 
> * critical: the problematic grids are set with FAI=0, the main reason for invalid T2 (and other surface diagnostics);
> * measurement height is always 3*Zh, which might not be sensible.
> 
> Setting a non-zero FAI would resolve the -999 issue but grid 380 still would observe abnormal T2 values.
> 
> I'll think about this case and put more suggestions here or in the SUEWS/SuPy repo, which might more relevant.
> 
> Anyway, thanks for providing this _interesting_ case!

just to know,before the update that import the supy, there was no problematic pixel.

**Comment by sunt05** [comment]
> > had just gone through the input, there are two issues I can see:
> > 
> > * critical: the problematic grids are set with FAI=0, the main reason for invalid T2 (and other surface diagnostics);
> > * measurement height is always 3*Zh, which might not be sensible.
> > 
> > Setting a non-zero FAI would resolve the -999 issue but grid 380 still would observe abnormal T2 values.
> > I'll think about this case and put more suggestions here or in the SUEWS/SuPy repo, which might more relevant.
> > Anyway, thanks for providing this _interesting_ case!
> 
> just to know,before the update that import the supy, there was no problematic pixel.

that's fair enough: because the previous SUEWS kernel used another simplified approach to get T2 (and other near-surface diagnostics) without explicit consideration of morphology hence "better looking" (but less accurate) results.

**Comment by biglimp** [comment]
As this is a SuPy/Suews issue and not a Suews Analyzer issue I will close this now. Please resubmit another issue if necessary.
