### ISSUE TITLE
Issue with DSM Generator

### ISSUE THREAD

**Issue by lf-duarte11** [UMEP-dev/UMEP#167]
I'm trying to create a new DSM with the generator tool. I'm introducing a DTM in tiff format and a buildings polygon layer specifying the height above sea level with the attribute height_asl but the tool only runs up to 60% and I get the following error:

2020-06-16T18:26:44     WARNING    Traceback (most recent call last):
              File "C:/Users/luisp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\dsm_generator.py", line 572, in start_progress
              dsm_array = np.array(dsm_raster.ReadAsArray().astype(np.float))
             AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

I feel like I shouldn't edit anything on the UMEP DSM generator python code, so I don't know which could be the error. Thank you if anyone could help me

![1](https://user-images.githubusercontent.com/67029932/84838136-3a6d8a00-afff-11ea-919c-f5f7801fab7b.PNG)

**Comment by biglimp** [comment]
Can you please attach the DTM and polygon layer. What OS are you using and what version of UMEP?

**Comment by lf-duarte11** [comment]
Sure, thank you so much. I'm attaching here a .zip file with the raster and the shapefile of the polygon layer.

I'm using Windows 10 Pro (64-bit), QGIS 3.12.0-București, and UMEP 3.14

[DSM Generator Issue.zip](https://github.com/UMEP-dev/UMEP/files/4792674/DSM.Generator.Issue.zip)

**Comment by biglimp** [comment]
Fixed in upcoming version 3.14.2
