### ISSUE TITLE
Typo: svf_calculator.py at line 329 - change pt to pf

### ISSUE THREAD

**Issue by rarygit** [UMEP-dev/UMEP#168]
Error thrown
svf_calculator.py at line 329, pt not defined.

if pf == 'darwin' or pf == 'linux2' or pt == 'linux':

should be:

if pf == 'darwin' or pf == 'linux2' or pf == 'linux':

then works fine.

**Comment by biglimp** [comment]
Thanks for noticing. Will include this in the next update.

**Comment by biglimp** [comment]
Fixed in upcoming version 3.14.2
