### ISSUE TITLE
SUEWS Simple won't run when using UMEP installed from ZIP

### ISSUE THREAD

**Issue by kitbenjamin** [UMEP-dev/UMEP#171]
After installing UMEP from zip file nothing happens after clicking *run*. No pop up window appears warning QGIS will freeze, as it did before.

Am following instructions from tutorial (*Add settings from test dataset*)

Works fine when using UMEP from *manage plugins*.

**Comment by biglimp** [comment]
Ah, i know what it is. I tested something and disabled the Run-button. I just put a new version in the repo. Download that one instead.
