### ISSUE TITLE
Error with SUEWS advamced when following SUEWS spatial tutorial

### ISSUE THREAD

**Issue by kitbenjamin** [UMEP-dev/UMEP#172]
Following the [SUEWS spatial](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html) tutorial.

When running SUEWS advanced I get the error attached 

Looks like something to do with using code 771 for anthropogenic in SUEWS prepare?

Can provide the SUEWS prepare output if required

[SuPy.log](https://github.com/UMEP-dev/UMEP/files/4844884/SuPy.log)

**Comment by biglimp** [comment]
Yes, please provide both input and output to SUEWSPrepare

**Comment by kitbenjamin** [comment]
Hopefully this has all you need:

[prepareIn.zip](https://github.com/UMEP-dev/UMEP/files/4845468/prepareIn.zip)
[prepareOut.zip](https://github.com/UMEP-dev/UMEP/files/4845469/prepareOut.zip)

**Comment by biglimp** [comment]
fixed in upcoming version 3.14.2
