### ISSUE TITLE
LQF error when running the tutorial

### ISSUE THREAD

**Issue by RJVogel** [UMEP-dev/UMEP#173]
I was following the tutorial on Anthropogenic heat with LQF and the data preparation step worked fine. However, when running the model, the following error appears:

object of type <class 'float'> cannot be safely interpreted as an integer.

I am running Ubuntu 20.04. I tried Python versions 3.6, 3.7 and 3.8. I tried QGIS 3.10 and 3.14. And I tried installing the UMEP plugin from QGIS and also installing the zip of this repository. Always the same error.

**Comment by biglimp** [comment]
Solved in 3.14.2 (Development release). Use SuPy-QGIS3 branch or wait until official release later this week
