### ISSUE TITLE
SEBE workflow algorithm crashes when following tutorial

### ISSUE THREAD

**Issue by kitbenjamin** [UMEP-dev/UMEP#176]
When following the tutorial on how to create workflows My QGIS crashes every time at this point (perhaps there is a better way to get a LOG file of this?)

![SEBE_crash](https://user-images.githubusercontent.com/53219529/86609810-5f24a400-bfa4-11ea-8d19-2a93d54ced6a.png)

It runs fine when using UMEP method from before.

**Comment by biglimp** [comment]
I cannot replicate this error.

Where in the tutorial is this happening (Line in rst-file)?

**Comment by biglimp** [comment]
Fixed when updated to QGIS 3.14
