### ISSUE TITLE
Question: Sky View Factor of large raster

### ISSUE THREAD

**Issue by jkittner** [UMEP-dev/UMEP#177]
Hello,
I am using your package to calculate the sky view factor in `QGIS`. While reading the [documentation](https://umep-docs.readthedocs.io/en/latest/pre-processor/Urban%20Geometry%20Sky%20View%20Factor%20Calculator.html) I found that large rasters should not work well and the raster must be tiled beforehand. I tried using `VRT` and  passing the `.vrt` file to the tool, but this is even slower than directly passing a large raster.
I need to process a raster with ~90 mio. px. I tiled it into ~120 tiles and each takes ~2-3 min to process. But I don't want to click through all 120 times, change the filename and so on. Is there an option to create a batch process or can I access it directly from the command line or from Python?

**Comment by biglimp** [comment]
As from a couple of months ago, **UMEP for processing** is available through QGIS. This makes is possible to either run a UMEP tool as a batch process or access tools via the processing Python library and the console In QGIS. That is what you are looking for. UMEP for processing is available through Manage and Install Plugins in QGIS. Remember when you tile your raster for extensive SVF-calculations that you use an overlap (50-100m) to reduce edge effects.

If you set up a batch process or python code, would you be willing to share this? I think other UMEP users also would find this very useful.

/Fredrik

**Comment by jkittner** [comment]
Thanks for your fast reply. I did not know about this but that seems to be exactly what I need. How can I access the tool from python?
When running:
```python
for alg in QgsApplication.processingRegistry().algorithms():
    print(f'{alg.id()}: {alg.displayName()}')
```
`umep:any_of_the_tools`  does not appear. Do I have to add a different path with `sys.path.append()`?

**Comment by biglimp** [comment]
I recommend that you have a look at this tutorial. In the end you see the syntax for accessing UMEP through processing.

https://tutorial-docs.readthedocs.io/en/latest/Tutorials/IntrodutionToProcessingSEBE.html#processingsebe

**Comment by jkittner** [comment]
Thank you so much for your help. I managed to calculate the SVF using the batch process. Unfortunatelly I don't have time to dig deeper into this at the moment. I'd love to add some more documentation regarding this later on!
