### ISSUE TITLE
persistent `package missing` issue when launching QGIS+UMEP

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#178]
issue raised from workshop:

> Another general question, I got through with the first two exercises, shut down QGIS, reopened it and it was stuck loading up saying "Restoring loaded plugins", the only way for me to fix this so far was to force quit QGIS and start it up again. 
It then starts normally, but is telling me that UMEP is now disabled, because it previously crashed QGIS. When I hit Enable Plugin this enables UMEP again and gives me the following message. This happens every time I close QGIS and restart it.
![6a11c8a7-57af-490b-b5cb-e56810e491f4](https://user-images.githubusercontent.com/1802656/86903130-d1ad9500-c106-11ea-9ebe-32b81ea6f896.jpg)

**Comment by sunt05** [comment]
@biglimp this seems to be a common issue for various Mac people, we may need to invoke more specific alerts telling us: which packages are not properly installed.

**Comment by biglimp** [comment]
This message comes from a try statement where the install supy function is included, the one that you made.

**Comment by hamidrezaomidvar** [comment]
Is there any solution for this problem? I am encountering the same problem, and it does not let me install UMEP.

**Comment by sunt05** [comment]
Try to install a recent dev version of SuPy using the QGIS-shipped python.

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by sunt05** [comment]
this is resolved.
