### ISSUE TITLE
About SOLWEIG Issue

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#179]
https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io/issues/10

by @sleepyheadzzzzzz

> Hello!
I'm a student from Aalto University and I meet one issue when I try to generate Tmrt map of Helsinki. Hoping you can help me out.
When I try to generate the map through SOLWEIG function, it jump the python error:  NumPy boolean array indexing assignment cannot assign 0 input values to the 472045 output values where the mask is true.
 All my documents included were successfully generated by Pre-processor. And the success of the test dataset on your website prove it not caused by the bug of the plugin. Do you have any idea about the solution?
![111](https://user-images.githubusercontent.com/68614342/88099375-c137f880-cba3-11ea-8cce-dc1495a0bbce.png)
![222](https://user-images.githubusercontent.com/68614342/88099382-c39a5280-cba3-11ea-8e65-0cc4f3daa506.png)

**Comment by biglimp** [comment]
Fist update UMEP and try again. You are using a very old version.

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by biglimp** [comment]
I will now close this issue as no response came in (since August 2020)
