### ISSUE TITLE
Analyzer error 'NoneType' object has no attribute 'GetLayer'

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/UMEP#180]
hi, i tried to use analyzer to generate a tiff of SUEWS products and i get this error from analyzer. I restarted the program and still nothing.

![image](https://user-images.githubusercontent.com/61833032/88665180-e6b68c00-d0e6-11ea-894c-c7cc0e37f2c9.png)

**Comment by biglimp** [comment]
More info is needed. 
- What versions of UMEP and QGIS are used?
- Can you replicate you error using data from this tutorial (https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html#suewsspatial)?
- What os are you using?

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by Empanag** [comment]
it is a bug i fixed it, i think i removed and reopened the shp.
