### ISSUE TITLE
error when trying to install plugin

### ISSUE THREAD

**Issue by shayeldad** [UMEP-dev/UMEP#183]
When trying to load the plugin I get the following message:
_Couldn't load plugin 'UMEP' due to an error when calling its classFactory() method_ 

Here's a screenshot:

![image](https://user-images.githubusercontent.com/51439953/91706677-5eb11f80-eb87-11ea-9a28-f3ea6a63fecf.png)

Appreciate your help :)

**Comment by biglimp** [comment]
Without seeing the whole error message it looks like you have the wrong scipy version installed. Please provide full eroor message, OS, versions of QGIS and UMEP as well as installed python libraries by pip list command (see https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities for more info)

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by Empanag** [comment]
close
