### ISSUE TITLE
issue with DSM generator

### ISSUE THREAD

**Issue by Soph-38** [UMEP-dev/UMEP#184]
Hello,
I am trying to generate a DSM from DEM and vector layer with building height information using the DSM generator.
I use **Qgis 3.14, UMEP 3.15.3, under linux system**.

**I get the following error from terminal** :
Warning 6: Normalized/laundered field name: 'height_asl' to 'height_a_2'
ERROR 1: hSrcDS == NULL
ERROR 1: hSrcDataset== NULL
ERROR 4: /home/herpin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP/DSMGenerator/temp/clipdsm.tif: Aucun fichier ou dossier de ce type

**And the following error from python Qgis interface :**               
File "/home/herpin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP/DSMGenerator/dsm_generator.py", line 647, in start_progress
              dsm_array = np.array(dsm_raster.ReadAsArray().astype(np.float))
             AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

The area under study is a small area (for testing), in Angers, France. I use SRC IGNF:LAMB93 (it is a reference for France and IGN, the coordinate system is in meters).
DEM : MNT interpolated at 1m resolution, from BD_ALTI IGN France
vector layer with buiding height : from BD_TOPO IGN France, field : "Hauteur"

When I run your tutorial on covent garden, London, everything is fine. I do not get why it is not working with the data from Angers, everything seems to fit the requirements asked by UMEP. The errors messages are not clear to me.

I attach the small set of data I use.
/media/herpin/DATA/Enseignement/AGROCAMPUS/M2/IEVU/2020-2021/CAS_ETUDE/bd_alti_small_v3_1m.tif
/media/herpin/DATA/Enseignement/AGROCAMPUS/M2/IEVU/2020-2021/CAS_ETUDE/SIG/batiment_angers_small_polygon.prj
/media/herpin/DATA/Enseignement/AGROCAMPUS/M2/IEVU/2020-2021/CAS_ETUDE/SIG/batiment_angers_small_polygon.shp
/media/herpin/DATA/Enseignement/AGROCAMPUS/M2/IEVU/2020-2021/CAS_ETUDE/SIG/batiment_angers_small_polygon.shx

Thanks

**Comment by biglimp** [comment]
Cannot find the files attachment. Please try to attach again.
This error message (AttributeError: 'NoneType' object has no attribute 'ReadAsArray') indicates that the polygon and raster is not located in the same place due to e.g. CRS differences.

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :
https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by Soph-38** [comment]
You can download files from the following link, thanks :

https://filesender.renater.fr/?s=download&token=ea580855-46b8-4560-8732-e39b29b3a472

**Comment by biglimp** [comment]
I cannot replicate your error on my Windows PC. However, I did not succesfully create a DSM from your data. @nilswallenberg, who wrote the code found some issues and now I can create a DSM from your data on my PC. Now please try on your linux system using the attached UMEP version (zip).
[UMEP.zip](https://github.com/UMEP-dev/UMEP/files/5174880/UMEP.zip)
[testdsm.zip](https://github.com/UMEP-dev/UMEP/files/5174886/testdsm.zip)

**Comment by Soph-38** [comment]
Thanks for updated code. In installed it but I still get the same errors though and cannot generate the DSM.
I uploaded your DSM and it looks right indeed.
In fact, I used before the just previous version (N-1) of UMEP, and the DSM generator was running all way through, without error, and generated a DSM but which was not correct, meaning equal to MNT, without building addition.
Is it possible that you send the previous version of UMEP 3.15, but with your new code of DSM generator ?
Thanks

**Comment by biglimp** [comment]
You can download this yourself (e.g. version 3.15.1) och just replace the DSMGenerator-folder from the version you want to use.

This is obviously a linux-related issue. I suspect that it has to do with gdal versions.

You can also try to reproject your data into a more universal CRS e.g. UTM and see if that solves the issue.

**Comment by Soph-38** [comment]
I could get the new version of DSMgenerator that you sent to work. This produces a good DSM on the tested input data, thanks

**Comment by biglimp** [comment]
Great. Then I will close this issue.

**Comment by Soph-38** [comment]
Hello,
Is the fixed code for DSM generator now included in the last version UMEP release ?
Thanks

**Comment by nilswallenberg** [comment]
It should be! :)
