### ISSUE TITLE
Issue with SOLWEIG

### ISSUE THREAD

**Issue by Soph-38** [UMEP-dev/UMEP#186]
Hello,

When trying to run SOLWEIG on my data (no vegetation and no landcover scheme), I get the following error :

AttributeError: 'SOLWEIG' object has no attribute 'dsmcopy' 
Traceback (most recent call last):
  File "/home/xxxx/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP-0f31bd79fe5d79be08c624115324e98a906f229d/SOLWEIG/solweig.py", line 735, in start_progress
    buildings = self.dsmcopy - self.dem
AttributeError: 'SOLWEIG' object has no attribute 'dsmcopy'

Version de Python : 3.8.2 (default, Mar 26 2020, 15:54:48) [GCC 7.3.0] 
Version de QGIS : 3.14.0-Pi Pi, exported 
Version UMEP is 3.15.1
under linux OS

I attach the following input data files for DSM, DEM, Wall height and aspect, SVF, meteo data, that you can download with following link : 
https://filesender.renater.fr/?s=download&token=234f6e79-8f42-422e-8600-87ed673668cc

The SCR is IGNF:LAMB93, the location is Angers, France.

**Comment by biglimp** [comment]
That was a bug that was fixed some versions ago. Try using UMEP 3.15.3 

I think yI recall you having an issue with some other tool and now maybe have a mix of versions (and if you want to keep this, just replace solweig.py form the latest commit in the repo (SuPy-QGIS branch))

**Comment by Soph-38** [comment]
OK I tried using UMEP 3.15.3 together with updated version of DSM generator and this is working.
You can close the issue, thanks.
