### ISSUE TITLE
PET for every pixel in SOLWEIG

### ISSUE THREAD

**Issue by Christian-think** [UMEP-dev/UMEP#187]
Hello,
As far as I know SOLWEIG only supports the calculation of PET for single points. My question now is, is there any theoretical / physical reason for this (something to do with the limitations of the SOLWEIG model?) or was there simply no need for a calculation of the PET for the total area/every pixel like for the MRT?
I'm asking because I created a little workaround that allows me to output the PET for every pixel as a raster. (create a point for every pixel, run SOLWEIG with these hundreds of thousands of POIs, merge the hundreds of thousands of PET-text-files and convert them into a raster). And now I'm not sure if these PET values for each pixel of the AOI are valid or if there was a reason why SOLWEIG does not offer this option?

Best Regards

**Comment by biglimp** [comment]
The reason is that we dont calcualte wind speed at each grid point and this is a essential parameter when calculating PET and UTCI.

**Comment by Christian-think** [comment]
Ok, if I understand you correctly, then solweig assumes the same wind speed for each POI no matter where it is located. This may be reasonable for single points but not for the whole area?

**Comment by biglimp** [comment]
Yes, correct.
