### ISSUE TITLE
Tree Generator not working

### ISSUE THREAD

**Issue by vsoubry** [UMEP-dev/UMEP#188]
Hello, I am having problems with the Tree Generator tool. I am using the 3.14 version of QGIS, with the latest UMEP version. My problem is similar to another similar issue that was mentioned on this forum in 2018, but i followed what was mentionned there and i can't seem to find a solution. 
I have a shp with the different point (trees) that i want to generate, with the fields added (ttype, totheight, diameter, trunk). Everything is fine and the MNS and MNT are the same pixel size and spatial extent, but when i run Tree Generator it generates the cdsm and the tdsm, but there are no values generated. Its all filled with zeros. A lot of times when i try to run the tool there is zero computing time, sometime a bit of computing time. 
[TreeGeneratorproblem.zip](https://github.com/UMEP-dev/UMEP/files/5306705/TreeGeneratorproblem.zip)

I have linked the data that i am using with this message, can anyone please help? This part is crucial to the realization of my masters thesis.

**Comment by biglimp** [comment]
I will answer this in the email list instead.
