### ISSUE TITLE
error in SOLWEIG

### ISSUE THREAD

**Issue by thorntree2** [UMEP-dev/UMEP#189]
Hi, I'm trying to get tmrt using SOLWEIG.
I already got SOLWEIG of 5m, 25m resolution with the same meteorological data and same coordinate system.
However, only 50m resolution makes this error.
What is the problem?
Please help me.

The error contents in QGIS are as follows.
---------------------------------------------------------------------------------------------------------------------------------------------
2020-10-06T15:36:10     CRITICAL    EXCEPTION IN C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SOLWEIG\solweigworker.py, 
             LINE 286 "timeaddW, timeaddN, timestepdec, Tgmap1, Tgmap1E, Tgmap1S, Tgmap1W, Tgmap1N, CI, TgOut1, diffsh, ani)" 
             ERROR MESSAGE: local variable 'weightsumwall_first' referenced before assignment
----------------------------------------------------------------------------------------------------------------------------------------------

And this is reference document of 50m resolution.
--------------------------------------------------------------------------------------------------------------------------------------------
This file provides run settings for the SOLWEIG run initiated at: Tue, 06 Oct 2020 15:36:10
Version: SOLWEIG v2019a

SURFACE DATA
Digital surface model (DSM): D:/02_WORK/01_GWJU/04_SOLWEIG/81_Sample/01_raster/dsm50
Model domain: rows = 504, columns = 730
Projected referece system: unnamed
Geographical coordinate system: Unknown datum based upon the GRS 1980 ellipsoid
Latitude: 35.04092742931634
Longitude: 126.63420126809487
UTC: 9
Vegetation scheme inactive
Landcover scheme inactive

DEM used to identify buildings
METEOROLOGICAL FORCING DATA
Meteorological file: D:/02_WORK/01_GWJU/04_SOLWEIG/10_Data/met_190729.txt

HUMAN EXPOSURE PARAMETERS
Absorption, shortwave radiation: 0.7
Absorption, longwave radiation: 0.95
Posture of human body: Standing
ENVIRONMENTAL PARAMETERS
Albedo of walls: 0.2
Albedo of ground (not used if land cover scheme is active): 0.15
Emissivity (walls): 0.9
Emissivity of ground (not used if land cover scheme is active): 0.95

ADDITIONAL SETTINGS
Human considered as a standing cylinder
Isotropic sky
----------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/72433270/95169079-43bc7580-07ed-11eb-93e5-ac28f12a1b9f.png)

This is reference document of 25m resolution.
----------------------------------------------------------------------------------------------------------------------------------------------
This file provides run settings for the SOLWEIG run initiated at: Tue, 06 Oct 2020 15:59:03
Version: SOLWEIG v2019a

SURFACE DATA
Digital surface model (DSM): D:/02_WORK/01_GWJU/04_SOLWEIG/01_Raster/03_DSM/dsm_25m
Model domain: rows = 1007, columns = 1457
Projected referece system: unnamed
Geographical coordinate system: Unknown datum based upon the GRS 1980 ellipsoid
Latitude: 35.04092742931634
Longitude: 126.63420126809487
UTC: 9
Vegetation scheme inactive
Landcover scheme inactive

DEM used to identify buildings
METEOROLOGICAL FORCING DATA
Meteorological file: D:/02_WORK/01_GWJU/04_SOLWEIG/10_Data/met_190729.txt

HUMAN EXPOSURE PARAMETERS
Absorption, shortwave radiation: 0.7
Absorption, longwave radiation: 0.95
Posture of human body: Standing
ENVIRONMENTAL PARAMETERS
Albedo of walls: 0.2
Albedo of ground (not used if land cover scheme is active): 0.15
Emissivity (walls): 0.9
Emissivity of ground (not used if land cover scheme is active): 0.95

ADDITIONAL SETTINGS
Human considered as a standing cylinder
Isotropic sky
----------------------------------------------------------------------------------------------------------------------------------------------

I don't know why the 25m resolution has no errors, and the 50m resolution has error.
Please help me...

**Comment by biglimp** [comment]
This model is not really designed to run with that course resolution. Then the separation between buildings and street will become difficult. That is probably what caused your error. I have no really good solution. Why do you want to use such large pixels?

**Comment by thorntree2** [comment]
I wanted to consider the calculation time and accuracy of the model according to resolution.
After hearing your opinion, I think you are right. It seems to be unnecessary consideration.
Thank you for your comment.
But I am still just curious.
Why does the model run when the UTC is 0?
Although the results are all wrong.
When the UTC is 9, the model doesn't run at all.
What is the reason for Python's error?
Even if it is a wrong result, can't I run the model?

**Comment by biglimp** [comment]
Since you didn't provide an error message it is hard for me to comment. However, the model make use of different code depending if day or night time. I assume that this error is caused by this, i.e. that setting it to UTC 9 you either switch from day to night or vie versa. UTC is used to calculate sun position.

As this is no issue I will close the this. Feel free to continue the discussion in the email list.

**Comment by thorntree2** [comment]
Thanks.
I attach SOLWEIG capture and error capture.
SOLWEIG window just stop without separate error message.
Only QGIS shows me error message.

If tou don't mind, I'll compress my data(DEM,DSM,SVF,Metadata) and send to
you, so can you review it?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20.
10. 08. 오후 12:55:20

2020년 10월 7일 (수) 오후 4:20, biglimp <notifications@github.com>님이 작성:
