### ISSUE TITLE
Further additions to the processing toolbox

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#190]
Hi all, just wondering if there are plans for more parts of the UMEP plugin to migrate to the processing toolbox in the near future?

**Comment by biglimp** [comment]
Yes, definitely. The issue is to find time to do it. You can see which tools that are planned to be migrated here (https://umep-docs.readthedocs.io/en/latest/UMEPforProcessing.html). If you have any wishes, on which tools we should do next, dont hesitate to say.
/Fredrik

**Comment by bweeding** [comment]
Hi Fredrik, I'm a doctoral student in Tasmania (Australia) and would love
to see primarily SOLWEIG (and the related processing tools) migrated to the
processing toolbox!

Cheers
Ben Weeding

**Comment by biglimp** [comment]
Actually, SOLWEIG is added in the latest version (as from 14 september). Just update the tool to version 0.5 you will find it. Most related preprocessing tools are already there (SVF-calculator, Wall Height and Aspect). 

Remember that umep for processing is still experimental so please dont hesitate to submit issues if something is not working or if you get strange result. I will close this issue now.

**Comment by bweeding** [comment]
Ah fantastic, thank you! I will be in touch if I find any issues.
