### ISSUE TITLE
Cannot select columns in input file for meteorological variables in Metdata processor

### ISSUE THREAD

**Issue by cpk105** [UMEP-dev/UMEP#191]
Hi,

I'm working with the data in this tutorial: https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html

I'm loading the meteorological data (Fig. 28). I cannot select columns in the input file in Metdata processor:
![image](https://user-images.githubusercontent.com/54835679/96561459-55cd0680-130b-11eb-9cf3-bca3e377e448.png)

I'm using Windows and QGIS 3.10. 

Does anyone know the solution for this problem? Thank you.

Paul

**Comment by biglimp** [comment]
I cannot replicate your error. I am using QGIS version 3.14.
What version of UMEP are you using?

Try to restart QGIS and try again. Also, you need to specify tab as separator before you load the file.

![image](https://user-images.githubusercontent.com/11908356/96573017-da992f80-12cd-11eb-93d8-9733461301a8.png)

**Comment by Empanag** [comment]
Try to use the right column separator(\tab probably) and after load the file.

**Comment by cpk105** [comment]
Thank you biglimp and Empanag for your comments. I found the solution: I need to choose the correct column separator BEFORE loading the file.
