### ISSUE TITLE
Meteorological file adjustments for Southern Hemisphere

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#195]
Just wondering if there are any built in options to adjust the day of year variable for calculations based in the Southern Hemisphere?

I'm generating a UMEP meteorological file using python, and while I can alter the day of year variable in my file, when it comes to referring to plots etc. this is less than ideal. 

Cheers
Ben Weeding
PhD candidate
University of Tasmania

**Comment by suegrimmond** [comment]
Sorry this is unclear. The DoY are the same in the SH and NH. DLS takes SH vs NH into account. Please can you explain what the problem is or show an example

**Comment by bweeding** [comment]
Apologies, there were unknown issues with UTC timings in my files. Resolved.
