### ISSUE TITLE
Problems with SOLWEIG and SOLWEIG Analyser

### ISSUE THREAD

**Issue by vsoubry** [UMEP-dev/UMEP#196]
Hello everyone, 
I am doing my master's thesis on the importance of tree placement in Montreal, and how their configuration impacts the Tmrt. 
I have 2 issues that might be correlated. 

1. I have executed SOLWEIG with all data linked with this issue. And when i try to generate a Diurnal Average with the SOLWEIG Analyser I have multiple python errors that pop up. The most common being : "Attribute Error : 'NoneType has no atrributes 'ReadAsArray' (screenshot linked with this). 

2. I did a run of SOLWEIG, without a LandCover (I thought it wasnt necessary since there is only Pavement and Buildings in the map but if the lack of a LandCover is what generates this, it was my next step to make one). The meteorological data I used is recorded every minute (why the linked data is so heavy). The problem i have is that the Tmrt goes to values of up to 82 degrees Celsius at some hours and the maximum recorded temperature that day is around 36 degrees Celsius. I thought theses anomalies were generated by the building temperatures (which apparently shouldn't be considered), but the temperatures at ground level are also very hot (up to 62 degrees at some hours). What is generating theses mistakes? 

Keep in mind that MNS is DMS and MNT is DEM (its the equivalent in french). 
I have linked : the whole folder where the SOLWEIG run was made (including all Tmrt maps and the run script), the points of tree placements (CDSM and TDSM (keep in mind that their placement isnt optimal and will be changed in the future)), the DMS and DEM, the formatted meteorological data (for SOLWEIG), the wall height and aspect and the SVF. The screenshot is also linked in the folder. 

I have linked this file on OneDrive here since the files are around 1Go : 

https://uqam-my.sharepoint.com/:u:/g/personal/ag691027_ens_uqam_ca/EWWXWeDisFxHsv8h87RHjRoBmKATM-DUGW3ZRlp4rlOlOg?e=YbDqqg

Please help me figure out what is wrong, it would mean the world to me. 

Thank you very much. 

Victor Soubry

**Comment by biglimp** [comment]
Your first issue is actually a bug. IT will be fixed in upcoming version. A quick-fix is to remove all files that ends with .xml in the Solweig output folder

The second issue is due to your metdata. 
First of all, 1 minute data is kind of pointless to use and your should average it to e.g. 15 minutes or even longer.
Second, Your metdata is strange as Kdn peaks around 4 pm when it should peak around noon (when the Sun is at its highest elevation during the day). That is why you such high Tmrt values. At the same time you have very high solar radiation at 4 pm but also the angle of which the Solar beam hits the standing cylinder during afternoon makes shortwave radiant load unreasonable high. Maybe your metdata is in UTC = 0? That might explain the offset...

**Comment by vsoubry** [comment]
Yes maybe the offset is generated from the UTC. But it would be weird that the recorded data isn't in the time zone where it was taken... Still i'll ask the meteo station about that. 
Also yes i'll have to do some averaging for the data since its getting pretty long to process all the maps... 

Thank you again for your time. Please don't close this just yet, i'll probably have following questions soon.

**Comment by bweeding** [comment]
> 
> 
> Your first issue is actually a bug. IT will be fixed in upcoming version. A quick-fix is to remove all files that ends with .xml in the Solweig output folder
> 

I'm having the same problem. When you say the output folder, do you mean where we are trying to save the image, or the 'model output folder' we select in the analyzer. I can't find .xml files in either.

**Comment by biglimp** [comment]
No, I mean where you save your solweig results (model output folder) so where you Tmrt rasters are located. In the data you attached there was a number of xml files in the TMRT folder. They might be hidden depending on your windows settings. Choose to show hidden files in your explorer and also make sure to show endings of filenames, i.e. full file names

**Comment by vsoubry** [comment]
I have a subsequent question. 
When i add POIs to a run of SOLWEIG, the results are different. It seems that the POIs diminish the Tmrt. 
To be clear, i did 2 runs with exactly the same parameters, except for the second one having POIs in it. 
Why is this happening?

**Comment by biglimp** [comment]
It should not change anything in the model. The only thing that POI to is to output data from specific point in the model domain. Re-check your settings again and if the issue still exist, send the data with a detailed explanantion on how you run the model for the two cases.

**Comment by biglimp** [comment]
If you still have problems with the above POIs issues, attach the data with a detailed explanation. Otherwise this issue will be closed.
