### ISSUE TITLE
How can hourly irrigation data be used in UMEP?

### ISSUE THREAD

**Issue by cpk105** [UMEP-dev/UMEP#197]
Hi

If hourly irrigation data for each polygon grid is know, how can I include that data?

How can I control how the applied irrigation, e.g. 10 mm, is distributed over different surfaces (e.g. 6 mm for grass and 3 mm for deciduous trees and 1 mm for paved surface)?

Thank you very much for your help!

Paul

**Comment by cpk105** [comment]
I have tried to include the hourly irrigation data in the "External water use [Wuh]" column in the meteorological input file (https://suews-docs.readthedocs.io/en/latest/input_files/met_input.html?highlight=external#ssss-yyyy-data-tt-txt) and successfully run the model. However, the "Irrigation [Irr]" column in the SUEWS output files did not show any irrigation, i.e. 0 mm.

The files that I used to run SUEWS are attached. 
[SUEWS prepare.zip](https://github.com/UMEP-dev/UMEP/files/5504479/SUEWS.prepare.zip)

**Comment by suegrimmond** [comment]
please raise this issue on the SUEWS GitHub site  https://github.com/Urban-Meteorology-Reading/SUEWS

**Comment by Empanag** [comment]
The irrigation code from SUEWS_siteselect.TXT should match with the code of your input of profile inside the SUEWS_Irrigation.txt. the prefix code is without irrigation. So you have to create a profile inside Suews prepare that will be created inside the irrigation file and the code inside the siteselect file must be the same. This can be edited in irrigation tab inside Suews prepare.

If you want to use your inputs maybe you need to change water use from Suews advance process from modelled to observed.
