### ISSUE TITLE
Plotting PET in SOLWEIG

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#199]
Just wondering if there are plans to allow PET to be plotted using the SOLWEIG analyser?

**Comment by biglimp** [comment]
PET can only be plotted for single points (POIs) at the moment as SOLWEIG is not considering spatial variation of wind fields. Maybe this will be added in the future but nothing is in the pipeline

**Comment by bweeding** [comment]
Ah yep, I'm aware that it would only be able to be plotted for points of interest, but it doesn't appear in the variable list for the analyser. I have checked that PET is available in the output files.

**Comment by biglimp** [comment]
Aha, now I get it. I will add this in the next version. Thanks for reminding me.
