### ISSUE TITLE
Projected reference system error

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#200]
I'm getting the following Python error:

![image](https://user-images.githubusercontent.com/57697604/99621884-149c5380-2a7d-11eb-9181-8b3711535b13.png)

I'm guessing this is to do with the CRS of one of the input files? Is there a clear fix to an error like this?

Cheers
Ben

**Comment by biglimp** [comment]
What version of UMEP and QGIS are you using? Please also attach your dsm.

**Comment by bweeding** [comment]
I'm using UMEP 3.15.4 and QGIS 3.12.3-București.

I produced the DSM using Fusion from a .las file, by individually extracting the points classified as ground and building, and using canopy model to combine them.

[DSM_clipped.zip](https://github.com/UMEP-dev/UMEP/files/5570094/DSM_clipped.zip)

**Comment by biglimp** [comment]
Your DSM need to have a CRS defined. Use e.g. Assign Projection from ther RAster menus in QGIS.
