### ISSUE TITLE
Cannot create DSM from OSM with custom extent from map canvas

### ISSUE THREAD

**Issue by GISbukten** [UMEP-dev/UMEP#202]
2020-11-26T11:04:25     WARNING    Traceback (most recent call last):
              File "C:/Users/Jessica Henestål/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\dsm_generator.py", line 276, in start_progress
              extDiffmaxy = lonmaxetx - extentDEM.yMaximum() # If larger than zero = warning #changed to gdal 3
             NameError: name 'lonmaxetx' is not defined

**Comment by nilswallenberg** [comment]
Hej,

Testa byta ut dsm_generator.py i "C:/Users/Jessica Henestål/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\" mot den nya som finns i zip-filen som jag har bifogat här. Starta sen om QGIS. Tror vi bara har slarvat lite med stavning i koden. :)

Nils
[dsm_generator.zip](https://github.com/UMEP-dev/UMEP/files/5602633/dsm_generator.zip)

**Comment by suegrimmond** [comment]
@nilswallenberg  = please can we use English so others also know the solution - thanks for solving

**Comment by nilswallenberg** [comment]
Yes, of course. My bad! I think it was just some misspelling in the code. The new attached file (dsm_generator.py) should replace the old one in the plugins directory for QGIS.

Sorry for any inconvenience! @suegrimmond

**Comment by biglimp** [comment]
@GISbukten , Did you solve this issue by using the new code attached by Nils? IIf so, I would ilke to update the tool for other users as well.

**Comment by GISbukten** [comment]
Hello everyone!
The new pythonfile Nils provided indeed solved the issue I had. Thank you:)

**Comment by GISbukten** [comment]
@biglimp @nilswallenberg

**Comment by biglimp** [comment]
Thanks. Then I update our repository and close this issue.
