### ISSUE TITLE
Invalid index to scalar variable: UMEP Footprint

### ISSUE THREAD

**Issue by ghost** [UMEP-dev/UMEP#203]
Hello,

At the beginning I followed the script for UMEP footprint creator and worked with the sample data. This worked well for a single footprint. Afterwards I wanted to create a climatology using an input file. Unfortunately i get the same error again and again and i couldn‘t fix it despite many tries. I have used the sample raster layers from London (see email notes).

I get the following error:

Traceback (most recent call last):
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\FootprintModel\footprint_model.py", line 573, in start_process
    maxfetch=r,rm=Rm)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\FootprintModel\KingsFootprint_UMEP.py", line 168, in footprintiterKAM
    rotatedphi = scnd.rotate(full, rotang[0], order=0, reshape=False, mode='nearest')
IndexError: invalid index to scalar variable.

I checked the maximum fetch, installed the non-existent python packages and tried the Kormann, Meixner (2001) and Kljun et al (2015) model. Unfortunately i haven‘t managed to fix the error yet.  

Best regards

**Comment by biglimp** [comment]
Can you please attach your met forcing file and give info on what geodata you have been using. We need this info when we forward this the appropriate person.
Also, specify which version UMEP, QGIS and what OS you are using.

**Comment by ghost** [comment]
Yes, of cause.

UMEP Version 3.15.4. 
QGIS-Version 3.16.1-Hannover
windows 10 home 64-Bit

I have used the data from the manual:
[test.txt](https://github.com/UMEP-dev/UMEP/files/5665852/test.txt)
[DEM_LondonCity_1m.tif.aux.txt](https://github.com/UMEP-dev/UMEP/files/5665853/DEM_LondonCity_1m.tif.aux.txt)
[DSM_LondonCity_1m.tif.aux.txt](https://github.com/UMEP-dev/UMEP/files/5665854/DSM_LondonCity_1m.tif.aux.txt)

(https://umep-docs.readthedocs.io/en/latest/pre-processor/Urban%20Morphology%20Source%20Area%20(Point).html)

**Comment by biglimp** [comment]
I think is fixed now. Download the latest development release from this repo (https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable) and try it out. I will close this now. We can re-open if issue is not resolved.

**Comment by ghost** [comment]
Hello. Thank you for your help. Unfortunately, there is another Python-issue. 

Traceback (most recent call last):
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\FootprintModel\footprint_model.py", line 596, in start_process
    np.savetxt(self.folderPath[0] + '/' + pre + '_' + 'SourceMorphParameters.txt', mat, fmt=('%5.5f'), comments='', header=header)
  File "", line 6, in savetxt
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\numpy\lib\npyio.py", line 1357, in savetxt
    open(fname, 'wt').close()
PermissionError: [Errno 13] Permission denied: 'C:/Users/user/Desktop/DataSmallAreaLondon/r_SourceMorphParameters.txt'

**Comment by biglimp** [comment]
This error indicates that you trying to write to a file that you either have no permission to write to or maybe it is open and therefore not accessible. Try using another prefix and see it that helps.

**Comment by ghost** [comment]
All right. Thank you
