### ISSUE TITLE
Accessing UMEP processing tools from an external python environment

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#205]
If I'm looking to run QGIS python code outside of the QGIS python environment, and want to use one of the built in processing tools, I can do it using :

from qgis import processing

processing.run("QGIS:tool_of_choice",{blah,blah})

What needs to be done in order to use a UMEP tool in such a situation?

**Comment by biglimp** [comment]
You need to add a couple of lines to tell your script the location of the UMEP code. This can be found in the processing tutorial. I will also move this info to the main website.
https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/IntrodutionToProcessingSEBE.html#accessing-algorithms-in-a-stand-alone-python-script
