### ISSUE TITLE
LCZ converter can not get grid index

### ISSUE THREAD

**Issue by j3r3m1** [UMEP-dev/UMEP#206]
Hi,
I have tried the LCZ converter for the city of Cork.
I load the .tif downloaded from WUDAPT and transform to EPSG3857
I have created a 200x200 m polygons grid within the raster area in the EPSG3857. I select it and set the _id_ as _id_field_.

However, when I run I get an error which seems related to this index name:
```
Traceback (most recent call last):
  File "/home/decide/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP/LCZ_Converter/LCZ_converter.py", line 669, in start_progress
    typetest = fields.at(idx).type()
KeyError: '-1'
```
Any idea why do I get this error ?

**Comment by biglimp** [comment]
Does id_field include unique values and what datatype is this field?
Did you try the tutorial related to this tool and if so, did it work on your Ubuntu? I know this tutorial and tool was developed by a mac-user...

**Comment by j3r3m1** [comment]
OK I went through the tutorial, it works on my Ubuntu.

The problem was related to the fact that my grid was not saved into a file. I did not know it would not work. If not possible to deal with temporary layers, would it make sense to test whether the grid is saved into a file, if not return an error ?
