### ISSUE TITLE
SUEWS Prepare Issue

### ISSUE THREAD

**Issue by flgebhardt** [UMEP-dev/UMEP#207]
Hello, I'm trying to use SUEWS advanced on a grid with 307 cells over a period of about 2 weeks. Here Qgis craches, probably because of my small RAM (4gb). Now I try to split the grid in smaller parts to process each of them alone, and merge the output later. Now, when I use SUEWS prepare to produce inputs for each part using excactly the same data (which worked fine with the total grid) it returns the following error: 

    LINE 420 "zMax = max(float(IMPveg_max_dec),float(IMP_max))" 
             ERROR MESSAGE: local variable 'IMPveg_max_dec' referenced before assignment

I'm using UMEP 3.15.4 with QGIS 3.16.1-Hannover on windows

**Comment by biglimp** [comment]
Difficult to say what is happening. Please attach all the data used in SUEWSPrepare. However, we will probably not be able to look at this until after Christmas. Also check any logfile created by SuPy.

One workaround would be to cut the file SiteSelect.txt into separate smaller files (fewer rows).

**Comment by flgebhardt** [comment]
okay I there were missing some values in the tree morphology file. After fixing this it worked! 
But now QGIS still craches when using SUEWS advanced even with strongly reduced time period and cell number. The supy log just says '2020-12-22 19:24:54,578 - SuPy - INFO - All cache cleared.' 

I will attach my SUEWS prepare results. Would be great if you can at least check weather it works at your side or not.

[prepare_klein1.zip](https://github.com/UMEP-dev/UMEP/files/5731514/prepare_klein1.zip)

**Comment by flgebhardt** [comment]
Update:
I changed the directory of the input data and then it worked. So the error was probably caused by incompatible characters in the file directory. 

Thank you for the advice to use the SiteSelect file to manage the computation on my device. 

Unfortunately I get a lot of -999 values when I calculate Tair2m. I can't find any regularity in the errors when I check the morphometric file or the siteselect file,  like in #164 . But this would rather belong to a new issue.

**Comment by suegrimmond** [comment]
yes please raise this as a new issue as someone different will look a this. Make certain you provide all the appropriate files
