### ISSUE TITLE
integrate docs into this repo

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#208]
@biglimp shall we consider integrating the docs into this repo? so we have one place to guarantee the consistency between code and docs.

**Comment by biglimp** [comment]
I think it is a good idea. I see you have moved them already. What about SUEWS docs?

**Comment by sunt05** [comment]
SUEWS docs has already been merged with the code quite a while ago.

**Comment by biglimp** [comment]
Ok, good.

**Comment by sunt05** [comment]
just as a follow-up on this: we may need to restructure the files a bit to accommodate `docs`.
maybe moving all code into a folder, say `src` for "source code"?

**Comment by biglimp** [comment]
but i not UMEP-docs a separate repo? I think it is good to have it that way as I am moving between branches in UMEP.

**Comment by sunt05** [comment]
Switching between branches is OK with this approach; and it is actually making more sense to adopt this approach as we are having an almost totally new `processing` branch:
the key advantage of putting docs and together is the consistency between code and docs: we can write docs and code in  one place and (almost) at the same time, and some of the docstrings from python functions can be automatically retrieved to be docs pages.

So for each branch, the code-doc-integrated approach can allow code/version specific docs be generated automatically: we just need to tag the repo and RTD will generate a version specific doc site for us.

One example of this can be [SUEWS](https://suews.readthedocs.io/en/latest/):
![image](https://user-images.githubusercontent.com/1802656/103994459-f4406980-518e-11eb-9188-04eee671ae0a.png)

as you can see, we can even have a "develop" version, which I think is similar to the `processing` one in UMEP, something that is WIP but kind of give people a sense where we are going.

If you have more concerns, we can have a quick chat on this.

**Comment by biglimp** [comment]
processing and develop is not the same. The processing branch for UMEP is just moving the tools to the processing toolbox in QGIS. The docs is the same (identical) for the main branch and processing. That is why I dont want it integrate it but instead have it as a separate repo.

**Comment by sunt05** [comment]
great! then it sounds good to me.
