### ISSUE TITLE
SUEWS Prepare Error 

### ISSUE THREAD

**Issue by flgebhardt** [UMEP-dev/UMEP#209]
Hello, I did a SUEWS model run on a period of about two weeks with a 500m grid and a total cell number of 370. I managed to solve all issues I had in #207. Now I want to increase my resolution to a 250m grid with same extend and excactly the same input data. Now I get this error message when I run SUEWS prepare: 
 
 EXCEPTION IN C:/Users/flori/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
            
LINE 453 "#if np.isnan(IMP_zd) or IMP_zd            
 ERROR MESSAGE: '

I already delete the cells at the edge of the grid which got wrong values from the morphometric calculator. Furthermore, the cdsm doesn't represent excactly the distribution of trees/vegetation according to the landcover fraction file but I'm pretty shure that this doesn't cause the problem. As I said, it worked fine on the 500m grid and can't figure out what's the problem now with the new grid resolution. 

I attach the morphometric files, the grid and the land cover fractions. If you need the raster files I could upload them too later.

Would be great if you can check my files!

[1buildings_IMPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/5756951/1buildings_IMPGrid_isotropic.txt)
[2veg1_IMPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/5756952/2veg1_IMPGrid_isotropic.txt)
[landcover250_2.txt](https://github.com/UMEP-dev/UMEP/files/5756973/landcover250_2.txt)

[metdata_dwd_sundach_kurz_umep.txt](https://github.com/UMEP-dev/UMEP/files/5756978/metdata_dwd_sundach_kurz_umep.txt)

**Comment by flgebhardt** [comment]
[gitter250_pop.zip](https://github.com/UMEP-dev/UMEP/files/5757078/gitter250_pop.zip)

**Comment by biglimp** [comment]
I am not sure why, but you have negative landcover fractions at two locations in your landcover fraction file. That should not be possible... Change them to zero or a positive number (so that the sum adds up to 1. Then try again.

**Comment by flgebhardt** [comment]
Yes that caused the issue! Thank you so much! Land cover fractions were generated with some estimations for my simulation site and there was this mistake in my R code.

I still have another question: 
I have some cells where deciduous tree cover is 1, and SUEWS doesn't want to include the roughness calculations for these sites. ( ERROR MESSAGE: 0.0 cannot be raised to a negative power, #147 ). The vegetation morph file above is strongly reduced, which made it work. But now i figuered out that when I change land cover to 0.99 deciduous trees and 0.01 grass it works even with my complete files from the cdsm. Does it make any sense to you? Or is there maybe something wrong with my cdsm?

**Comment by biglimp** [comment]
When you say SUEWS you mean SUEWS Prepare? Please raise a new and separate issue with example data then we can have a look.
