### ISSUE TITLE
Forcing file format: ERA5 downloader vs. SUEWS prepare

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#214]
Hej Developers!

I would like to report an issue/bug with regards the formatting of the forcing file.  
When trying to run SUEWS prepare with the forcing file obtained via the Download data (or supy.util.gen_forcing_era5), I get the following Python error:

CRITICAL    EXCEPTION IN C:/Users/cga/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
             LINE 816 "np.savetxt(data_out, met_save, fmt=numformat, delimiter=' ', header=header, comments='')" 
             ERROR MESSAGE: fmt has wrong number of % formats: %3d %2d %3d %2d %6.2f %6.2f %6.2f %6.2f %6.2f %6.2f %6.2f %6.2f %6.2f %6.4f %6.2f %6.2f %6.2f %6.2f %6.4f %6.2f %6.2f %6.2f %6.2f %6.2f

SUEWS prepare works with an older forcing file of mine that I ran SOLWEIG with.

Best,
Csilla

**Comment by biglimp** [comment]
Can you please attach your forcing file.

**Comment by CsillaVG** [comment]
Sure! Here are my test sets.
Not working: [ERA5_UTC-47.5N-19.0E-281.7A_2013_data_60.txt](https://github.com/UMEP-dev/UMEP/files/5781203/ERA5_UTC-47.5N-19.0E-281.7A_2013_data_60.txt)
Old, working: [omsz.txt](https://github.com/UMEP-dev/UMEP/files/5781205/omsz.txt)

**Comment by biglimp** [comment]
@sunt05 , I see an additional column in the dataset downloaded from ERA5 (isec). What is this and when was this added in the supy.util.gen_forcing_era5 funkction? This results in error for SUEWS Prepare.

**Comment by sunt05** [comment]
Ah, this was a bug in an earlier version of SuPy, which has been fixed in the dev version of SuPy. I'll update the fixed version info later today to resolve this. 
Sorry folks!

**Comment by CsillaVG** [comment]
Also, to run Download data (ERA5) and supy.util.gen_forcing_era5, the toolz package was needed. Without it Download data (ERA5) was just hanging there for hours after downloading the data.

**Comment by sunt05** [comment]
supy has been updated just now; so just `pip install --upgrade supy` to get the fixed version.

> Also, to run Download data (ERA5) and supy.util.gen_forcing_era5, the toolz package was needed. Without it Download data (ERA5) was just hanging there for hours after downloading the data.

also, I'm not aware that `toolz` is needed by supy per se; if so, it should be dealt with by an upstream package that supy uses; so at the moment, I'm not including it as one of supy dependencies.

**Comment by CsillaVG** [comment]
Perfect. Thank you!
I am not aware if toolz is needed in supy either. In any case, it was a " ModuleNotFoundError: No module named 'tlz' " error that I received after running my one-line code with supy.util.gen_forcing_era5. :)
