### ISSUE TITLE
UMEP vegetation porosity

### ISSUE THREAD

**Issue by ghost** [UMEP-dev/UMEP#215]
I don't have data about the vegetation porosity for the UMEP-Input. I only have informations about the LAI, VegetationType, patch and vegetation on buildings. Is it possible to generate the Footprint anyway?

**Comment by biglimp** [comment]
Yes. Use default values if you dont have etter information. This is not a bug. I will close this. Please use email list for general questions.

**Comment by suegrimmond** [comment]
you can use literature values that vary with season (the most important part)
