### ISSUE TITLE
ERA5 forcing data and sun angles

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#219]
Hi Developers!

I am back again with a new set of issues. (:

(1) Multi-year forcing data from ERA5 downloader
The ERA5 downloader now works like a charm for a single year data. Thank you again! 
However, there seems to be a single line of data missing from the end of each year (Year+1 DOY=1 Hour=0). Because of it, SuPy throws and error.
Attached is the sample set generated for 2012-2014 with gen_forcing_era5.
[multiYearForcing.zip](https://github.com/UMEP-dev/UMEP/files/5826097/multiYearForcing.zip)

(2) ERA5 forcing data, a timezone issue(?)
I am getting a bit weird results with the ERA5 data. Since my modeled air temperatures (T2) are running 2 hours ahead of my reference data (from Hun met office, OMSZ), my guess would be that the ERA5 data is saved as UTC-1 instead of my UTC+1.
I did two test runs with SuPy: (1) with ERA5 forcing and (2) with modified epw forcing (where a section in the epw was replaced with my ref data, cosidering epw data convention). I am attaching the in- and output files from these runs zipped. Below are also the figures illustrating the in- and output T2 and Kdown values from SUEWS/SuPy as well as the reference data (OMSZ).
[R11a01-ERA5run.zip](https://github.com/UMEP-dev/UMEP/files/5826101/R11a01-ERA5run.zip)
[R11o01-EPWrun.zip](https://github.com/UMEP-dev/UMEP/files/5826104/R11o01-EPWrun.zip)
![dUW_0_ERA5 run](https://user-images.githubusercontent.com/53008258/104843598-cc0de480-58cb-11eb-872d-fea467334b24.png)
![dUW_0_modEPW run](https://user-images.githubusercontent.com/53008258/104843619-da5c0080-58cb-11eb-9680-6eca696f7970.png)

(3) Altitude and azimuth angles in SOLWEIG and SUEWS results
I am getting strange sun angles in both SOLWEIG and SUEWS results files. The location is Budapest (47.5N,19E), but the altitude/zenith angels indicate longer days in winter (~16h) than in the summer (~8h). See the above attached files for reference.

(4) epw conversion with the 'Prepare Existing Data' occasionally replaces the actual year with 1985. Attached is a reference data that it occurs with.
[epwConversion.zip](https://github.com/UMEP-dev/UMEP/files/5826109/epwConversion.zip)

(5) epw file header not updated
The header part of epw containing the geographical location, timezone, etc. is not updated, despite providing some of them in the gen_epw function. It is always the standard "LOCATION,Chongqing Shapingba,Chongqing,CHN,CSWD,575160,29.58,106.47,8,259.1 ..."
The 'gen_epw' generated epw files are in the zipped result folders attached above at (2).

(6) Wind speed data in ERA5-based forcing seems to be half the value.
In addition to gen_forcing_era5 derived ERA5 weather data, I've also obtained two datasets from Shiny Weather Data (lukas-rokka). CAMS is from the old website (https://rokka.shinyapps.io/shinyweatherdata_old/) and ERA5-ERA5 is from the newer one (https://rokka.shinyapps.io/shinyweatherdata/). Compared to those and to my field notes, wind speed data are SuPy-ERA5 are about half the value. Attached are epw files from Shiny Weather Data and a figure illustrating 2 weeks of data from September 2013.
[epwfiles.zip](https://github.com/UMEP-dev/UMEP/files/5826269/epwfiles.zip)
![forcing_ERA5-CAMS](https://user-images.githubusercontent.com/53008258/104846677-ff586f80-58db-11eb-8f5e-152a67e81032.png)

Thank you again for all your hard work!
Regards,
Csilla

**Comment by sunt05** [comment]
> Hi Developers!
> 
> I am back again with a new set of issues. (:

Welcome back 😄 

> 
> (1) Multi-year forcing data from ERA5 downloader
> The ERA5 downloader now works like a charm for a single year data. Thank you again!
> However, there seems to be a single line of data missing from the end of each year (Year+1 DOY=1 Hour=0). Because of it, SuPy throws and error.
> Attached is the sample set generated for 2012-2014 with gen_forcing_era5.
> [multiYearForcing.zip](https://github.com/UMEP-dev/UMEP/files/5826097/multiYearForcing.zip)

This is a known issue in a previous version of supy;
please update it to the latest version by the following command in your terminal:

```
pip install -U supy
```

> 
> (2) ERA5 forcing data, a timezone issue(?)
> I am getting a bit weird results with the ERA5 data. Since my modeled air temperatures (T2) are running 2 hours ahead of my reference data (from Hun met office, OMSZ), my guess would be that the ERA5 data is saved as UTC-1 instead of my UTC+1.
> I did two test runs with SuPy: (1) with ERA5 forcing and (2) with modified epw forcing (where a section in the epw was replaced with my ref data, cosidering epw data convention). I am attaching the in- and output files from these runs zipped. Below are also the figures illustrating the in- and output T2 and Kdown values from SUEWS/SuPy as well as the reference data (OMSZ).
> [R11a01-ERA5run.zip](https://github.com/UMEP-dev/UMEP/files/5826101/R11a01-ERA5run.zip)
> [R11o01-EPWrun.zip](https://github.com/UMEP-dev/UMEP/files/5826104/R11o01-EPWrun.zip)
> ![dUW_0_ERA5 run](https://user-images.githubusercontent.com/53008258/104843598-cc0de480-58cb-11eb-872d-fea467334b24.png)
> ![dUW_0_modEPW run](https://user-images.githubusercontent.com/53008258/104843619-da5c0080-58cb-11eb-9680-6eca696f7970.png)
> 

ERA5 data is stored in UTC and users need to convert them to proper timezones by themsevels.

**Comment by sunt05** [comment]
> (4) epw conversion with the 'Prepare Existing Data' occasionally replaces the actual year with 1985. Attached is a reference data that it occurs with.
> [epwConversion.zip](https://github.com/UMEP-dev/UMEP/files/5826109/epwConversion.zip)
> 

Thanks for reporting this. I'll see how a fix can be made.


> (5) epw file header not updated
> The header part of epw containing the geographical location, timezone, etc. is not updated, despite providing some of them in the gen_epw function. It is always the standard "LOCATION,Chongqing Shapingba,Chongqing,CHN,CSWD,575160,29.58,106.47,8,259.1 ..."
> The 'gen_epw' generated epw files are in the zipped result folders attached above at (2).

Please consider the EPW-related functionality as experimental and avoid using them in your "decent" research/work at the moment: please use with caution but feedbacks are more than welcome 🤝

**Comment by sunt05** [comment]
@CsillaVG please follow the EPW issues here: UMEP-dev/SUEWS#152

**Comment by CsillaVG** [comment]
Thank you for your quick response and explanations!
