### ISSUE TITLE
SOLWEIG not executing 

### ISSUE THREAD

**Issue by vsoubry** [UMEP-dev/UMEP#230]
Hello, i'm having problems with SOLWEIG.
Everytime i try to execute it, the progress bar starts a little bit and then stops like the tool just finished processing. When that happens there is no dialogue info appearing telling me something happened. In the directory for my output files there is only a single time file thats been created for one instance of time (the first one). I'm doing this with the same files i used 2 months ago but with a different area. I'm doing exactly the same step i did, but i think something changed with the new patches since then. 

Also, this might be related (or not), but when i start up QGIS i get a message everytime that i need to install UMEP, and when i click ok it tells me an error occured and that it failed to install, even though i used other tools in UMEP and it worked fine (screenshot linked). 
I use QGIS version 3.14, is it because i need to update QGIS? 

Help would be much appreciated since i need to finish my results for my thesis... 
Thank you.

![Error_SOLWEIG](https://user-images.githubusercontent.com/58615111/107076322-48079800-67b9-11eb-9c85-a5a1d84e7090.PNG)

**Comment by biglimp** [comment]
What OS are you using and what version of UMEP?
Is there no messages in the log related to this (speech bubble lower right)?

**Comment by vsoubry** [comment]
I am using UMEP version 3.15.5 on QGIS version 3.14. I work on a PC Windows 10, system version 18363.1316.
I get this message in the general Tab 

2021-02-08T11:07:22     CRITICAL    EXCEPTION IN C:/Users/vsoub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SOLWEIG\solweigworker.py, 
             LINE 286 "timeaddW, timeaddN, timestepdec, Tgmap1, Tgmap1E, Tgmap1S, Tgmap1W, Tgmap1N, CI, TgOut1, diffsh, ani)" 
             ERROR MESSAGE: Unable to allocate 6.32 MiB for an array with shape (2, 690, 600) and data type float64

In the Python Messages, i get a few messages (photo linked). 

Thank you again for your time.[
![PythonMessages](https://user-images.githubusercontent.com/58615111/107246619-6ad6be00-69fe-11eb-94c0-fbe45e4c8890.PNG)
](url)

**Comment by biglimp** [comment]
These are just warnings and will not break the process.
Can you attach your input data (spatial data + svf.zip + metfile). Also give me UTC.
If there is a SOLWEIG Runinfo textfile created. Please attach this also.

**Comment by vsoubry** [comment]
Here is the data linked in the google drive link. 
The UTC is -5. 
https://drive.google.com/file/d/1tI0RPAzt7VDvN7bbMg9aFeotLc6NtTqK/view?usp=sharing 

Thank you!

**Comment by biglimp** [comment]
You found a bug where Nodata values = 0 made the model crash. This is fixed in the latest development release 3.15.7

**Comment by vsoubry** [comment]
I have installed the latest version and it works for half of my data. However, the second half is for a zone thats a little larger ( the data provided above in this issue), and it still gives me the same general message : 

2021-02-10T16:52:22     CRITICAL    EXCEPTION IN C:/Users/vsoub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\SOLWEIG\solweigworker.py, 
             LINE 286 "timeaddW, timeaddN, timestepdec, Tgmap1, Tgmap1E, Tgmap1S, Tgmap1W, Tgmap1N, CI, TgOut1, diffsh, ani)" 
             ERROR MESSAGE: Unable to allocate 3.16 MiB for an array with shape (690, 600) and data type float64

It also displays the same python messages than the screenshot linked above.

I also get a little dialogue box when i execute SOLWEIG that says "It should take a few minutes", with the dialogue box specifying "Semi lage zone". Is there any link with my version of QGIS or the memory on my computer? 

Also for the first half of my data to work (smaller zone) i had to close QGIS each time i wanted to execute SOLWEIG or else it would display the same messages mentionned here.

Thank you very much for your support.
