### ISSUE TITLE
Follow-up to Issue 230

### ISSUE THREAD

**Issue by vsoubry** [UMEP-dev/UMEP#231]
This is a follow up to the issue number #230 

The new version 3.15.7 is working for half my data. However the other half is for a larger zone (data linked in the issue #230), and it still displays the same General message : 

2021-02-10T16:52:22     CRITICAL    EXCEPTION IN C:/Users/vsoub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\SOLWEIG\solweigworker.py, 
             LINE 286 "timeaddW, timeaddN, timestepdec, Tgmap1, Tgmap1E, Tgmap1S, Tgmap1W, Tgmap1N, CI, TgOut1, diffsh, ani)" 
             ERROR MESSAGE: Unable to allocate 3.16 MiB for an array with shape (690, 600) and data type float64

I also still have the same Python messages mentionned in the screeshot of issue #230. 
![PythonMessages](https://user-images.githubusercontent.com/58615111/107579942-dd44cb00-6bc3-11eb-8caf-5b56e8f969db.PNG)

Is it related to my QGIS version 3.14? or the memory on my computer?

Also i have to mention that to execute SOLWEIG i had to close QGIS in between each run or else the same messages mentionned here would pop up (if i did two runs in a row without closing). 

Thank you very much for your support.

**Comment by vsoubry** [comment]
I also have to mention that when executing SOLWEIG for my larger data a pop up message would appear telling me that it would take a few minutes with the dialogue box named "Semi Lage Zone". This pop up didnt appear for my smaller zone... might be correlated to why it doesnt work.

**Comment by biglimp** [comment]
I cannot replicate your error. It works fine on my W10 PC (Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz   2.40 GHz, 16Gb RAM, QGIS 3.16.3). You could try to use SOLWEIG via the Processing toolbox. It might be able to cope with higher memory stress.

**Comment by vsoubry** [comment]
I updated to QGIS 3.16.3 and i still get the same messages. What do you mean by using SOLWEIG via the Processing Toolbox?

**Comment by biglimp** [comment]
We have moved/copied a lot of the tools to the processing Toolbox in QGIS. Go to the webpage linked here to install it and also find info on how to use it. It is the same SOLWEIG model but it is now more integrated with the QGIS environment.

https://umep-docs.readthedocs.io/en/latest/UMEPforProcessing.html

**Comment by vsoubry** [comment]
Ok i found the problem, i had the 32 bit version... i updated it to the 64 bit version and it works now! Thanks again
