### ISSUE TITLE
Enhancement Request - Parked Vehicles

### ISSUE THREAD

**Issue by rarygit** [UMEP-dev/UMEP#232]
SOLWEIG land cover for paved surfaces excludes vehicles parked in carparks, which can be a significant contributor to land surface temperatures (see FLIR images below). Especially areas covering large carparks servicing shopping centres.

Usually I remove all vehicles from the LiDAR data prior to converting it to raster grids.

In these circumstances, as a feature request, is it possible to add parked vehicles as a component of the Ground land cover, with corresponding emissivity? At certain times of day, especially midday during the summer vacation, the carparks can be almost entirely filled with vehicles.

![FLIR0031_22Aug2019_1440](https://user-images.githubusercontent.com/16574504/107611510-6ef41d00-6c44-11eb-9908-cd8a95e06f68.jpg)
![FLIR0033_22Aug2019_1440](https://user-images.githubusercontent.com/16574504/107611511-6f8cb380-6c44-11eb-9af9-1712d1585608.jpg)

**Comment by biglimp** [comment]
Hi,
Would it be possible for you ta ask the same question in our new Discussion forum (https://github.com/UMEP-dev/UMEP/discussions). I think this might be interesting for more users and we also would like get people to use the forum.

**Comment by biglimp** [comment]
Actually, I see that I can convert this issue into a discussion item. I will do so. You dont need to do anything.
