### ISSUE TITLE
Problem with the 3.15.7 version

### ISSUE THREAD

**Issue by vsoubry** [UMEP-dev/UMEP#236]
Hello again. 
My issue is that when i try to execute SOLWEIG without any CDSM or TDSM i get a python mistake (screenshot). 
I used SOLWEIG before that with CDSM and TDSM without any problems, but i now need to make Tmrt maps without them. 

Thank you again.
![Pythonmistake](https://user-images.githubusercontent.com/58615111/107967199-d1b62300-6f7a-11eb-884b-f4f1de0cad19.PNG)

**Comment by biglimp** [comment]
Please try to replace solweig.py with the attached file and report back if this solves your issue (You need to change .txt to .py).

[solweig.txt](https://github.com/UMEP-dev/UMEP/files/5982757/solweig.txt)

**Comment by biglimp** [comment]
Now also available from last commit https://github.com/UMEP-dev/UMEP/commit/52a0f7ff9c1ac4cc92b48ee14013e8e0c1d9733d

**Comment by vsoubry** [comment]
Ok i tried with the new version it works. 
Now instead of opening a new Issue i'll juste write it here. 
I'm trying to use the Solweig Analyser, except that when i use the Exclude Building function, it doesn't substract the areas where there are buildings, it converts them to -9999, which is bad for my analysis. It used to work properly, but now with my new data it doesn't work anymore. I've linked the building grid i'm using here. 

Do you know what's the problem. 
Thank you again.

[buildings.zip](https://github.com/UMEP-dev/UMEP/files/5983669/buildings.zip)

**Comment by vsoubry** [comment]
I'm now working on the 3.15.5 version and it works on that version.

**Comment by biglimp** [comment]
This comes from resolving issue #218. Why dont you just set NoData to -9999 for your building layer? Or am I missing something?
