### ISSUE TITLE
Kjun et al. UMEP error:  local variable 'psi_f' referenced before assignment 

### ISSUE THREAD

**Issue by ghost** [UMEP-dev/UMEP#238]

**Comment by biglimp** [comment]
I think I need to forward this to Christoph who wrote the code. Could you please also attach the DSM and DEM.

**Comment by ghost** [comment]
The files are too big for this page, even as zip. 
I have used the example DSM and DEM (DataSmallAreaLondon) from the following page:

https://urban-meteorology-reading.github.io/

I will send this question also to Christoph. Thank you.

**Comment by biglimp** [comment]
Ok. Please let me know his answer so that we can fix any possible bugs in the code.

**Comment by biglimp** [comment]
@MonaScht , did you get hold of Christoph?

**Comment by ghost** [comment]
No, I found an other program that fits better. Thank you
