### ISSUE TITLE
supy  - linux issue

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP#241]
Is tried to resolve the old issue that supy is not working in QGIS on linux. I updated to Ubuntu 20.04 and QGIS 3.18. Now I got the following error trying to install supy within QGIS. Maybe this is a way forward @sunt05 ?

```
2021-03-05T10:22:12     WARNING    Traceback (most recent call last):
              File "/home/fredrik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/UMEP/suewsmodel/__init__.py", line 8, in 
              import supy as sp
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fredrik/.local/lib/python3.8/site-packages/supy/__init__.py", line 17, in 
              from ._supy_module import (
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fredrik/.local/lib/python3.8/site-packages/supy/_supy_module.py", line 28, in 
              from ._check import check_forcing, check_state
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fredrik/.local/lib/python3.8/site-packages/supy/_check.py", line 11, in 
              from ._load import dict_var_type_forcing
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fredrik/.local/lib/python3.8/site-packages/supy/_load.py", line 8, in 
              from supy_driver import suews_driver as sd
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fredrik/.local/lib/python3.8/site-packages/supy_driver/__init__.py", line 13, in 
              from supy_driver.suews_driver import (
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 798, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ImportError: numpy.core.multiarray failed to import
             
             During handling of the above exception, another exception occurred:
             
             RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
             
2021-03-05T10:22:24     WARNING    RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd 

```

**Comment by rarygit** [comment]
If this helps as a test installing supy on Ubuntu 20.04, QGIS 3.18

supy 2021.2.26  installed OK

Using a miniconda3 environment 
$ conda create -n qgis_18
$ conda activate qgis_10
(qgis_10) l1nux@l1nux-P370EM: $ conda install qgis numpy scipy matplotlib
(qgis_10) l1nux@l1nux-P370EM: $ pip install supy --upgrade
(qgis_10) l1nux@l1nux-P370EM: $ conda list

packages in environment at /media/l1nux/SAN240/conda_envs/envs/qgis_18:
Name                                                Version                                         Build                                     Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argparse                  1.4.0                    pypi_0    pypi
asteval                   0.9.23                   pypi_0    pypi
atmosp                    0.2.9                    pypi_0    pypi
boost-cpp                 1.74.0               hc6e9bd1_2    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h7979940_1007    conda-forge
cdsapi                    0.5.1                    pypi_0    pypi
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
click                     7.1.2                    pypi_0    pypi
coverage                  5.5              py39h3811e60_0    conda-forge
cryptography              3.4.4            py39h95dcef6_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dask                      2021.2.0                 pypi_0    pypi
dbus                      1.13.6               hfdff14a_1    conda-forge
dill                      0.3.3                    pypi_0    pypi
exiv2                     0.27.1               had08079_0    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
f90nml                    1.2                      pypi_0    pypi
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
future                    0.18.2           py39hf3d152e_3    conda-forge
gdal                      3.2.1            py39h409cc32_7    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.6.0                h2b14fbe_4    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.7               h9c3ff4c_1    conda-forge
glib-tools                2.66.7               h9c3ff4c_1    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
gst-plugins-base          1.18.3               h04508c2_0    conda-forge
gstreamer                 1.18.3               h3560a44_0    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
httplib2                  0.19.0             pyhd8ed1ab_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
kealib                    1.4.14               he4dc956_1    conda-forge
kiwisolver                1.3.1            py39h1a9c180_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_0    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               hd7c4107_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgdal                   3.2.1                h38ff51b_7    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.7               h3e27bee_1    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h02e6976_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_0    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.1                 hfd2b0eb_2    conda-forge
libprotobuf               3.15.5               h780b84a_0    conda-forge
librttopo                 1.1.0                h1185371_6    conda-forge
libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
libspatialite             5.0.1                he52d314_3    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
libzip                    1.7.3                h4de3113_0    conda-forge
linecache2                1.0.0                    pypi_0    pypi
lmfit                     1.0.2                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                1.1.1            py39h3811e60_3    conda-forge
matplotlib                3.3.4            py39hf3d152e_0    conda-forge
matplotlib-base           3.3.4            py39h2fa2bec_0    conda-forge
mock                      4.0.3            py39hf3d152e_1    conda-forge
multiprocess              0.70.11.1                pypi_0    pypi
mysql-common              8.0.23               ha770c72_1    conda-forge
mysql-libs                8.0.23               h935591d_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nose                      1.3.7                    pypi_0    pypi
nose2                     0.9.2                      py_0    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.62                 hb5efdd6_0    conda-forge
numdifftools              0.9.39                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.20.1           py39hdbf815f_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hf7af979_0    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
owslib                    0.23.0             pyhd8ed1ab_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.3                    pypi_0    pypi
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    8.1.1            py39hf95b381_0    conda-forge
pint                      0.16.1                   pypi_0    pypi
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platypus-opt              1.0.4                    pypi_0    pypi
plotly                    4.14.3             pyh44b312d_0    conda-forge
poppler                   0.89.0               h2de54a5_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 h6303168_2    conda-forge
proj                      7.2.0                h277dcde_2    conda-forge
psycopg2                  2.8.6            py39h3811e60_2    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pvlib                     0.8.1                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py39h50a64a9_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_7    conda-forge
pyqt-impl                 5.12.3           py39h0fcd23e_7    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_7    conda-forge
pyqtchart                 5.12             py39h0fcd23e_7    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_7    conda-forge
pyqtwebkit                5.212            py39h20c28b1_1    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.2           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
qca                       2.2.1                h73816c6_3    conda-forge
qgis                      3.18.0           py39hce95e4c_2    conda-forge
qjson                     0.9.0             h73816c6_1006    conda-forge
qscintilla2               2.11.2           py39hf01f197_4    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtkeychain                0.12.0               h2264404_0    conda-forge
qtlocation                5.12.9               he1b5a44_0    conda-forge
qtserialport              5.9.8                h73816c6_1    conda-forge
qtwebkit                  5.212                h8f65c2e_1    conda-forge
qwt                       6.1.6                h7ec6b3e_0    conda-forge
qwtpolar                  1.1.1                h73816c6_7    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scipy                     1.6.0            py39hee8e79c_0    conda-forge
seaborn                   0.11.1                   pypi_0    pypi
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
supy                      2021.2.26                pypi_0    pypi
supy-driver               2020b14                  pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tiledb                    2.2.4                hb9a9e87_1    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py39h3811e60_1    conda-forge
tqdm                      4.58.0                   pypi_0    pypi
traceback2                1.4.0                    pypi_0    pypi
tzcode                    2021a                h7f98852_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
uncertainties             2.4.4                    pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.17.0                   pypi_0    pypi
xerces-c                  3.2.3                h9d8b166_2    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.0                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by biglimp** [comment]
Thanks. Installing is not the issue but running a supy model run inside of QGIS, e.g. in the Python console:

```
import supy as sp
df_state_init, df_forcing = sp.load_SampleData()
grid = df_state_init.index[0]
# by default, two years of forcing data are included;
# to save running time for demonstration, we only use one year in this demo
df_forcing=df_forcing.loc['2012'].iloc[1:]
df_output, df_state_final = sp.run_supy(df_forcing, df_state_init)
```

**Comment by rarygit** [comment]
In the Python console, I ran the following code and had no error messages.
Obtained the first output, as below.

```
import matplotlib.pyplot as plt
import supy as sp
import pandas as pd
import numpy as np
from pathlib import Path


%matplotlib inline   #-- Use only if jupyter notebook
sp.show_version()   # -- Don't use; QGIS 3.16, 3.18 will crash

# For new users to SUEWS/SuPy:
# To ease the input file preparation, a helper function load_SampleData is provided to get the sample input for SuPy simulations
End of Comments

df_state_init, df_forcing = sp.load_SampleData()
grid = df_state_init.index[0]
df_forcing=df_forcing.loc['2012'].iloc[1:]

df_state_init.loc[:,['bldgh','evetreeh','dectreeh']]
```


output:
```
var     bldgh evetreeh dectreeh
ind_dim     0        0        0
grid                           
1        22.0     13.1     13.1`
```

**Comment by biglimp** [comment]
it is the run_supy function that is the issue... Just copy the code in my earlier comment for testing.

**Comment by sunt05** [comment]
I think this is an upstream numpy version issue: please use the latest numpy.

But I'll also add some updated dependency info for `supy_driver`, which may hopefully resolve this.

**Comment by sunt05** [comment]
@biglimp as a quick fix, can you try to update numpy used by QGIS and see if this is still an issue?

**Comment by biglimp** [comment]
updated numpy (1.20 something). Now I can execute a model run with supy in the QGIS console. Something has changed... Super!

**Comment by biglimp** [comment]
It also works via UMEP (SUEWSSimple). We should inform the users to update.
