### ISSUE TITLE
Error installing latest version of UMEP for processing

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#242]
Seeing the following when I update the UMEP for processing plugin:
![image](https://user-images.githubusercontent.com/57697604/110738370-43844280-8283-11eb-80fe-59f6acae2e8c.png)

However QGIS then tells me the update has been successful. Should I be concerned?

**Comment by biglimp** [comment]
I have seen this also and I am not sure what this is since it happens outside of our code. I seems that it has no effect on the umep plugin but if you notice some strange behaviour, please let us know. I will close this issue.
