### ISSUE TITLE
Casting failure while running 

### ISSUE THREAD

**Issue by FroehDo** [UMEP-dev/UMEP#244]
While running "Solar Energy on Building Envelopes" i get the following crash exception (immediatelly).

> 2021-03-12T09:22:07     CRITICAL    EXCEPTION IN C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python/plugins\UMEP\SEBE\sebeworker.py, 
             LINE 105 "wallmatrix = np.zeros((np.shape(wallrow)[0], int(wallsections)))" 
             ERROR MESSAGE: cannot convert float NaN to integer

I'm trying with a DSM of 30x30cm.

**Comment by biglimp** [comment]
What OS are you using (Windows, Mac etc.)?
What version of UMEP?
For quicker response, also attach your input files.

**Comment by FroehDo** [comment]
I'm on Win10 (64)
QGIS-Version is 3.10.13-A Coruña
UMEP Version is 3.16 (23rd Feb 2021)
I'll ask wether I'm allowed to share the DSM, for I don't own that...

**Comment by FroehDo** [comment]
My test files can be obtained at [https://geoportal.freiburg.de/files/rem/sample_20210318/testfiles.zip](https://geoportal.freiburg.de/files/rem/sample_20210318/testfiles.zip).

**Comment by biglimp** [comment]
Please also attach your meteorological file.

**Comment by FroehDo** [comment]
Ah, sure. Sry. Here you go: [https://geoportal.freiburg.de/files/rem/sample_20210318/meta_export.txt](https://geoportal.freiburg.de/files/rem/sample_20210318/meta_export.txt)

**Comment by biglimp** [comment]
This is very strange. The reason is that you somehow get strange values in the lowest row in your wall height raster. I cannot understand where they come from. I suggest that you reclass values larger than e.g.100 to 0 in your wall raster. Then it should work. I might look into fixing this later.

**Comment by biglimp** [comment]
Actually, my previous suggestion will not work. I have to try something else...
