### ISSUE TITLE
add version info

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#249]
version info should be embedded in the code/plugin for easier identification.

**Comment by biglimp** [comment]
Great. How can we go about this. If you point me the correct direction I can do it.

**Comment by sunt05** [comment]
I just add something simple here: https://github.com/UMEP-dev/UMEP/commit/7f29d648b96d29292676878a687be1ad2fa98fc2

So you can get your thoughts in.

Please let me know if more I can help with.
