### ISSUE TITLE
Problem with Lup in SOLWEIG 

### ISSUE THREAD

**Issue by ljin456** [UMEP-dev/UMEP#254]
Dear developers,

we would like to report an issue with the outgoing longwave radiation Lup in SOLWEIG. 

We performed two SOLWEIG simulations on a mostly cloud-free day with temporal resolutions of 1-minute and 10-minute, respectively. We observed unusual fluctuations during the sun-exposed hours in Lup. In the 1-min simulation, the value of Lup drops every 30 minutes (30 time steps) and in the 10-min simulation it drops every 7 time steps.

Here are the POI files and other input files we used.
[input4solweig.zip](https://github.com/UMEP-dev/UMEP/files/6170341/input4solweig.zip)

Thank you.

![0726_l_obs_1min](https://user-images.githubusercontent.com/58299975/111761266-0251eb00-88a0-11eb-98b5-e3002632f716.png)
![0726_l_dcep_10min](https://user-images.githubusercontent.com/58299975/111761275-04b44500-88a0-11eb-8d42-a0094c87e2ad.png)

**Comment by biglimp** [comment]
I found the issue for this and will update SOLWEIG in a near future.
