### ISSUE TITLE
SOLWEIG error TDSM filepath not defined

### ISSUE THREAD

**Issue by cdbell01** [UMEP-dev/UMEP#255]
**Describe the bug**
I'm encountering an error when running Solweig with a TDSM I've created myself. If I uncheck "Trunk zone DSM exist" and use the built-in TDSM generator in Solweig - Solweig runs great with the other inputs. The output seems correct. Note, I did not use the UMEP Tree Generator to create the TDSM, I used the raster calculator.

**To Reproduce**
1. Open the Solweig processor menu and fill in all inputs
2. Check "Trunk zone DSM exist"
3. Input a raster layer for the TDSM
4. Press run
5. See error log below

**Desktop (please complete the following information):**
 - OS: macOS
 - QGIS Version 3.16.4-Hanover
 - UMEP Version 3.16.1 (installed from the develop branch on 3/11/21)
 - SuPy Version unknown

**Error log**
Traceback (most recent call last):               File "/Users/colinbell/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP-SuPy-QGIS3/SOLWEIG/solweig.py", line 411, in start_progress               dataSet = gdal.Open(filePath_tdsm)              NameError: name 'filePath_tdsm' is not defined

**Comment by biglimp** [comment]
Fixed. I can also recommend to use SOLWEIG in UMEP for processing (https://plugins.qgis.org/plugins/processing_umep/)
