### ISSUE TITLE
Shadow generator gives false names to shadow files and overwrites itself.

### ISSUE THREAD

**Issue by shayeldad** [UMEP-dev/UMEP#256]
Hi,
I'm using latest version of UMEP, and in the newest versions (3.16 and 3.17), I have an error with shadow generator when creating a daily shadow pattern. I get the following message (for a full day calculation): 

_

> Traceback (most recent call last):
>               File "C:/Users/Shay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\ShadowGenerator\shadow_generator.py", line 428, in start_progress
>               dst, wallsh, wheight, waspect)
>               File "C:/Users/Shay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\ShadowGenerator\dailyshading.py", line 102, in dailyshading
>               time_vector = dt.datetime(year, month, day, time['hour'], time['min'], time['sec'])
>              ValueError: hour must be in 0..23

another issue which could maybe imply on the error, is when i create individual shadows. for instance, i create a shadow for 9:30 am and receive a correct results, but the file name is "Shadow_at_20201221_1030".

Thanks in advance, i appreciate your project.
Shay

![image](https://user-images.githubusercontent.com/51439953/111906120-b8ac0080-8a57-11eb-9565-ddaca227d273.png)

**Comment by biglimp** [comment]
Could you please try if you get the same error when using the ShadowGenerator from **UMEP for Processing** (available from the QGIS Plugin repository) and report back.

**Comment by shayeldad** [comment]
I do, same result.

**Comment by biglimp** [comment]
Thanks. I will try to identify the issue. Could you please attach your DSM for me to work with.

**Comment by shayeldad** [comment]
attached

**Comment by shayeldad** [comment]
[MUZA6.5FL.zip](https://github.com/UMEP-dev/UMEP/files/6180699/MUZA6.5FL.zip)

**Comment by biglimp** [comment]
Solved. Use development release 3.17.1 or 1.2.1 (processing). https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable
