### ISSUE TITLE
Umep installation error: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by AlexKDo** [UMEP-dev/UMEP#262]
Hello,

I am trying to install UMEP plugin in QGis and there is always an error- as seen in the pic below,

Appreciate any help provided!

![Untitled Project — QGIS 23_3_2021 8_01_14 μμ](https://user-images.githubusercontent.com/81244161/112195445-a4603300-8c12-11eb-87a9-665591a6fa25.png)

**Comment by biglimp** [comment]
This is a known issue where SuPy, a tool used in UMEP is using a different version of numpy than is shipped with QGIS. We will soon introduce a solution. In the meantime you can upgrade numpy yourself by following the instructions from https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities. The commands you should use (if you are a windows user) is:
`py3_env`
`pip install numpy —upgrade`

**Comment by sunt05** [comment]
This should have be fixed now with a recent update of `supy-driver` that explicitly specifies the minimum required `numpy` version.
But as user environments are diverse, let's keep this open for a while and see if similar issues would appear.

**Comment by AlexKDo** [comment]
It is indeed fixed! thank you. 
I also installed UMEP from zip file, because i had problem with Post-processing and it all works until now. 

Should i close this issue?

**Comment by sunt05** [comment]
@AlexKDo thanks for your feedback!
and yes, please close the issue.
