### ISSUE TITLE
Lines in mean radiant temperature images

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#264]
When generating mean radiant temperature maps, lines are appearing. 
The code used to generate the images can be found here: 
https://github.com/bweeding/phd/blob/main/las_fusion_processing_draft3_uni.py

![image](https://user-images.githubusercontent.com/57697604/112562839-5292f500-8e2c-11eb-9a2a-2ae66843ef39.png)

**Comment by biglimp** [comment]
This is not a UMEP issue. I am moving this over to Discussions where we can continue this.
