### ISSUE TITLE
conflict in numpy versions 

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP#271]
We still have a conflict version issue which I think relate to Supy. Is is possible to update numpy automatically when installing SuPy?

Would be prefereble if users were not forced to upgrade numpy manually.

**Desktop (please complete the following information):**
 - OS: 'Windows 10
 - QGIS Version 3.18
 - UMEP Version 3.17
 - SuPy Version 2021.3.30

![image](https://user-images.githubusercontent.com/11908356/113673907-d74a0280-96b9-11eb-812f-4558d065f835.png)

![image](https://user-images.githubusercontent.com/11908356/113674041-02345680-96ba-11eb-99ae-62d999fa8648.png)

**Comment by sunt05** [comment]
This should not happen if users upgrade their installed supy as all required dependencies would be installed/upgraded as well.
So I couldn't think of a good way to resolve this at the moment.

And the supy here is installed for the first time or upgraded from a previous version?
if the latter, did you notice that `numpy` is updated along the way as well?

**Comment by biglimp** [comment]
SuPy is already on the computer and when QGIS is reinstalled numpy is not upgraded. 

Is this still the location where I can see what modules that are installed/upgraded when Supy is installed? According to this, numpy is not included. https://github.com/sunt05/SuPy/blob/d48f58d8f35e852acd4e205ca4b0a3c9adcdebf2/src/setup.py#L40-L58

**Comment by sunt05** [comment]
> SuPy is already on the computer and when QGIS is reinstalled numpy is not upgraded.

So I guess the re-installation of QGIS somehow overrode the numpy required by supy.

> 
> Is this still the location where I can see what modules that are installed/upgraded when Supy is installed? According to this, numpy is not included. https://github.com/sunt05/SuPy/blob/d48f58d8f35e852acd4e205ca4b0a3c9adcdebf2/src/setup.py#L40-L58

(almost) yes, but this is the latest version (you were looking at the archived one):
https://github.com/UMEP-dev/SuPy/blob/master/src/setup.py

And the dependency on `numpy` is not specified here but in the `supy-driver` module.


in this case, you may `pip uninstall supy supy-driver` and reinstall them to resolve this issue: required `numpy` will be installed automatically.

**Comment by biglimp** [comment]
Ok, thanks. I other words, we cannot avoid users NOT to be forced to use pip... Hopefully this is not a common issue.

Where can I find the modules installed with the supy-driver?

**Comment by sunt05** [comment]
> Where can I find the modules installed with the supy-driver?

Only numpy is required by SuPy-driver: no other dependencies.

**Comment by biglimp** [comment]
@sunt05, I uninstalled QGIS and UMEP as well as removing Supy and supy-driver from my system. Then I installed QGIS and installed UMEP from the QGIS repository. Still the same issue where numpy 1.19.1 is not upgraded to 1.20.x used by the supy-driver giving the error below. In other words, installing sypy-driver does not upgrade numpy version on W10. It seems that `pip install numpy --upgrade` is our only option at the moment?

![image](https://user-images.githubusercontent.com/11908356/122068285-90ccfe80-cdf4-11eb-8d22-e8f6d85641ed.png)

**Comment by sunt05** [comment]
It's a pity that this issue persists... 
did you restart your QGIS after running the supy installer in UMEP?
or, I think there are some leftover in your QGIS-python folder that confused python to pick up an older version of numpy, which could occasionally happen.
I guess you were running that situation.

Let me think about this... very very tricky...

**Comment by biglimp** [comment]
Yes, even restarted whole system. Still same error. 

I am thinking of two workarounds:
1. Make the user install specific supy version where numpy 1.19 is used. Probably not a doable option
2. Give users instructions how to upgrade numpy using pip if 1.19 is installed on their system

Nevertheless, we need to do something cos now you get a python error every time you start QGIS. Not nice.

**Comment by sunt05** [comment]
> It seems that `pip install numpy --upgrade` is our only option at the moment?

So after you manually did this, things would work? That's very weird as our code should do the same thing. I'm wondering there's something else happening at your side. 

I tried a new installation of QGIS 3.19 at my side on Mac and found a different issue with the same symptom. 

So which QGIS are you using?

**Comment by biglimp** [comment]
QGIS: 3.18.3
Yes, it works now. Actually, I needed to close QGIS in order to update numpy. I got this error running `pip install numpy --upgrade` when QGIS was open indicating that f2py is blocking the update somehow...

```
C:\Users\xlinfr\Documents\PythonScripts\UMEP>pip install numpy --upgrade
Collecting numpy
  Downloading numpy-1.20.3-cp37-cp37m-win_amd64.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB 6.8 MB/s
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.1
    Uninstalling numpy-1.19.1:
      Successfully uninstalled numpy-1.19.1
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\osgeo4~1\\apps\\python37\\lib\\site-packages\\~umpy\\.libs\\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.
```

**Comment by biglimp** [comment]
I am thinking of something like this:
```
import numpy as np
if np.__version__ < '1.19':
    tell user to upgrade
```

what do you think?

**Comment by sunt05** [comment]
My concern is if a user can successfully do this as our code is supposed to do the same thing for users. 
I guess something else was breaking the update. 
Let me try it again here and update you later.

**Comment by sunt05** [comment]
I think I identified the issue: the `pip` shipped with this QGIS-python couldn't address the dependency property.
I'll improve the automatic installation code to resolve this: give me a second.

**Comment by sunt05** [comment]
added a tentative fix for this: https://github.com/UMEP-dev/UMEP/commit/9d6d2b879d17b494a1ad87e24fb175ba0a42d4c2
