### ISSUE TITLE
spatial data downloader is not working

### ISSUE THREAD

**Issue by debasmita260** [UMEP-dev/UMEP#272]
**Describe the bug**

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - QGIS Version [e.g. 3.18]
 - UMEP Version [e.g. 3.16.2]
 - SuPy Version [e.g. 2021.1.23]

**Screenshots**

**Data**
If applicable, add data files to help us reproduce your problem.

**Additional context**

**Comment by suegrimmond** [comment]
please provide error information

**Comment by debasmita260** [comment]
![image](https://user-images.githubusercontent.com/82051633/113813735-147fc480-978e-11eb-9a46-c2e0507cb863.png)

**Comment by debasmita260** [comment]
![image](https://user-images.githubusercontent.com/82051633/113813772-295c5800-978e-11eb-8639-5436b1566316.png)
