### ISSUE TITLE
SUEWS Prepare Error 

### ISSUE THREAD

**Issue by gusbacos** [UMEP-dev/UMEP#277]
**Describe the bug**

I get following message when trying to Generate using SUEWS Prepare: 

> Operations cancelled, process unsuccessful! See the General tab in Log Meassages Panel (speech bubble, lower right) for more information

I get following error code in Log Messages 

> 2021-04-15T17:09:30     INFO    Setting up tab: Paved
> 2021-04-15T17:09:30     INFO    Setting up tab: Building
> 2021-04-15T17:09:30     INFO    Setting up tab: Evergreen
> 2021-04-15T17:09:30     INFO    Setting up tab: Decidious
> 2021-04-15T17:09:30     INFO    Setting up tab: Grass
> 2021-04-15T17:09:30     INFO    Setting up tab: Bare Soil
> 2021-04-15T17:09:30     INFO    Setting up tab: Water
> 2021-04-15T17:09:30     INFO    Setting up tab: Conductance
> 2021-04-15T17:09:30     INFO    Setting up tab: Snow
> 2021-04-15T17:09:30     INFO    Setting up tab: Snow clearing
> 2021-04-15T17:09:30     INFO    Setting up tab: Anthropogenic
> 2021-04-15T17:09:30     INFO    Setting up tab: Irrigation
> 2021-04-15T17:09:30     INFO    Setting up tab: Water Use (Manual)
> 2021-04-15T17:09:30     INFO    Setting up tab: Water Use (Automatic)
> 2021-04-15T17:09:30     INFO    Setting up tab: ESTM Coefficients
> 2021-04-15T17:10:20     CRITICAL    EXCEPTION IN C:/Users/xbacos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\SUEWSPrepare\prepare_worker.py, 
>              LINE 103 "print('Processing ID: ' + str(feat_id))" 
>              ERROR MESSAGE: I/O operation on closed file.
> 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - QGIS Version 3.18.1
 - UMEP Version e.g. 3.16.1
 - SuPy Version e.g. 2021.1.12

**Data**
[Okv.zip](https://github.com/UMEP-dev/UMEP/files/6319084/Okv.zip)
See attached data, but i also tried Using the data provided in the SUEWS Prepare Tutorial (https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html?highlight=prepare)  with the same result

**Comment by biglimp** [comment]
@gusbacos , shall we close this as this was fixed after updating to latest versions?

**Comment by gusbacos** [comment]
Yes, lets do that.

**Comment by C-H-Simpson** [comment]
I'm getting this same error

OS: Windows 10
QGIS: 3.20.1
UMEP: 3.17.3
SuPy version: 2021.7.22
Python version 3.9.5

**Comment by C-H-Simpson** [comment]
In case anyone else has this problem: Commenting out line 103 of UMEP/SUEWSPrepare/prepare_worker.py was enough to make it run for me.
