### ISSUE TITLE
Error when using SOLWEIG with trunk zone grid

### ISSUE THREAD

**Issue by j0lsson** [UMEP-dev/UMEP#279]
Hi! 

When I try to use SOLWEIG with a tdsm layer a get a python error. It works fine if I exclude the tdsm. See attached image for the error and .zip for the data. 

![Python_error](https://user-images.githubusercontent.com/77452966/119228751-b546fb00-bb14-11eb-8f3d-1a136f0cd488.JPG)
[SOLWEIG_input_data.zip](https://github.com/UMEP-dev/UMEP/files/6526517/SOLWEIG_input_data.zip)

Best regards, 
J

**Comment by biglimp** [comment]
What version of UMEP are you using?

**Comment by j0lsson** [comment]
3.17, and QGIS 3.18.2

**Comment by biglimp** [comment]
This has been fixed since UMEP 3.17.1. We have not uploaded this to the QGIS repo just jet so please use the development release from this Github. Consult our Manual on how to install.

**Comment by j0lsson** [comment]
Works fine now, thanks!
