### ISSUE TITLE
Daily Shadow Pattern not responding?

### ISSUE THREAD

**Issue by AnneSawa** [UMEP-dev/UMEP#284]
Hi, 

I have a dsm raster that I would like to calculate the Daily Shadow Pattern for. When I click run, the 
When I try to use the Daily Shadow Pattern tool, QGIS stops responding. It uses almost all of my working memory and I am not sure how to fix it. 

I am using QGIS 3.10.14.

**Comment by biglimp** [comment]
I suspect that this is not an issue so I will move this over too discussions as others could benefit from our discussion.

Three things:
1. What version of UMEP and what operating system are you using?
2. How large is your DSM (rows and columns)? It sounds that you are using a too big raster for your computer memory
3. Try using **UMEP for processing** where the shadow tool also is available. Here, QGIS automatically make use of a so called ”thread” which hi ders your computer to freeze.

Let me know your progress.
/Fredrik
