### ISSUE TITLE
Missing figure in the Urban Energy Balance - SUEWS and WUDAPT tutorial

### ISSUE THREAD

**Issue by MartinaFrid** [UMEP-dev/UMEP#313]
Fig. 48 - 'Settings for the LCZ converter plugin' is not shown in the 'Urban Energy Balance - SUEWS and WUDAPT' tutorial.

![image](https://user-images.githubusercontent.com/85220147/129471220-306fb067-2960-4fc0-a15e-0fef58a2a9be.png)

**Comment by biglimp** [comment]
That image didnt add any needed info so it has been removed.
