### ISSUE TITLE
pre processor - wall height and aspect

### ISSUE THREAD

**Issue by HibaHamdi09** [UMEP-dev/UMEP#324]
the button "run" in the wall height and aspect generator doesn't work. I put the DSM (downloaded from the test dataset https://urban-meteorology-reading.github.io/) but it doesn't work.

**Comment by biglimp** [comment]
I just tried the tool with the Gothenburg DSM and it worked fine. Can you please be more specific. Which one of the DSMs are you using? What version of UMEP and QGIS? What operation system are you using?

**Comment by HibaHamdi09** [comment]
thank you for your reactivity and i am sorry, my request was not clear.
- i work with DSM_KRbig (Goteborg)
- Qgis 3.16
- UMEP 3.18

**Comment by biglimp** [comment]
What is your error message?

**Comment by HibaHamdi09** [comment]
there is no error message, i can't press the button "Run". The button is grey.

**Comment by biglimp** [comment]
HAve you added a path to the output files? When this is done, the run-button becomes active.

**Comment by HibaHamdi09** [comment]
OK. Thank you. It works now. I put the directory at first but i think i made a mistake in the directory, that's why it didn't work. 
Thank you so much!
