### ISSUE TITLE
Tree Generator

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#33]
**[Original report](https://bitbucket.org/fredrik_ucg/umep/issue/33) by Andrew Speak (Bitbucket: [andyspeak33](https://bitbucket.org/andyspeak33), ).**

The original report had attachments: t1.jpg, t2.jpg, t3.jpg, Bolzanoshapefiles.zip, bolzano shapefiles.7z, vittoriashapefiles.7z

----------------------------------------

I am going through the steps to create a TDSM and CDSM.  I have a pointfile containing all the necessary information (I have rounded the heights etc to the nearest meter because I thought this may have been causing the problem before).  I have the DSM and DEM in the same resolution and extent.

The tool runs for a few seconds then produces the tiffs but when I load them they are all black and their values are NAN to 0.

Any idea what I am doing wrong?

**Comment by vsoubry** [comment]
Hello, i am having the exact same problem as you and it doesnt seem clear what corrected the problem. What did you do to make it work? It would mean the world to me if you answered i'm sort of stuck in my masters thesis because of this step. 
Thank you.

**Comment by sunt05** [comment]
Hi @vsoubry, are you using the latest UMEP version? can you report the versions of your QGIS and UMEP?
Since I'm not the developer of this plugin, @biglimp may be more helpful?

**Comment by biglimp** [comment]
As this issue is dealt with else where I am closing this again.
