### ISSUE TITLE
problem with SUEWS prepare

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/UMEP#336]
**Describe the bug**
i try to open SUEWS prepare from UMEP plugin at QGIS and i get the following message

i tried for these versions of QGIS 

3.16.8
3.18.1
3.20.3

UMEP v 3.18

**Screenshots**
![image](https://user-images.githubusercontent.com/61833032/140503193-3f79006d-6c56-445b-8d4f-6044d9e48ee6.png)

**Comment by biglimp** [comment]
I think we solved this in the new version but this is only in the development release e.g. not in QGIS repository. Try install as decribed in https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable, or wait until we create a new version for the QGIS repo.
