### ISSUE TITLE
UMEP installation error in QGIS 2.18

### ISSUE THREAD

**Issue by shovals123** [UMEP-dev/UMEP#347]
**Describe the bug**
I am trying to open the UMEP plug-in in Qgis 2.18. When I try to install it in the Plugin Manager, I receive the following alert:
"This plugin is broken
cannot import name NUMPY_MKL"

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - QGIS Version 2.18.28
 - UMEP Version - from 2.18 Plugin Library
 - SuPy Version - uncertain.

**Screenshots**
![image](https://user-images.githubusercontent.com/96479679/147085216-adbe4b0d-0249-4a4f-936c-cfe5f412456d.png)

Thank you in advance.

**Comment by biglimp** [comment]
UMEP 3.x is only available in QGIS 3.x. To make UMEP work you need the install an old version of UMEP (2.x).

**Comment by biglimp** [comment]
You can easily install zipped versions from our github using the "Install fron Zip" in QGIS (Plugins>Manage and Install Plugins).

**Comment by shovals123** [comment]
Hi,

I ama aware of that function in later versions of the QGIS but it isn’t available in QGIS 2.

Thanks once again.
