### ISSUE TITLE
ERROR WHILE TRYING TO RUN LCZ CONVERTER

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/UMEP#356]
Hello,

Please I have the following error while trying to run the LCZ converter, The programme did not run but instead gave the error below. Kindly help ....

An error has occurred while executing Python code: 

KeyError: '-1' 
Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\LCZ_Converter\LCZ_converter.py", line 669, in start_progress
    typetest = fields.at(idx).type()
KeyError: '-1'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare/Modules
C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\Users\User\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\User\AppData\Local\gis4wrf\python39
C:\Users\User\AppData\Local\gis4wrf\python39\lib\site-packages
C:/Users/User

**Comment by biglimp** [comment]
1. What version of UMEP are you using?
2. What data are you using? If you are using your own produced data, please try the converter using the date in this tutorial: https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsWUDAPT.html#suewswudapt
3. Based on the error message, you are having an issue with the attribute field in your polygon grid. Make sure you use an attribute field with unique interger numbers.

**Comment by biglimp** [comment]
@phemiobe , is this issue still active or can I close?
