### ISSUE TITLE
Perez_v3 output issue (SOLWEIG)

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#365]
I'm getting incorrect outputs from Perez_v3, which have showed up in kdown and Tmrt. I’m supplying my own diff and dir radiation (from the Australian Bureau of Meteorology’s BARRA reanalysis product). I’ve traced the errors all the way back to the Perez_v3 function in Solweig_2021a_calc:
 
lv = Perez_v3(zenDeg, azimuth, radD, radI, jday, patchchoice)   # Relative luminance
 
The inputs for Perez_v3 that produce the bad results are:
 
zendeg: 85.7476675536682
azimuth: 67.36351431750992
radD: 73.1
radI: 100.1
jday: 229.0
patchchoice: 1
 
This produces an output with the 3rd column hundreds of times larger than for the other normal outputs:
 
![image](https://user-images.githubusercontent.com/57697604/152504791-969e204d-82a1-4d9b-a1f2-86450247c04c.png)

 
Which then goes into the anisotropic luminosity:
 
aniLum = aniLum + diffsh[:,:,idx] * lv[0][idx][2]
 
dRad = aniLum * radD
 
Causing dRad to have extremely large values:
 
max: 3176.9642980328917
min: -2196.1060734137354
med: 1078.274174716783
 
compared to a normal dRad:
max: 101.12
min: 0.15784201699530884
med: 50.55301209344854
 
Which is then fed into kdown. This results into large kdown and Tmrt values. I also traced an occurrence of low Tmrt and kdown values, and found that the same thing happened, though at 2pm in the afternoon!
 
zendeg: 22.940787488281416
azimuth: 355.04264645985876
radD: 110.58
radI: 87.59
jday: 21.0
patchchoice: 1
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
[ 6.         36.          9.76427633]
 
In both of these cases, extreme kdown led to extreme Tmrt.

**Comment by biglimp** [comment]
Thanks Ben. We should try to identify when this happens. It would be good if you can try to identify a pattern, e.g. when radI and radD is very similar or at high zenith angles etc. I would be good to also know radG at these occasions, as well as times of day.

Can you also proved an inputexample when this happens, e.g. all info needed (metfile, location etc.)

**Comment by bweeding** [comment]
I'll have a go at some deeper analysis first thing on Monday!

**Comment by nilswallenberg** [comment]
Hi Ben,

Do you know if your input radI is for a horizontal surface or perpendicular to sun's beam? It should be perpendicular to the sun's beam. If the input is on a horizontal surface it is easy to change it to perpendicular with one line of code. 

radI[i] = radI[i]/np.sin(altitude[0][i] * np.pi/180)

This line should be then be added to the solweig_algorithm.py just before so.Solweig_2021a_calc (approximately line 900 for UMEP processing and 300 for UMEP).

Cheers,
Nils

**Comment by bweeding** [comment]
Hi Nils, in addressing the issue I think I found another one at my end which I have solved. I'll deal with that first.

I realised that because I'm using hourly mean data, I should be using timestamps on the half hour, so that I get an average sun position from the model as well. Therefore my data which is the average from 1300 to 1400 is stamped 1330 instead of 1300. You can see in the figure below that moving from stamping data on the hour compared to on the half hour improves things significantly:
![image](https://user-images.githubusercontent.com/57697604/152909820-772f8dba-f0a7-4273-99ff-33eb71f7c35f.png)

I then tested out the modified radiation formula, as I'm fairly sure my radiation data is normal to the ground, as it comes from a surface level parameter in Wm^-2:
![image](https://user-images.githubusercontent.com/57697604/152911001-2e673eaa-c7e3-4aa1-b05e-889c78c71174.png)

As you can see, the addition of the radiation formula introduces a range of strange results.

I'm going to run the same tests with some longer times periods and will send through the results when they're done.

Cheers
Ben

**Comment by bweeding** [comment]
### Investigation of strange results

I've produced two runs of a 50m by 50m tile from 2016 through 2018 using hourly mean reanalysis data.

![image](https://user-images.githubusercontent.com/57697604/153359092-d5d64962-8703-4b83-8996-48c9cf2b21b9.png)
As you can see, the seasonality in Tmrt is well represented, although there are two timestamps with extremely low average Tmrts that are clearly errors. Adding in the radiation modification as suggested by Nils reduces some of the extreme values, and adds an interesting peak in high but reasonable Tmrt values.

We can then look and the maximum and minimums for each run:
![image](https://user-images.githubusercontent.com/57697604/153361293-cb2fc4d2-ffa3-4659-9416-4d06dc453c9b.png)
While the minimums both appear sensible, the maximum values on the modified radiation run are quite strange, peaking in winter. The radiation modified run also contains far more extreme value spikes. Given this, I've focused the rest of this analysis on the default setting.

The next plot shows azimuth, altitude, radD, and radI plotted with Tmrt:
![image](https://user-images.githubusercontent.com/57697604/153369500-a803dc21-4072-4cf5-abab-1249746aaded.png)
This shows the extreme errors occurring at lower radiation values and sun altitudes, and wider azimuths. To clarify the times of year these errors occur at we can use a 2D histogram of Tmrt and day of year:
![image](https://user-images.githubusercontent.com/57697604/153370800-e0b79fa8-1a6e-4cb5-9c22-4548bfedea5c.png)
We have non during Summer, but some occurring in all other seasons.

To check if a relationship appears with the ratio of altitude to azimuth and Tmrt:
![image](https://user-images.githubusercontent.com/57697604/153372292-8f7ebaba-94ba-4e0e-b430-c38c80a5c96e.png)
This shows extreme values only occur when the ratio is small and positive.

Doing the same with Rad I and Rad D:
![image](https://user-images.githubusercontent.com/57697604/153372565-2cad60ef-de63-4c6e-80ff-c07086b16a7f.png)
This shows the extreme values occur when Rad D is relatively large, in the context of both radiation values being small.

I haven't continued any deeper down the rabbit hole, as I'd like to hear if you have any guiding comments or ideas before I go any further?

Cheers
Ben

**Comment by nilswallenberg** [comment]
There are a few things you could do or check:

1. Compare global radiation with I0 to check if you are off in time (does the reanalysis correct for daylight saving, etc, and how it is treated in your SOLWEIG run?). If you compare global radiation and I0 on a clear day (one in winter and one in summer) they should more or less match.

2. The example from 2PM on January 21st:
zendeg: 22.940787488281416
azimuth: 355.04264645985876
radD: 110.58
radI: 87.59
jday: 21.0

Is it realistic to have only ~200 radG at this specific time? If it is overcast, radD should probably be higher if radI is 87. If it was fully overcast, radI should be zero. Could be something wrong with the input data here.

3. Another possible explanation is that the Perez model is not able to solve for some specific inputs. It is after all an empirical model.

4. Also found this (nr 8 in the following pdf):
http://www.bom.gov.au/research/projects/reanalysis/Known_issues_in_BARRA_dataset_July_2019.pdf
Maybe it helps, not sure which one of the BARRA products it relates to. 

5. There are quite few errors, which you could filter out. :-)

Hope we can solve this! :-)

Cheers,
Nils

**Comment by bweeding** [comment]
Hi Nils, I'm sure we can solve it! 

I checked the I0 and global and there was indeed a mismatch occurring during winter! 
![image](https://user-images.githubusercontent.com/57697604/153528566-32254499-bc6b-4ae5-b2c2-ca71f46bbe2f.png)
This was due to me using a local time conversion which included daylight savings. I fixed this by using a set offset of 11 hours:
![image](https://user-images.githubusercontent.com/57697604/153528728-ee9cd02c-348c-42fc-a4ed-65371a2c5c3a.png)

I then ran the 2016 through 2018 period again:
![image](https://user-images.githubusercontent.com/57697604/153532329-0d8098da-813f-4989-95f2-400e4331d932.png)
![image](https://user-images.githubusercontent.com/57697604/153532799-2b8371da-b2fb-4eb4-b802-d5af30f342d6.png)
I only received one warning message during processing:
![image](https://user-images.githubusercontent.com/57697604/153528905-9f20bbaa-fa30-4763-afe7-8746a1080dfc.png)
![image](https://user-images.githubusercontent.com/57697604/153533273-27e5cc51-54cd-487f-8705-53ccc9831170.png)
![image](https://user-images.githubusercontent.com/57697604/153533359-f52ea69d-5379-4abd-a21c-60bf2601ddf6.png)
![image](https://user-images.githubusercontent.com/57697604/153533631-0a234360-584a-4722-b213-cd1030ecc8ef.png)

We now only have two timestamps with erroneous values, shown in the top two panels, with the following hour below them:
![image](https://user-images.githubusercontent.com/57697604/153534878-75308cc1-3b57-4109-8512-15fb4dc4c2e7.png)
The large white shape is a building where I've eliminated the Tmrt, while the speckled white areas must be NaNs produced by the Tmrt algorithm I'm assuming?

Given the uncertainty in the BARRA radiation and the empirical nature of the formula, 2 bad hours in 3 years of data seems pretty good! I'm going to now run the full 30 year time series over the weekend and will then produce plots on Monday.

Cheers
Ben

**Comment by biglimp** [comment]
Great Ben! Looks like you sorted out almost all strange values. Is the last maps is from a time step where you have strange data? If everything is ok, no NaNs should be present.

**Comment by bweeding** [comment]
Thanks! The last maps are normal timestamps, but when I calculate UTCI using xarrays, I also set the Tmrt values of all the building locations to NaN so I'm only dealing with pedestrian accessible data for analysis.

**Comment by bweeding** [comment]
Hi Fredrik and Nils, after sorting out the time alignment issue, the data has cleared up significantly. However, there are still some "bad" timestamps. I've pulled out images of timestamps with Tmrt less than -20 and plotted them here. I'm going to do a bit more digging, but just wondering if there are any patterns or issues you recognise? 

Cheers
Ben

![bad tmrt timestamps](https://user-images.githubusercontent.com/57697604/156268715-97fbd2c7-1561-458d-9017-372a5b356acb.png)

**Comment by biglimp** [comment]
Hm. I see some linear features in your output (about 526900). What are these and could they affect the output?

**Comment by bweeding** [comment]
I believe these are artifacts from the combining of the tiles. The whole 150m x 150m image is made from nine 50m x 50m tiles. Each of the 50m x 50m tiles is processes as the centre of its own 150m x 150m tile to account for tall building shadows. The linear features only seem to appear at low sun angles (dusk/dawn), so I think they must be from differences in the buildings that are used to calculate shadows. Does that make sense?

**Comment by biglimp** [comment]
Me theory is that at certain, very specific times during dawn and/or dusk, the calculation of sun angle and the observed Kdown does not match and somehow creates these strange Tmrt values. That could be if e.g. have positive sun angle but still no positive Kdown or something like that. Could you take one of the strange time steps and see what the full uotput looks like by putting in a POI somewhere in the sunlit part of the model. Then we could see from which flux the large negative values come from (Kdown, Kup, Kside, Ldown, Lup or Lside).

**Comment by bweeding** [comment]
Ah ok makes sense, I'll do it first thing Monday. I can produce maps of all
the outputs using the xarray modification I've made.

**Comment by biglimp** [comment]
It would also be good to get the sun angles etc. for that time step. Hence the POI.

**Comment by bweeding** [comment]
Ah yep no worries, I'll put it all together. Have a good weekend!

**Comment by bweeding** [comment]
Here's a POI from the model - it's at 526995, 5252145.

There's a negative value for kdown - could that be it?

[POI_1_for_FL.txt](https://github.com/UMEP-dev/UMEP/files/8194310/POI_1_for_FL.txt)
l

**Comment by biglimp** [comment]
Well, that is just a consequence of something. I see that you are using the wrong Kdir. It should be direct beam perpedicular to the solar position. Now you are using Kdir for a horisontal surface. I see this since Kdir+Kdiff = Kglobal. This could also be the reason why you get negative Kdown.

Kdir, Kdiff and Kdown are input parameters whereas the other K-components are model outputs.

Recalculate Kdir `direct-beam radiation = (global−diffuse) / sin(sun altitude)` and try again.

**Comment by bweeding** [comment]
Ah yes, this is something Nils mentioned before but I tried and the results were odd.

So I modified kdir by inserting:
radI[i] = (radG[i]-radD[i])/np.sin(altitude[0][i] * np.pi/180)
into solweig_algorithm.py just before the use of so.Solweig_2021a_calc.

Looking first at the 1 day time period from the POI file, modifying the radiation makes the Tmrt output more reasonable, though the numbers are still high in some locations:
![image](https://user-images.githubusercontent.com/57697604/157169764-e16b573b-fa2f-408b-99a7-338f4907aae8.png)

If we look at the spatial maximum for each hour we see modifying the radiation has quite an impact in increasing the Tmrt values:
![image](https://user-images.githubusercontent.com/57697604/157169810-5704c380-c40d-45e7-89f4-4494645783b8.png)

and if we look at the radiation values from the POI file, we can see increases in kdir and kdown:
![image](https://user-images.githubusercontent.com/57697604/157169834-6cc63879-6cbf-4bdf-9d9a-20a0a663ad12.png)

Checking to see what happens on a longer time period, we see that using the radiation modification results in much higher Tmrt values, including some very large spikes.
![image](https://user-images.githubusercontent.com/57697604/157169887-d4c73ac8-3450-4937-ae5e-17d315f5c6aa.png)

If we do an hourly boxplot of all the data (not spatial max/min), we can see these extreme values occur at the 7:30, 8:30, and 9:30 timestamps.
![image](https://user-images.githubusercontent.com/57697604/157169974-f5f6e3c3-9aa7-4d3b-b90f-11ace8037722.png)

If I perform the same plot without the radiation modification, we see strange values for 8:30 and 15:30, though only low rather than high:
![image](https://user-images.githubusercontent.com/57697604/157169924-591402ac-6f68-42a9-bb3e-cdba4ff4f1e2.png)

Does that suggest any particular issue other than extremely high values cased by dividing by sin(alt) when alt is very low?

Cheers
Ben

**Comment by biglimp** [comment]
The values looks more reasonable now when you are using the correct Kdir.

I think you are correct that the division of sin(alt) is one of the issues here. The model is very sensitive during mornings and evenings and if you have small time biases between sun position and the observed forcing data you can end up with these spikes. It is always the relation between sun altitude and radiation that can cause this. I suggest that you filter out values when you have:
- larger Kdiff than Kglobal
- Negative Kdown
- Unreasonable high Kdir (larger than e.g. 1500)

Me and Nils will think on how to get rid of these unreasonable high/low Tmrt values by putting in restrictions in the model. We might come back to you to test later.

**Comment by bweeding** [comment]
Ok great I'll have a tinker tomorrow and show you the results. Should I
stick with the radiation modification though?

**Comment by biglimp** [comment]
Yes, radiation perpendicular to the solar beam.

**Comment by bweeding** [comment]
Ok great, I'll send through some results tomorrow! Enjoying figuring this
out!!

**Comment by bweeding** [comment]
So I included the following conditions to filter out the "bad" values:

  ```
          if (radDout>radG[i]).any():
                Tmrt.fill(np.nan)
                
            if (Kdown < 0).any():
                Tmrt.fill(np.nan)
                
            if (radIout > 1500).any():
                Tmrt.fill(np.nan)
```
and used data from 
`starting_date = '1994-01-01';
finishing_date = '1996-12-31'`

This gives reasonable looking mins and maxes:
![image](https://user-images.githubusercontent.com/57697604/157367179-be6769ca-ac62-4735-8c54-84030bdf54c9.png)

If we do an hourly boxplot, it seems like there are some very high values in the morning:
![image](https://user-images.githubusercontent.com/57697604/157367358-4a6e7308-47d5-472d-8747-1ae398ffb565.png)

The filtering removed 847 timestamps out of 26281, ~3.2%. If we plot the filtered timestamps by hour, we see morning contributes more than evening:
![image](https://user-images.githubusercontent.com/57697604/157369430-0e8921c3-39d2-4241-8af2-70b87e1d1cc2.png)

I can translate the good Tmrt values over to UTCI:
![image](https://user-images.githubusercontent.com/57697604/157370527-e2e1c2e0-2810-4df3-8407-a58f35d211aa.png)

and then compare Tmrt, Tair, and UTCI:
![image](https://user-images.githubusercontent.com/57697604/157371709-c9596778-5d71-414d-8e09-f56c7a0326bd.png)

**Comment by bweeding** [comment]
In relation to the problems caused by offsets between sunrise in altitude and in the meteorology, will that be connected to the position of the target location within the timezone? Or is that accounted for within the model?

**Comment by biglimp** [comment]
That is accounted for. I am thinking of other things that could happen e.g.:
- A clock in a logger is showing wrong time when using observed data as input forcing. Very small difference can produce the error that you have discovered
- The data is not average up to the recorded timestep but instead momentaneous values for that timestep

Thanks for presenting your restrictions in the comment above. We will include these in the model in the future.

**Comment by bweeding** [comment]
Ah ok. My data is averaged for the surrounding hour ie. 0930 data is the
mean from 0900 to 1000. Could that be it?

**Comment by biglimp** [comment]
Well, it depends where your data is coming from. If you have observed averaged data for 0900 and 1000 etc., you should not move the data to 0930. AND, if you have momentaneous data you should use 0930. SOLWEIG calulates the sun position inbetween timesteps, i.e. if you have data on the hour e.g. 0900 and 1000 then the position is calculated for 0930.

With obsereved avarge data I mean that fro 1000, an average of samples between 0900 and 1000 is recorded for the 1000 timestep.

Hope this makes sense...

**Comment by bweeding** [comment]
Ah so if my data is an average from 0900 to 1000 (it's a reanalysis
product) then I should associate it with a timestamp of 1000?

**Comment by biglimp** [comment]
Yes, if reanalysis data timestamp 1000 is an average between 0900 and 1000.

**Comment by bweeding** [comment]
Ok I'll restamp the times tomorrow and send through a comparison.

**Comment by bweeding** [comment]
Ok I've used 1994 data to compare the old (on the half hour) to the new (at the end of the hour) timestamping. 
This reduced the number of "bad" timestamps from 266 to 178 (from 3% to 2%).

We can see a shift in the Tmrt values and what looks like a reduction in extreme values.
![image](https://user-images.githubusercontent.com/57697604/157562271-6955e3af-0138-4b28-8003-587e88603698.png)

Checking this with a histogram confirms that an actual change in values has occurred, rather than simply a shift of values from one hour to another:
![image](https://user-images.githubusercontent.com/57697604/157563283-69d93f98-c706-4d02-b3f8-191f4dabf7c7.png)

**Comment by biglimp** [comment]
@bweeding , can i close this (or maybe move to discussions)?

**Comment by bweeding** [comment]
Yep, close away!
