### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 63: invalid continuation byte

### ISSUE THREAD

**Issue by dounia43** [UMEP-dev/UMEP#373]
I have the following error message every time I try to open a meteorological data file (loaded from the Copernicus program) using the plugin UMEP in QGIS. How can I fix it? I am a beginner in Python.

the meteo file is attached here,
[meteo.zip](https://github.com/UMEP-dev/UMEP/files/8078569/meteo.zip)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 63: invalid continuation byte 
Traceback (most recent call last):
  File "C:/Users/pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\MetdataProcessor\metdata_processor.py", line 213, in import_file
    header = f.readline().split(delim)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 63: invalid continuation byte

**Comment by biglimp** [comment]
Please attach your file so that I could tryit out.

**Comment by dounia43** [comment]
the meteo file is attached here,
[meteo.zip](https://github.com/UMEP-dev/UMEP/files/8078922/meteo.zip)

**Comment by biglimp** [comment]
You are trying to use a netCDF-file directly into UMEP. That is not possible. You should convert it into a text file and then run it through a MetDataProcessor OR download ERA5 data via the ERA5 Download tool in UMEP which will convert nc-files directly into UMEP-formatted meteorological files.
