### ISSUE TITLE
SUEWS prepare error

### ISSUE THREAD

**Issue by dounia43** [UMEP-dev/UMEP#376]
Hello, 
as described in the tutorial, I am using suews prepare in the UMEP pre-processor to generate inputs to run SUEWS. I used Madrid LCZ from wudapt, and then i used the default parameters for the LCZ in the LCZ converter.  I get the following message when trying to generate using SUEWS Prepare:

Operations cancelled, process unsuccessful! See the General tab in Log Meassages Panel (speech bubble, lower right) for more information.
2022-02-20T11:10:23     CRITICAL    EXCEPTION IN C:/Users/pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
             LINE 355 "IMP_wai = split[8]" 
             ERROR MESSAGE: list index out of range

UMEP 3.19.2
[lcz_build_MPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/8103935/lcz_build_MPGrid_isotropic.txt)
[lcz_LCFGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/8103936/lcz_LCFGrid_isotropic.txt)
[lcz_veg_MPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/8103937/lcz_veg_MPGrid_isotropic.txt)
[umepmeteoformat.txt](https://github.com/UMEP-dev/UMEP/files/8103940/umepmeteoformat.txt)

**Comment by biglimp** [comment]
We are aware of this error and are working on a solution. You can read more here #366

**Comment by biglimp** [comment]
Adjusted LCZ Converter to include H/W-ratio.
