### ISSUE TITLE
QGIS crashes when using UMEP- SUEWS advance

### ISSUE THREAD

**Issue by ozyaz** [UMEP-dev/UMEP#395]
**Describe the bug**
Dear UMEP COmmunity,

I want to share this error, keep happining to me when using UMEP/SUEWS advance. What seems to be the root of the cause?

here is the message of the error:

Crash ID: [9d3af83ee33d083733b84131e9a26700b133e606](https://github.com/qgis/QGIS/search?q=9d3af83ee33d083733b84131e9a26700b133e606&type=Issues)

Stack Trace

PyInit_suews_driver :
PyInit_suews_driver :
PyInit_suews_driver :
PyInit_suews_driver :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
QMenu::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by biglimp** [comment]
Can you try please try with SUEWS in **UMEP for processing** also. Also I see that you are using QGIS 3.16 and I would recommend that you update to the latest version (3.24). Also check your **supy**-version. It should be dispalyed in the log messages (General tab) when you start QGIS.

**Comment by ozyaz** [comment]
@biglimp Thank you for the recommendation. I did download the new long term version. But it crashed again (with UMEP Processor) after half an hour..

QGIS version: 3.22.5-Białowieża
QGIS code revision: c27231782f
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.2
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 1c17a7)
Algorithm started at: 2022-04-15T17:16:50
Algorithm 'Urban Energy Balance: SUEWS' starting…
Input parameters:
{ 'AERO' : 0, 'ANTHRO' : 2, 'INPUT_DIR' : 'C:\\Users\\ozgey\\Desktop\\1-Thesis GIS\\DATA_Berlin SUEWS\\2-FILES- QGIS Berlin\\Test_tucc_500m\\SUEWS_Prepare_output_500', 'NET' : 3, 'OHM' : 1, 'OUTPUT_DIR' : 'C:\\Users\\ozgey\\Desktop\\1-Thesis GIS\\DATA_Berlin SUEWS\\2-FILES- QGIS Berlin\\Test_tucc_500m\\SUEWS_advance-output_500m', 'SMD' : 0, 'SNOW' : False, 'STAB' : 1, 'STORAGE' : 0, 'TIMERESOUT' : 60, 'WU' : 0, 'Z0' : 1 }

SuPy version: 2021.11.22 
C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy
C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy
Creating RunControl.nml
Initiating model
Loading forcing data
Running model (QGIS not responsive)

**Comment by biglimp** [comment]
Ok, probably memory issue as @sunt05 is suggesting.

**Comment by biglimp** [comment]
@ozyaz , is this issue still active or can I close?

**Comment by ozyaz** [comment]
> 

Yes please, thank you
