### ISSUE TITLE
UWG Processor (Processing Toolbox) error

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#399]
Trying to run UWG from the Processing Toolbox ends up in the processor hanging and the following python error message.

              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/AlgorithmDialog.py", line 273, in runAlgorithm
              'parameters': self.algorithm().asMap(parameters, self.context)
             Exception: unknown

Environment:
 - OS: macOS 11.5.1
 - QGIS: 3.24.1-Tisler
 - UMEP: 3.19.3
 - Python: 3.9.5

Thank you!
Csilla

**Comment by biglimp** [comment]
Hm, looks like a Mac-error. Never seen this error before. Do yo happen to have a Windows PC close by to see if UWG works there? Do you have issues with any other UMEP-tools from the processing plugin on your Mac?

**Comment by CsillaVG** [comment]
Tested now on two Windows PCs. It took me a while to get them running, but UWG now runs on both well*.
Regarding the Mac: I've tried a few things, but couldn't fix the above issue. All other UWG-related pre-processors work well. 

* minus occasional issue with saturation pressure

**Comment by biglimp** [comment]
Thanks for info. When does this Mac error occur? When you open the tool or when you click **run**?

**Comment by CsillaVG** [comment]
After clicking on run. The UWG never finishes. It seems to be stuck in a loop with a status bar indicating that something is in progress. 
The standard 'python error occurred' message comes up  immediately after pressing run and the above message is displayed in the Python error log. This is a warning level error. I accidentally have left out that part. I am sorry. :flushed:

**Comment by biglimp** [comment]
Can you open the Python console in QGIS and see if you have any additional messages there?

**Comment by CsillaVG** [comment]
Nothing. It is blank.

**Comment by biglimp** [comment]
Just to be shure, can you try `from uwg import UWG` in the QGIS Python console.

**Comment by CsillaVG** [comment]
Good you asked. I am new to using processing and the python console in QGIS. I did two things.
(1) Installed QGIS 3.24.2 on another mac (macOS 10.14.6) with UMEP 3.19.3. It gives the same exact error when trying to run UWG using the UI.
(2) used the UI of UWG to generate a python command and ran it in the python console. That worked like a charm.

**Comment by biglimp** [comment]
Ok, last test. Try to run UWG with the attached data, just to see if your input data is currupt.
[inputfilestest.zip](https://github.com/UMEP-dev/UMEP/files/8538614/inputfilestest.zip)

**Comment by CsillaVG** [comment]
I run it with your data,  but the issue is the same: the UI is hanging and there is a python error message in the background.

BTW, the data that I am using are working on two windows QGIS/UMEP installs with UWG run via the UI. On the macs, I can only get UWG working as a python command.

I have tried one more thing: running UWG prepare via the Processing Toolbox UI (on the macs). This function works without a problem when run via the QGIS integrated UI interface (the drop-down menu). When trying it via the Processing Toolbox, it gives the same error as above.

**Comment by biglimp** [comment]
Ok. Maybe I missunderstood you. Does any other tool in **UMEP for processing** work, e.g. **Shadow Generator**, so NOT from the menu-based UMEP but from the **Processing Toolbox**? You can use the attached DSM to try it out. UTC=1
[DSM_KRbig.zip](https://github.com/UMEP-dev/UMEP/files/8539470/DSM_KRbig.zip)

**Comment by CsillaVG** [comment]
No. I get the same error for trying to run the shadow generator as well.

**Comment by biglimp** [comment]
Aha! Now we are getting closer. Can you now try some other tools in the toolbox, e.g. **Create Grid**, **Raster Information** and see if these are working for you.

**Comment by CsillaVG** [comment]
Both ran just fine.

**Comment by biglimp** [comment]
Ok, so there is no issues in running niative processing tools. Now please try this. Download **Raster Quantilizer** from **Manage and Install Plugins** to check if this third party processing plugin works or fails for you.

**Comment by CsillaVG** [comment]
It worked.

**Comment by biglimp** [comment]
Sorry for making you trying all this but I have one more thing: Please download **Potential Slope Failure for processing** and use the attached data. This is another plugin from me and want to see if I am doing something wrong in general when I code these kind of plugins.

[testdata.zip](https://github.com/UMEP-dev/UMEP/files/8540868/testdata.zip)

**Comment by CsillaVG** [comment]
No problem. It run well, without any issue.

**Comment by biglimp** [comment]
Ok, thanks. Now I will see if I can find the issue. I will get back to you if I need you to try something more. Thanks Csilla!

**Comment by CsillaVG** [comment]
You are more then welcome. And the thank you is mine!

**Comment by biglimp** [comment]
Csilla, some updates. I examined the code and cannot see why it should not work for you. I also asked a colleague to try and for him is works. He has IOs 12.3 and QGIS 3.22.3. I asked him to update to 3.24 to see if the error appear.

**Comment by CsillaVG** [comment]
Thank you. I can also give a try to QGIS <3.24 this weekend.

**Comment by CsillaVG** [comment]
Update: UMEP processing runs well under QGIS 3.22.3 (both on iOS 10.14 and 11.15). 
However, for it to work, the pillow package needed to be upgraded on both systems.

**Comment by biglimp** [comment]
@CsillaVG , This issue might be outdated as new versions has arrived. Can I close? You can open a new issue if you experience the same issue on newer versions.
