### ISSUE TITLE
ImportError and RuntimeError

### ISSUE THREAD

**Issue by SimoneBeltramino** [UMEP-dev/UMEP#401]
I have tried to install the UMEP plugin both on the new 3.24 version and on a previous 3.16. I also tried on a mac computer but it keeps giving me the following error. What can I do to solve it?
Thanks in advance.
<img width="611" alt="Immagine 2022-04-15 114046" src="https://user-images.githubusercontent.com/103640974/163871561-8b345e9a-67a6-41a4-9acc-655f86078645.png">
<img width="746" alt="Immagine 2022-04-15 114153" src="https://user-images.githubusercontent.com/103640974/163871572-6fe570de-bcc4-4e6f-871f-2b9a28beed78.png">
[Errore.txt](https://github.com/UMEP-dev/UMEP/files/8507970/Errore.txt)

**Comment by sunt05** [comment]
please update your installed numpy.

**Comment by biglimp** [comment]
See [here](https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities) for instructions on how to upgrade numpy.
