### ISSUE TITLE
Pressure detected as out of range

### ISSUE THREAD

**Issue by PetitMote** [UMEP-dev/UMEP#403]
**Describe the bug**
I’m trying to import shiny weather data. Unfortunately, the preprocessor thinks all my pressure data is out of range, at every line.
I’ve located the condition here: https://github.com/UMEP-dev/UMEP/blob/7263c89b7c58467de655da2ca499661f8e1e7f77/MetdataProcessor/metdata_processor.py#L485

See my CSV file. I did convert data from Pa to kPa. I looked for min and max, and they are way inside the range.
[filec5f4bd507_lat=47.25_lng=-1.5_period=2021.csv](https://github.com/UMEP-dev/UMEP/files/8530366/filec5f4bd507_lat.47.25_lng.-1.5_period.2021.csv)

**To Reproduce**
1. Metdata processor
2. Set to 1 line of header, semicolon as separator, and load the attached csv
3. Set the time columns, and set the barometric pressure to "sp_kPa"
4. Export data and see the error

**Desktop (please complete the following information):**
 - OS: Win10
 - QGIS Version 3.24.1
 - UMEP Version 3.19.3
 - SuPy Version 2022.4.7

**Data**
[filec5f4bd507_lat=47.25_lng=-1.5_period=2021.csv](https://github.com/UMEP-dev/UMEP/files/8530366/filec5f4bd507_lat.47.25_lng.-1.5_period.2021.csv)

Thank you guys

**Comment by biglimp** [comment]
Did you try to downlaod as EPW-file and then tick in the EPW-format button on the preprocessor? That should work.
Otherwise, you should divide by 1000 and those numbers that are problematic should be adjusted manually. I also see that your ne column use , and not . as decimal. It should be a dot, not a comma.

**Comment by PetitMote** [comment]
I’ve tried to round the value with no decimal, and still got the error. Also, there is no out of range value, min is 98.5, and max is 103.5.

Thanks for the epw tip.

With the epw, it worked fine, thank you.

**Comment by biglimp** [comment]
Strange since the limits are 30 and 107...

**Comment by biglimp** [comment]
Just tried with your data (when replaced the commas) and could not replicate your error. Mine works fine.

**Comment by PetitMote** [comment]
Hi,
I did it too, when replacing commas by point using notepad++. Guess I won’t know what LibreOffice was doing wrong.

Thank you
