### ISSUE TITLE
Dsm generator failed to respond

### ISSUE THREAD

**Issue by WestDrift** [UMEP-dev/UMEP#416]
UMEP DSM generator failed to repsond.
![image](https://user-images.githubusercontent.com/79802447/168431415-778397d1-b04b-40da-9669-969e574468d9.png)

I'm confused which part was wrong, QGIS, python or UMEP？Really thanks if any one can help as soon as possible!

**Comment by nilswallenberg** [comment]
Hi @WestDrift,

Can you please attach your input data so I can have a look.

Cheers,
Nils

**Comment by WestDrift** [comment]
Hi Nils,


I left the programs running and found it completed 60% several hours later. I guess the problem is a too large research area and an old computer. Later I'll try some smaller data and observe the outcome.&nbsp;


I just began to use github recently and realized that my issue may not be so proper. Sorry to bother you and really thanks for your patient reply!


Best regards,
WestDrift



---Original---
From: ***@***.***&gt;
Date: Mon, May 16, 2022 21:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [UMEP-dev/UMEP] Dsm generator failed to respond (Issue #416)




 
Hi @WestDrift,
 
Can you please attach your input data so I can have a look.
 
Cheers,
 Nils
