### ISSUE TITLE
sudden error with SOLWEIG main process

### ISSUE THREAD

**Issue by ElyumOfTheRocks** [UMEP-dev/UMEP#424]
**Describe the bug**
SOLWEIG main process started crashing upon "run". A few days ago, it was working fine, I do not think I changed anything since it worked. I wonder what I did wrong...

When running from UMEP tab (not processing), I get this error  : 

2022-06-09T12:23:27     CRITICAL    EXCEPTION IN 
C:\Users/udesr4d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SOLWEIG\solweigworker.py,
LINE 290 "dRad, Kside = so.Solweig_2022a_calc("
ERROR` MESSAGE: local variable '**patches_in_band**' referenced before assignment

When running from UMEP processing, I get this error  : 
File"C:\Users/udesr4d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\solweig_algorithm.py", line 955, in processAlgorithm
dRad, Kside = so.Solweig_2022a_calc(
File"C:\Users/udesr4d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\SOLWEIGpython\Solweig_2022a_calc_forprocessing.py", line 344, in Solweig_2022a_calc
Lside, L_patches, CI_Tg, CI_TgG, KsideD, dRad, Kside
UnboundLocalError: local variable '**L_patches**' referenced before assignment

**To Reproduce**
I tried with different combinations of parameters, image below is one of them. I also tried with another qgis project with different data and with the Goteborg tutorial, but the issue remains the same.
![image](https://user-images.githubusercontent.com/91809050/172898847-6041f103-1449-48dc-a0d0-1ac4ba8f5797.png)

**Desktop**
 - OS: win10
 - QGIS Version 3.22
 - UMEP Version [e.g. 3.20]
 - SuPy Version e.g. 2022.4.7

Thanks for your time!

**Comment by nilswallenberg** [comment]
Sorry for the inconvenience. It should be fixed now and a new version is available here on GitHub (also attached zip files) and soon in the QGIS repository.

Cheers,
Nils

[UMEP-processing-main.zip](https://github.com/UMEP-dev/UMEP/files/8877210/UMEP-processing-main.zip)
[UMEP-SuPy-QGIS3.zip](https://github.com/UMEP-dev/UMEP/files/8877211/UMEP-SuPy-QGIS3.zip)

**Comment by ElyumOfTheRocks** [comment]
great! thanks for the quick response. I'm curious about the reason of the error, was it a fix I could have seen?
