### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by khorsans** [UMEP-dev/UMEP#429]
Hi all,
Can the SUEWS scheme be used on dusty days as well? My goal is to study the changes in the amount of heat and radiation fluxes of a city on dusty days using the SUEWS scheme.

**Comment by suegrimmond** [comment]
Yes - if you have the forcing meteorology for those conditions.
The surface resistances have not been developed or tested under those conditions specifically. But depending on where you are thinking of there may other considerations first.
