### ISSUE TITLE
Error while running SEBE (umep processor) - Urgent

### ISSUE THREAD

**Issue by Frappetro** [UMEP-dev/UMEP#433]
Hi everyone!! I'm finally finishing my master degree thesis but I'm having trouble with running the SEBE simulation, in particular while running it, this python error comes out:

TypeError: can only concatenate str (not "NoneType") to str 
Traceback (most recent call last):
  File "C:\Users/Petro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBE\sebe.py", line 472, in start_progress
    WriteMetaDataSEBE.writeRunInfo(self.folderPath[0], filepath_dsm, self.gdal_dsm, self.usevegdem,
  File "C:\Users/Petro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBE\WriteMetaDataSEBE.py", line 27, in writeRunInfo
    file.write('Projected referece system: ' + srs.GetAttrValue('projcs'))
TypeError: can only concatenate str (not "NoneType") to str

I understand the problem could be related to the reference system but don't know ho to solve it!!
While running the Swedish tutorial i got no problem, but now seems the programm can't upgrade the text file with the correct info, it only acquires information about surface data and model domain, not utc, latitude or longitude...

I need to solve this problem and send the thesis, please help me!! 
Thank you in advance!

**Comment by biglimp** [comment]
Try change to a CRS on your DSM that are more common e.g. UTM. For e.g. west coast Sweden that would be EPSG:32632.
