### ISSUE TITLE
Solweig processor (UMEP) from processing toolbox

### ISSUE THREAD

**Issue by Axou973** [UMEP-dev/UMEP#437]
Hello, I have the same problem. With the UMEP processor from Processing ToolBox, The outdoor thermal comfort doesn't work.
they show me that : 
Longitude derived from DSM: 4.78884444108657
Latitude derived from DSM: 45.77444574049266
Vegetation scheme activated
Sky View Factor rasters loaded
Meteorological data successfully loaded
Calculating sun positions for each time step
Isotropic sky
Writing settings for this model run to specified output folder (Filename: RunInfoSOLWEIG_YYYY_DOY_HHMM.txt)
Executing main model
Traceback (most recent call last):
File "C:\Users/admin-ddavid/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\solweig_algorithm.py", line 955, in processAlgorithm
dRad, Kside = so.Solweig_2022a_calc(
File "C:\Users/admin-ddavid/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\SOLWEIGpython\Solweig_2022a_calc_forprocessing.py", line 344, in Solweig_2022a_calc
Lside, L_patches, CI_Tg, CI_TgG, KsideD, dRad, Kside
UnboundLocalError: local variable 'L_patches' referenced before assignment
Execution failed after 6.06 secondes

For the meteo data, I used the pre-processor Meteorolagical Data. I converted the data in epw to txt with the tool. 
But I don't understand why does the data change a lot ? (from epw to txt). For exemple it's not the same year.
Where can I send my zip folder to check what is wrong ?
I have the last version of UMEP an UMEP processing

Thank you for your help
[actual.txt](https://github.com/UMEP-dev/UMEP/files/9093582/actual.txt)
[actual_2.txt](https://github.com/UMEP-dev/UMEP/files/9093583/actual_2.txt)
![SOLWEIG_ERROR](https://user-images.githubusercontent.com/91162605/178506288-a0ca9024-1a24-41bb-9d4c-b90b8d69dc5c.jpg)

**Comment by nilswallenberg** [comment]
Hi,

I have hopefully fixed this. There is a new version here at GitHub (will be available in the QGIS repository later).

Cheers,
Nils

**Comment by ML426** [comment]
Hi @nilswallenberg,
I have the same problem,
How to import the new version in Qgis?

**Comment by nilswallenberg** [comment]
Here's how you can install it from zip-file:

https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable

Cheers,
Nils
