### ISSUE TITLE
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe 

### ISSUE THREAD

**Issue by ozyaz** [UMEP-dev/UMEP#439]
**Describe the bug**
Plug in doesnt work and gives this API version error again as it did in the past.
Therefore I couldnt use the SUEWS prepare in UMEP..
I went through the recomennded steps to update packages in UMEP Manuel here: https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities 

*****
ERROR:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe 

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.22.5-Białowieża Białowieża, c2723178 

****

**Desktop (please complete the following information):**

QGIS-Version | 3.22.5-Białowieża

Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041   (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 13.0
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version   2009
Aktive   Python-Erweiterungen |  
UMEP | 3.20
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

**Comment by sunt05** [comment]
Please update the `numpy` used by QGIS following the method here #409 .

**Comment by biglimp** [comment]
Update to the latest QGIS version 3.26. That will solve this.
