### ISSUE TITLE
Problem with the installation of Supy 

### ISSUE THREAD

**Issue by NishaPatel09** [UMEP-dev/UMEP#440]
Hello,

I am trying to install UMEP plug in in the QGIS and it is showing some error. I have tried to uninstall the plugin and tried it again but still, it is not working. The error which is popping up constantly is I mentioned below. I will be very happy to receive any kind of help for the same. 

**Desktop (please complete the following information):**
 - OS: Windows
 - QGIS Version [e.g. 3.18]
 - UMEP Version [e.g. 3.16.2]
 - SuPy Version [e.g. 2021.1.23]

<img width="575" alt="Error" src="https://user-images.githubusercontent.com/109536480/179546819-50f41173-b7f3-4ba6-b3a0-c100b828d764.png">

**Comment by sunt05** [comment]
similar to #421 ; possible workaround can be found here https://github.com/UMEP-dev/UMEP/discussions/409.

**Comment by biglimp** [comment]
Using the latest version of QGIS (3.26) solves this issue.
