### ISSUE TITLE
Leafon parameter with southern hemisphere data

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP#441]
Hi all, was looking to confirm that when a CDSM is loaded into SOLWEIG, it defaults as evergreen/coniferous?

Came across what I believe is a bug in Solweig_v2015_metdata_noload.py:

```
    leafon1 = 97  #TODO this should change
    leafoff1 = 300  #TODO this should change
```

Looks like the timings are only for the northern hemisphere?

Cheers
Ben

**Comment by biglimp** [comment]
Hi Ben,
Yes, you are correct. This is me being lazy back when I wrote this code. We will try to change this. I the meantime you can change this in the code yourself... /Fredrik

**Comment by nilswallenberg** [comment]
Hi Ben,

The new fix hopefully works for the southern hemisphere as well. :-)

Cheers,
Nils
