### ISSUE TITLE
Simulation error Tmrt

### ISSUE THREAD

**Issue by SimoneBeltramino** [UMEP-dev/UMEP#455]
When I run the simulation of the Mean Radiant Temperature with SOLWEIG it gives me the following error in the log messages.

```
EXCEPTION IN C:\Users/simone.beltramino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SOLWEIG\solweigworker.py, 
             LINE 290 "dRad, Kside = so.Solweig_2022a_calc(" 
             ERROR MESSAGE: local variable 'L_patches' referenced before assignment
```

I tried to update the NumPy libraries as described in the UMEP manual but it doesn't change the situation. I have a PC with Windows operating system, I have tried with other PCs with the same operating system but the problem persists.

**Comment by nilswallenberg** [comment]
Hi,

Try the latest version of UMEP (download the one here on GitHub) and install with zip. Should fix this!

Cheers,
Nils
