### ISSUE TITLE
SUEWS prepare window

### ISSUE THREAD

**Issue by Empanag** [UMEP-dev/UMEP#461]
**Describe the bug**
Hi, inside SUEWS prepare plugin, i can't uncheck the option for shapefile for weekend in both tabs of automatic and manual water use.

**Desktop (please complete the following information):**
 - OS: W11
 - QGIS Version 3.22.6
 - UMEP Version 3.20.6
 - SuPy Version 2022.4.7

![image](https://user-images.githubusercontent.com/61833032/192766910-45bd91b9-d6c8-4526-a321-460d76a2a628.png)

Also a save option for setting would be very helpful.
Thanks

**Comment by biglimp** [comment]
I did not write this code but I will see if I can fix it. I also want to inform you that a new plugin is coming soon SUEWS Database which will improve the pre-processing for the SUEWS-model. 
We will probably not add an save setting, but who knows...

**Comment by biglimp** [comment]
The tickbox should be fixed now. The "Save settings" is not considered at this time. It will probable take some time before new version is available in QGIS repo. Use Development Release is you cannot wait.
