### ISSUE TITLE
okay I there were missing some values in the tree morphology file. After fixing this it worked!

### ISSUE THREAD

**Issue by shahjahan0275** [UMEP-dev/UMEP#462]
okay I there were missing some values in the tree morphology file. After fixing this it worked! 
But now QGIS still craches when using SUEWS advanced even with strongly reduced time period and cell number. The supy log just says '2020-12-22 19:24:54,578 - SuPy - INFO - All cache cleared.' 

I will attach my SUEWS prepare results. Would be great if you can at least check weather it works at your side or not.

[prepare_klein1.zip](https://github.com/UMEP-dev/UMEP/files/5731514/prepare_klein1.zip)

_Originally posted by @flgebhardt in https://github.com/UMEP-dev/UMEP/issues/207#issuecomment-749715536_

**Comment by shahjahan0275** [comment]
I am also facing the same problem with SUEWS prepare. can you please tell me which " values in the tree morphology file" that you have fixed to solve the issue.

**Comment by biglimp** [comment]
Before we move on, could you please try to run SUEWS from **UMEP for processing** first and report back the result.

**Comment by shahjahan0275** [comment]
I could not prepare the data to run SUEWS using "SUEWS prepare" due  to that problem. So how can I run SUEWS from UMEP for processing with out prepared data

**Comment by shahjahan0275** [comment]
So I am facing this problem 
python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
             LINE 425 "zH = (float(IMP_heights_mean) * LCF_bu + float(IMPveg_heights_mean_eve) * LCF_ev + float(IMPveg_heights_mean_dec) * LCF_de) / (LCF_bu + LCF_ev + LCF_de)" 
             ERROR MESSAGE: local variable 'IMPveg_max_dec' referenced before assignment

I am using QGIS 3.26.3 
May I know "What are the values that you missed in the tree morphology file"
Regards

**Comment by shahjahan0275** [comment]
is there any problem in the "prepare_worker.py" to show the error above?

**Comment by biglimp** [comment]
Ok, now I understand a bit better. 

Can you attach your files that you use in SUEWSPrepare and your settings for vegetation, i.e. are you using both deciduous and confier.

**Comment by shahjahan0275** [comment]
[_build_MPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/9731989/_build_MPGrid_isotropic.txt)
[_LCFGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/9731990/_LCFGrid_isotropic.txt)
[_veg_MPGrid_isotropic.txt](https://github.com/UMEP-dev/UMEP/files/9731991/_veg_MPGrid_isotropic.txt)
[NYC_2010_UMEP.txt](https://github.com/UMEP-dev/UMEP/files/9731994/NYC_2010_UMEP.txt)

**Comment by shahjahan0275** [comment]
These are the files that I used in SUEWS  prepare. I was exactly following this tutorial
https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsWUDAPT.html#suewswudapt

**Comment by biglimp** [comment]
I need your grid also (shapefile).

**Comment by biglimp** [comment]
I need your grid also (shapefile).

**Comment by shahjahan0275** [comment]
[SUEWSWUDAPT_NYC.zip](https://github.com/UMEP-dev/UMEP/files/9735656/SUEWSWUDAPT_NYC.zip)

**Comment by shahjahan0275** [comment]
All the grid  (shapefile) is in the zip. Regards

**Comment by biglimp** [comment]
Found the bug. Should be fixed now. It will probably take some time before new version is available in QGIS repo. Use Development Release is you cannot wait.

**Comment by shahjahan0275** [comment]
I am facing following problem while running UMEP > Processer > Urban Energy Balance > Urban Energy Balance (SUEWS/BLUEWS, advanced). I am following the same tutorial as before:
https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsWUDAPT.html#suewswudapt
![image](https://user-images.githubusercontent.com/39149359/196490208-07f280b7-5802-456a-943f-cde102a768de.png)

attaching supy log also:

[SuPy.log](https://github.com/UMEP-dev/UMEP/files/9812783/SuPy.log)

**Comment by biglimp** [comment]
What version of UMEP are you using. THis might have been fixed in the latest version.

**Comment by shahjahan0275** [comment]
I am using the following version:
UMEP Available version (stable) 	3.20.7 updated at Tue Oct 11 02:56:13 2022

**Comment by biglimp** [comment]
Can also please check your version of SuPy. Should be displayed as a log message in QGIS.

**Comment by biglimp** [comment]
I think I found the issue. Updated to 3.20.8. Install as a development release (https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable). You need to go back in the tutorial and re-run SUEWS Prepare.

**Comment by shahjahan0275** [comment]
I have followed your instruction. same error:
![image](https://user-images.githubusercontent.com/39149359/197170910-7e8aa8ee-cbff-43e7-99ac-550472a44065.png)
[SuPy.log](https://github.com/UMEP-dev/UMEP/files/9838032/SuPy.log)

**Comment by biglimp** [comment]
What.version of SuPy do you have?

**Comment by biglimp** [comment]
Ok, new try. Download latest development release and try again.

**Comment by shahjahan0275** [comment]
![image](https://user-images.githubusercontent.com/39149359/197741614-53243d0c-97b0-46bc-acfe-72e8a27c48c9.png)
I have 32 GB installed memory on my laptop.

**Comment by biglimp** [comment]
First things first, did we get rid of the other error? This is a new one?

**Comment by shahjahan0275** [comment]
Yes, there are no other error, SUEWS ran for quite some time, then this
error occurred. Regards

**Comment by biglimp** [comment]
@sunt05, what do you make of this last error?

**Comment by biglimp** [comment]
hm, this error is produced from one of our [tutorials ](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsWUDAPT.html#suewswudapt) which worked before SuPy. We need to find a solution to this.

**Comment by sunt05** [comment]
> Yes, there are no other error, SUEWS ran for quite some time, then this error occurred. Regards

@shahjahan0275 Thanks for the update - then please close this issue and follow up on [the new one](https://github.com/UMEP-dev/UMEP/issues/465).

@biglimp to me, this seems to be an upstream issue as explained in [the issue referenced here](https://github.com/UMEP-dev/SuPy/issues/47).
