### ISSUE TITLE
Meteorological Data: Download data (ERA5) does not deliver data

### ISSUE THREAD

**Issue by jkblizzard** [UMEP-dev/UMEP#467]
Once the coordinates and the target directory are entered, the download tool indicates working status. However, even after six hours and longer nothing happens.
I have followed the instructions, registered at Copernicus, installed both CDS API key and client. 
I have not received any error message.
The CDS live site indicates no requests from my site (yes, I am logged in)

 - OS: Debian 11
 - QGIS  3.10
 - UMEP  3.20.6

Maybe I have misunderstood installation instructions on the Copernicus howto site. However, I cannot figure out at which point I made a mistake. 
Thanks a lot for any support in advance.

**Comment by biglimp** [comment]
Based on traffic, it can take a loooong time to downlaod. If you open your python console, you can see some info on the progress. I just started one download below:
![image](https://user-images.githubusercontent.com/11908356/198247362-94cb3031-085f-470d-bcba-68aa807a5955.png)

If you are interested in Europe I can recommend to have a look at https://www.shinyweatherdata.com/. Here, someone made an interface which is much more effective.

**Comment by jkblizzard** [comment]
thanks a lot for your instant response. 
My python console indicates the download directory on my computer and then nothing. There is no "Welcome to CDS", etc.
Thanks for linking me to shinyweather. However, that did not work for me either. I have got a number of disconnection messages, and ones the download process was indicated to be finished I could not access the csv file in the export section. I was referred to a google mail account but I do not have a google account.

**Comment by biglimp** [comment]
Just tried the shinyweather thing. No problems for me.

HAve you tried to access the data outside as shown here: https://cds.climate.copernicus.eu/api-how-to? Try that and let us know the result.

**Comment by biglimp** [comment]
@jkblizzard , any progress on this issue. Can I close it?
