### ISSUE TITLE
Installing missing Python Packages when installing UMEP and UMEP for processing error on MacOS

### ISSUE THREAD

**Issue by gusbacos** [UMEP-dev/UMEP#472]
**Describe the bug**
The possibility for installing missing python packages when installing UMEP and UMEP for processing generate following error message

Packages not installed. report any errors to...

when i try to import supy in the QGIS python console, supy is not installed

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - QGIS Version 3.26.3
 - UMEP Version 3.20.7
 - SuPy Version None

Best, 
Oskar

**Comment by sunt05** [comment]
Seems to be caused by a deprecated option in `pip` that was used in our supy installation script.

@biglimp please review my PR #474 and see if it would fix this issue - thanks!
