### ISSUE TITLE
Umep Prepare is looking for Gridlayout file...( ERROR MESSAGE: ........\suewsmodel/Input/GridLayoutKc.nml')

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/UMEP#484]
Hi everyone,
Using UMEP SUEWS prepare I encountered an error as shown below.

2022-12-16T21:35:06     CRITICAL    EXCEPTION IN C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
             LINE 837 "copyfile(self.output_path + 'GridLayoutKc.nml', self.output_dir[0] + "/" + 'GridLayout' + str(self.file_code) + '.nml')" 
             ERROR MESSAGE: [Errno 2] No such file or directory: 'C:\\Users/User/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\UMEP\\suewsmodel/Input/GridLayoutKc.nml'

Seems the code is looking for a GridLayoutKc.nml. while in the suews prepare interface, there is nowhere to upload such file. could anyone please advise..Before now, I use to work with suews prepare without any problem, but since I updated the plugin, I encountered this issue.     Thanks

**Comment by phemiobe** [comment]
solved ..When I prepare the GridLayout file and placed it in the corresponding directory

**Comment by sunt05** [comment]
thanks @phemiobe for reporting this.

@biglimp I think we may need implement an empty `GridLayout.nml` or alike to pass the checking of supy even though the related features are not used by ordinary UMEP users.

**Comment by biglimp** [comment]
Hm, there should already be an empty file like included. @phemiobe , can you describe more in detail how you produced your error, i.e. what tools did you use and what versions? You need to update both SuPy and the UMEP plugin as UMEP copies the files from a sub-directory in the SuPy directory.

**Comment by phemiobe** [comment]
Thanks, guys for your responses. 
The error was produced when I run SUEWS prepare with UMEP (Installed version 3.20.9) which I think is the latest version.
Thank you

**Comment by biglimp** [comment]
And what is your version of SuPy?

**Comment by phemiobe** [comment]
supy: 2022.2.17 
supy_driver: 2021a2

**Comment by biglimp** [comment]
I think you might need to update your supy (https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities). You can also check what files you have in your sample_run folder. Type: `sys.modules["supy"].__path__[0]` in your Python console in QGIS. Then you see where your supy is located. Then go to **sample_run/input** and see if you see the missing file(which I dont think you will find)

**Comment by biglimp** [comment]
@phemiobe , did you solve this issue by updating supy?

**Comment by phemiobe** [comment]
Yeah. Thanks
