### ISSUE TITLE
missing trees with Tree Generator

### ISSUE THREAD

**Issue by s-martiz** [UMEP-dev/UMEP#495]
Dear UMEP-users,

I am having a problem using the Tree Generator module to generate CDSM.tif and TDSM.tif layers from a trees.shp layer. 
I noticed that some trees are missing in the .tif files (see below)

in green the trees position
<img width="527" alt="image" src="https://user-images.githubusercontent.com/50947346/214895797-d9fc7b3a-fe43-40e2-9f59-321125d1e975.png">

and the resulting CDSM.tif
<img width="511" alt="image" src="https://user-images.githubusercontent.com/50947346/214895962-8da1c4e8-3fd8-4cfb-93be-6699969aa383.png">

Is there a limitation on the number of trees the Tree Generator can take as input? 
Sincerely

PS : you'll find attached the data used for this example
[data.zip](https://github.com/UMEP-dev/UMEP/files/10511544/data.zip)

**Comment by nilswallenberg** [comment]
Hi,

We'll look into it. We need the remaining files for the .shp though (e.g. .dbf, .prj, .shx).

Cheers,
Nils

**Comment by s-martiz** [comment]
Hi,
Thank you for your answer.
You'll find attached the remaining files
Sincerely
Simon
[data.zip](https://github.com/UMEP-dev/UMEP/files/10517281/data.zip)

**Comment by nilswallenberg** [comment]
Thank you! 

I had a quick look at your DSM and DEM and they differ where there is supposedly ground surface. For example in bottom center where you don't get trees the DSM have values ~17 and the DEM ~12. Running the tool with the DEM in both Raster DSM and Raster DEM results in a CDSM with trees in all locations.

I would check the DSM and DEM to see if they are correct.

Cheers,
Nils

**Comment by biglimp** [comment]
I am closing this as this seem to be a data issue, not a code issue. Please resubmit if problems does not go away.
