### ISSUE TITLE
Add diagnostic height in ERA5 download tool

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP#498]
Add capabilities to adjust ERA5 data to specific forcing height. @sunt05 , what should the default height and range for this variable be?

**Comment by sunt05** [comment]
The default value used in SuPy is 100 m - the minimum value should be dependent on the mean building height while the max can be infinity.

**Comment by biglimp** [comment]
So now, when we dont set **hgt_agl_diag** in **gen_forcing_era5**, we recalculate to 100 magl? min and max are just needed to set some limits in the tool. How about having a range between 2 and 500 meters?

**Comment by sunt05** [comment]
> So now, when we dont set **hgt_agl_diag** in **gen_forcing_era5**, we recalculate to 100 magl? 

That's correct. 

> min and max are just needed to set some limits in the tool. How about having a range between 2 and 500 meters?

Looks good to me.
