### ISSUE TITLE
ISSUE WITH DSM GENERATOR

### ISSUE THREAD

**Issue by buritilg** [UMEP-dev/UMEP#499]
I am not able to generate the DSM from DEM and building footprints. Could somebody help me?  I am new to UMEP. Please take a look at the attached DEM and building footprint files. The CRS is the same for both layers.

2023-02-07T12:13:59     WARNING    Traceback (most recent call last):
               line 645, in start_progress
              dsm_array = np.array(dsm_raster.ReadAsArray().astype(np.float))
             AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

[DEM_NAD83SOUTH.zip](https://github.com/UMEP-dev/UMEP/files/10677732/DEM_NAD83SOUTH.zip)
[Building_footprints.zip](https://github.com/UMEP-dev/UMEP/files/10677762/Building_footprints.zip)

**Comment by biglimp** [comment]
Hi. We have a discussion forum that is probably more effective if you want help. I will move you over there. Maybe @nilswallenberg can take a look tomorrow…
