### ISSUE TITLE
Meteorological Data: Download data (ERA5) Download never finishes

### ISSUE THREAD

**Issue by muenchhagen** [UMEP-dev/UMEP#509]
**Describe the bug**
I try to download Meteorological Data: via the tool "Meteorological Data: Download data (ERA5)". I start the process but it never ends. 
I tried it with a small dataset (for a single day). On the website "cds.climate.copernicus.eu" the request is stated as completed. 
I am using latest OSGeo4W package with QGIS 3.30 on Windows 10. 

**Desktop (please complete the following information):**
 - OS: Win 10
 - QGIS Version 3.30
 - UMEP Version 3.20.9
 - SuPy Version 2022.9.22

**Screenshots**
![CopernicusData_Screenshot](https://user-images.githubusercontent.com/16646571/225890175-09bdd945-3372-47c3-97d5-1ac8e6b43022.JPG)

**Comment by biglimp** [comment]
I cannot replicate your error. I downloaded one day for central London and it took only a few seconds. However, I am using QGIS 3.26 but I dont think it should matter. Make sure that your lat, lon is correct. Ocean areas is not included (I think).

**Comment by muenchhagen** [comment]
I don't know what happened. Now it works just fine ... 
I included a OSM Layer with the QuickMapService Tool. After that it worked. Maybe there was something off with my coordinates before.
