### ISSUE TITLE
TreeGenerator TDSM is necessary

### ISSUE THREAD

**Issue by svenjahoffmann** [UMEP-dev/UMEP#520]
### Discussed in https://github.com/UMEP-dev/UMEP/discussions/519

<div type='discussions-op-text'>

<sup>Originally posted by **svenjahoffmann** May 19, 2023</sup>
Dear UMEP Community,
I try to use the TreeGenerator in the Toolbox UMEP for processing. I have a canopy DSM and a point shapefile with new trees. With the TreeGenerator I want to add new trees to the current canopy DSM. I get the Error message: "No valid vegetation TDSM raster layer is selected. Both CDSM and TDSM must be selected if merging with existing". I already tried TreeGenerator months ago and it worked without TDSM, why do I need it now? I only want an updated CDSM, I don't want to update the TDSM (as it does not even exist). A few months ago I used the "normal" TreeGenerator Tool, not the one in the Toolbox for processing. But these days it's not possible anymore to use the "normal" one, there is the message: "This tool has moved to UMEP for processing, available via the QGIS Plugin Manager. Visit our online manual for more information".

Thanks for your help!!
</div>

**Comment by nilswallenberg** [comment]
Hi,

Should be fixed now. Try the latest version of UMEP for processing available here at GitHub. :)

Cheers,
Nils
