### ISSUE TITLE
Solar Energy of Building Envelope producing negative results

### ISSUE THREAD

**Issue by est987** [UMEP-dev/UMEP#521]
**Describe the bug**
I'm running the Solar Energy of Building Envelope processor, and for some odd reason I am receiving negative results. I tried with an older project's files and it worked fine. Not sure what is the problem here? Maybe something is wrong with my DSM?

**To Reproduce**
1. Run Solar Energy of Building Envelope on attached DSM, WALL ASPECT and WALL HEIGHT rasters:
CRS:6991 UTC: 2 (see screenshot )

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - QGIS Version 3.28.3
 - UMEP Version 4.0.1
 - SuPy Version 2022.9.22

**Screenshots**
![image](https://github.com/UMEP-dev/UMEP/assets/43732852/d281465c-c94a-4191-b96f-3042fca6e5a1)
![image](https://github.com/UMEP-dev/UMEP/assets/43732852/06abcc6c-aa33-450c-b3c5-35a7f3b8fb13)

**Data**
See Attached.
[DSM_RADIATION_DATA.zip](https://github.com/UMEP-dev/UMEP/files/11563245/DSM_RADIATION_DATA.zip)

**Additional context**
I have been working on a similar work process for many similar projects and worked so far without a problem. As I said, couldn't reproduce problem with a different DSM file from another project.

**Comment by biglimp** [comment]
Maybe something wrong with the CRS and your current version of QGIS? Try ro reproject to a more common CRS such as UTM and try again. Also, The solar radiation values in your metfile looks too low. Units should be W/m2.

**Comment by est987** [comment]
I rebuild the model with a more common CRS (2039) and was still receiving negative values.
So I created a new the MET file only for the six hours I'm interested with updated data (2013-2022 avg), and I received a much more reasonable result.

<img width="728" alt="image" src="https://github.com/UMEP-dev/UMEP/assets/43732852/eb47df09-173e-43db-a8c1-add476804ec3">

The reason the radiation values in MET file look small, is because they're divided by six. My understanding is that they are hourly values, while only representing 10 min (1/6 hour). If I don't do the division, I receive results two orders of magnitude larger than my expected range (0-4 kWh). Hope I'm not misunderstanding something.

Thank you for your help!

[BeitDeganKrinaAvgMetFile_DIVIDE-SIX_UTC2.txt](https://github.com/UMEP-dev/UMEP/files/11605233/BeitDeganKrinaAvgMetFile_DIVIDE-SIX_UTC2.txt)

**Comment by biglimp** [comment]
Ok, now I see. Sorry for not noticing before. SEBE must be executed with hourly data. It is stated in the manual but we should make that more clear to avoid misstake.

**Comment by est987** [comment]
Thanks! Do you think it is better to calculate the hourly average and rebuild the MET file with only one line per hour?

**Comment by biglimp** [comment]
Yes, one line per hour.
