### ISSUE TITLE
cannot access SUEWS advanced: "plugin moved to UMEP processing"

### ISSUE THREAD

**Issue by ozyaz** [UMEP-dev/UMEP#525]
Hi,

I want to use the SUEWS advanced under UMEP plug-in, but it says it moved to the UMEP processor, what does that mean?

Can I not run the advanced using QGIS anymore?

![Untitled picture](https://github.com/UMEP-dev/UMEP/assets/100167079/5995d44a-27f2-4132-859c-507aadfb6142)

**Comment by biglimp** [comment]
Yes, you can. I has just moved to UMEP for Processing. It is the same tool.

**Comment by ozyaz** [comment]
> Yes, you can. I has just moved to UMEP for Processing. It is the same tool.

I cannot find the SUEWS advanced in QGIS plugins though. I have the UMEP processing installed but, how do I supposed to access it? can you give me the steps and where to find it thanks :)

**Comment by biglimp** [comment]
Its just called SUEWS in UMEP fro Processing

**Comment by Witellsteim** [comment]
@ozyaz Did you manage to fix it? I have the same issue for some of my tools (SVF and SUEWS). I also have UMEP for processing installed, but can't find where to run it now.

Edit: 
Solved. I can run it by searching it from the QGIS Processing Toolbox. It just wont run via the UMEP tab

**Comment by ozyaz** [comment]
> Its just called SUEWS in UMEP fro Processing

But there is no plugin shown in the menu "UMEP for processing" in my QGIS I have the latest version 3.28 LTR. Can you please provide some screenshots from QGIS, that would be really helpful, cause there is no guidance on this one in the latest Tutorial document from May 2023..

**Comment by ozyaz** [comment]
> 

Hey, I actually also checked the processing toolbox but didnt appear. Which version of QGIS are you using?

**Comment by ozyaz** [comment]
Okay it is here!! thankss

![grafik](https://github.com/UMEP-dev/UMEP/assets/100167079/e2cc7a7a-ff45-4df5-9083-8a9dd0a9c59c)
