### ISSUE TITLE
Crash when installing UMEP for processing on Ubuntu 22

### ISSUE THREAD

**Issue by Chatellier-U-Eiffel** [UMEP-dev/UMEP#529]
**Describe the bug**
I'am new in QGIS and UMEP.
I'am trying to install UMEP and UMEP for processing on ubuntu 22.
Installing QGIS and UMEP works find but when I install UMEP for processing QGIS crashes.
Here is how I process for the installations

1. Create a new Ubuntu machine

2. Launch the following script with sudo :

apt install gnupg software-properties-common
wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg

echo "Types: deb deb-src" > /etc/apt/sources.list.d/qgis.sources
echo "URIs: https://qgis.org/debian" >> /etc/apt/sources.list.d/qgis.sources
echo "Suites: jammy" >> /etc/apt/sources.list.d/qgis.sources
echo "Architectures: amd64" >> /etc/apt/sources.list.d/qgis.sources
echo "Components: main" >> /etc/apt/sources.list.d/qgis.sources
echo "Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg" >> /etc/apt/sources.list.d/qgis.sources

apt update
apt install -y qgis qgis-plugin-grass

3. Launch the folloging command :

sudo apt install -y python3-pip

4. Launch the following commands without sudo

pip install pandas
pip install supy
python3 -m pip install --upgrade numpy
pip install xlrd
pip install xlwt

5. Launch QGIS and install UMEP

6. Install UMEP for processing (accept to install python modules to restart qgis)

QGIS crashes when executing the restart step of step 6

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - QGIS Version : 3.30.3-'s-Hertogenbosch
 - UMEP Version : 4.0.2
 - SuPy Version : I don't know

Many thanks in advance for your help.

 Patrice.

**Comment by biglimp** [comment]
@j3r3m1 , You use umep in a linux env. Du you have any suggestions?

**Comment by j3r3m1** [comment]
Have you tried an earlier version of QGIS ? Did you try starting QGIS within a Terminal in order to see what kind of error happen when QGIS crashes ?

**Comment by Chatellier-U-Eiffel** [comment]
I've tried QGIS 3.28 and 3.30

When I set URIs to https://qgis.org/debian QGIS 3.30 is installed
When I set URIs to https://qgis.org/ubuntu-ltr QGIS 3.28 is installed

I've started QGIS within a terminal. You will find the reports in the attached files (one for 3.28 and one for 3.30).
These files have been generated from virtual machines but I've also tried with a real machine and the results are the same.

[log_qgis_3_28.pdf](https://github.com/UMEP-dev/UMEP/files/11767446/log_qgis_3_28.pdf)
[log_qgis_3_30.pdf](https://github.com/UMEP-dev/UMEP/files/11767447/log_qgis_3_30.pdf)

**Comment by j3r3m1** [comment]
OK not that verbose. I am using Ubuntu 22.04 and QGIS 3.28 and it works fine but I have performed the installation of QGIS and all Python package in an anaconda environment. You might have a try installing conda and then in a new environment installing the following extra packages:
conda install qgis, pandas, geopandas, rasterio, gdal, numba, jaydebeapi, netcdf4, xarray 
Then in this conda environment start qgis and try installing UMEP for processing

**Comment by Chatellier-U-Eiffel** [comment]
I've created a new virtual machine. In that machine I've installed anaconda following the procedure described in
https://docs.anaconda.com/free/anaconda/install/linux/

Then I ran the following command in a terminal :
conda install qgis, pandas, geopandas, rasterio, gdal, numba, jaydebeapi, netcdf4, xarray

It seams conda does not find the packages I'm trying to install (see attached file).
[conda_error.pdf](https://github.com/UMEP-dev/UMEP/files/11768757/conda_error.pdf)

Is there anything I should don after installing conda and before executing the command conda install ... ?

**Comment by j3r3m1** [comment]
Once you have installed anaconda, do the following in a terminal to add conda-forge as a repo:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
``` 
Then you install the package as you did (you can also create a new environment beforehand if you want to have an other use of your conda installation than UMEP):
http://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

**Comment by Chatellier-U-Eiffel** [comment]
It seams the packages are still not found (see attached file)

[conda_error_02.pdf](https://github.com/UMEP-dev/UMEP/files/11769070/conda_error_02.pdf)

**Comment by j3r3m1** [comment]
Does a simple 
`conda install pandas `
work ?

**Comment by Chatellier-U-Eiffel** [comment]
I've entered the line 
conda install pandas

The file bellow contains what I got

[Conda_03.pdf](https://github.com/UMEP-dev/UMEP/files/11769891/Conda_03.pdf)

After 45mn I stopped the process because conda was still computing.

**Comment by Chatellier-U-Eiffel** [comment]
I've entered the line 
conda install pandas

The file bellow contains what I got

[Conda_03.pdf](https://github.com/UMEP-dev/UMEP/files/11769891/Conda_03.pdf)

After 45mn I stopped the process because conda was still computing.

Something else. When en enter the command "conda list" I get the following warning:

WARNING conda.core.prefix_data:_load_site_packages(288): Problem reading non-conda package record at lib/python3.10/site-packages/PyOpenGL-3.1.1a1-py3.10.egg-info/PKG-INFO. Please verify that you still need this, and if so, that this is still installed correctly. Reinstalling this package may help.

**Comment by j3r3m1** [comment]
I am not that familiar with virtual machine and maybe the problem comes from there, even though I do not see why. Could you please try to install anaconda in your Ubuntu 22.04 which is not a virtual one ?

**Comment by Chatellier-U-Eiffel** [comment]
Yes.
Next week on Tuesday I'll go to my office and reinstall everything on a real machine.
I'll let you know
Many tanks for your help and have a nice WE.

**Comment by Chatellier-U-Eiffel** [comment]
I've found the origin of the crash.

It comes from netCDF4. The version installed by UMEP for processing  in ~/.local/lib/python3.10/site-packages is the version 1.6.4.
UMEP works fine when I replace this version by version1.6.3.

So, before to install UMEP for processing one has to run the two following command lines :
pip install netCDF4==1.6.3
pip install numba

**Comment by Chatellier-U-Eiffel** [comment]
Many thanks again for you help.
