### ISSUE TITLE
error when using Outdoor Thermal Comfort: SOLWEIG v2022a

### ISSUE THREAD

**Issue by arz54** [UMEP-dev/UMEP#539]
I'm trying to use SOLWEIG v2022a like explain in the docs for TreePlanter with the dataset of the tutorial 
but when i run SOLWEIG  i have an error

File "C:\Users/xxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\solweig_algorithm.py", line 1231, in processAlgorithm
radG_for_plot = radG[DOY == unique_days[0]]
UnboundLocalError: local variable 'unique_days' referenced before assignment

I'm using 
- QGIS 3.32.0-Lima
- processing_umep  2.0.7

**Comment by nilswallenberg** [comment]
Hi,

Can you please attach your data and I will have a look at it.

Cheers,
Nils

**Comment by nilswallenberg** [comment]
Hi again,

Should be fixed now.

Cheers,
Nils

**Comment by arz54** [comment]
Hi sorry I've forgot to send you the data i test this soon ;)
