### ISSUE TITLE
Problem when running Urban Morphology: Morphometric Calculator (Point)

### ISSUE THREAD

**Issue by jassssuiiii** [UMEP-dev/UMEP#540]
**Describe the bug**
Problem encountered when running Urban Morphology: Morphometric Calculator (Point)

**To Reproduce**
1. Go to 'Urban Morphology: Morphometric Calculator (Point)'
2. choose point of interest
3. Search distance: 200m, Wind direction search interval (degree): 5
4. Select raster layers of DSM and DEM
5. Select saving directory and run the plugin
6. Error message appears:
> QGIS version: 3.20.2-Odense
> QGIS code revision: 9f59a156
> Qt version: 5.15.2
> Python version: 3.9.5
> GDAL version: 3.3.1
> GEOS version: 3.9.1-CAPI-1.14.2
> PROJ version: Rel. 8.1.0, July 1st, 2021
> PDAL version: 2.3.0 (git-version: eac774)
> Processing algorithm…
> Algorithm 'Urban Morphology: Morphometric Calculator (Point)' starting…
> Input parameters:
> { 'FILE_PREFIX' : 'RuleOfThumb', 'INPUT_DEM' : 'C:/../Merged DTM.tif', 'INPUT_DISTANCE' : 400, 'INPUT_DSM' : 'C:/../Merged DSM.tif', 'INPUT_DSMBUILD' : None, 'INPUT_INTERVAL' : 40, 'INPUT_POINT' : '355639.739613,170300.998768 [EPSG:27700]', 'INPUT_POINTLAYER' : None, 'OUTPUT_DIR' : 'C:\\Users\\yizhang\\Desktop', 'OUTPUT_POINT' : 'TEMPORARY_OUTPUT', 'OUTPUT_POLYGON' : 'TEMPORARY_OUTPUT', 'ROUGH' : 0, 'SAVE_POINT' : True, 'USE_DSM_BUILD' : False }
> 
> Point location obtained manually
> x = 355639.739613
> y = 170300.998768
> Traceback (most recent call last):
> File "C:\../python/plugins\processing_umep\preprocessor\imagemorphparmspoint_algorithm.py", line 247, in processAlgorithm
> immorphresult = morph.imagemorphparam_v2(dsm, dem, scale, 1, degree, feedback, 1)
> File "C:\../python/plugins\processing_umep\util\imageMorphometricParms_v2.py", line 99, in imagemorphparam_v2
> lineMid = a[0:imidy,imid]
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> 
> Execution failed after 0.23 seconds
> 
> Loading resulting layers
> Algorithm 'Urban Morphology: Morphometric Calculator (Point)' finished

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - QGIS Version: 3.20.2-Odense
 - UMEP Version: 4.0.2
 - SuPy Version: 2023.5.26.dev0

**Screenshots**

**Data**
If applicable, add data files to help us reproduce your problem.

**Additional context**

**Comment by biglimp** [comment]
I suspect there is an issue regarding CRS. Can you please share your data (DSM and DEM).

**Comment by biglimp** [comment]
@jassssuiiii , is this issue still valid? Can I close?

**Comment by biglimp** [comment]
No response. Please open a new issue if this is still a problem.
