### ISSUE TITLE
Error Code when installing the UMEP for Processing 

### ISSUE THREAD

**Issue by b-newtonp** [UMEP-dev/UMEP#542]
Hello I am new to QGIS and I have trying to install this plugin to do some solar PV calculations but I get this error code when trying to install it. RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe.  QGIS is upto date please help

**Comment by biglimp** [comment]
This is most probably a version conflict because you have an old version of QGIS. Update your QGIS and try again. Also have a look at our discussions page. There are many others who have had similar issues.  https://github.com/UMEP-dev/UMEP/discussions

**Comment by biglimp** [comment]
@b-newtonp , is this issue still valid or can I close?

**Comment by biglimp** [comment]
No response. Please open a new issue if this is not solved with newer versions.
