### ISSUE TITLE
Error with DSM Generator

### ISSUE THREAD

**Issue by amerville98** [UMEP-dev/UMEP#553]
**Describe the bug**
I have an AttributeError error when i process DSM Generator

**To Reproduce**
I first tried with my own DEM and Polygon with building height but i had the same error by using data from Goteborg_SWEREF99_1200

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGIS Version 3.32.3
 - UMEP Version 4.0.2 (umep for processing 2.0.7
 - Numpy version 1.24.1
![dsmgenerator](https://github.com/UMEP-dev/UMEP/assets/144142386/8b217e88-6d78-44d9-b0cd-07423c8d96b7)

**Comment by nilswallenberg** [comment]
Hi,

Can you please attach your data.

Cheers,
Nils

**Comment by amerville98** [comment]
Hi,
I had the error when i used data from the tutorial : https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/DailyShading.html#dailyshading
(and the first time with my own)

**Comment by nilswallenberg** [comment]
Hmm, okay. I can use that data set (DEM) and create a DSM. Just made a quick test with the buildings shapefile that comes with the data set (used the KVALITET field but shouldn't matter). 

Do you have a field in your polygon shapefile with information on building height?

**Comment by amerville98** [comment]
I introduced a field with the same height for everyone one .
I had also this error  :
![image](https://github.com/UMEP-dev/UMEP/assets/144142386/49a80abe-b862-4e79-8f6b-e4f5bc3b7f57)

I noticed that new fileds appeared after the field "height' each i try to run the function

![image](https://github.com/UMEP-dev/UMEP/assets/144142386/774b15eb-b5f9-4afe-9adb-467350f1ed17)

**Comment by biglimp** [comment]
I updated QGIS to latest version (same as you) and could not replicate your error. Please send you building polygons and DEM for us to try.

**Comment by amerville98** [comment]
[error_dsm.zip](https://github.com/UMEP-dev/UMEP/files/12686139/error_dsm.zip)

**Comment by biglimp** [comment]
You have not send the shapefile but the bdf-file. A shapefile is actually at leat 3 files (shp, dbf, shx). Include all files that is called buildings.

**Comment by amerville98** [comment]
Sorry, it's here 
[error_dsm_2.zip](https://github.com/UMEP-dev/UMEP/files/12698284/error_dsm_2.zip)

**Comment by biglimp** [comment]
You are still missing files from the Gothenburg testdata, e.g. buildings.prj which is important as this include info on CRS for the building layer

**Comment by amerville98** [comment]
[buildings.zip](https://github.com/UMEP-dev/UMEP/files/12698407/buildings.zip)

**Comment by biglimp** [comment]
Thanks. Just tested. I cannot replicate your error. I used the following settings (extent is taken from the DEM):

![image](https://github.com/UMEP-dev/UMEP/assets/11908356/04ed803d-f954-4c0c-824c-c2d7522fca27)

**Comment by amerville98** [comment]
I used the same settings and i have the last error i sent

**Comment by amerville98** [comment]
why did you use stats_me_1 which the field automatically create when i run the function ? In any case, I get this error with this field or with HEIGHT, which is my field that I created by hand (=10m for all entities).

**Comment by nilswallenberg** [comment]
I tried with the HEIGHT field and it worked. Difficult to figure out what could be the problem here.

Have you tried with the long term release of QGIS (Version 3.28.11 LTR)? You are now on 3.32.3, which is less stable.

**Comment by biglimp** [comment]
I have this settings:
QGIS version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)

I suggest that you uninstall QGIS and start a clean new installation. I will close this issue as it is not related to UMEP.
