### ISSUE TITLE
Error using Outdoor Thermal Confort SOLWEIG v2022a

### ISSUE THREAD

**Issue by vitorlavor** [UMEP-dev/UMEP#554]
I am trying to run the tutorial for SOLWEIG from UMEP website, using the data available for  Gontenburg, however I am having this error:

Traceback (most recent call last):
File
"C:\Users/ef819661/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\solweig_algorithm.py", line 1231, in processAlgorithm radG_for_plot = radG[DOY == unique_days[0]] UnboundLocalError: local variable 'unique_days' referenced before assignment  
Execution failed after 14.25 seconds

QGIS 3.28.5
UMEP 2.0.7

**Comment by nilswallenberg** [comment]
Hi,

Try the latest version of UMEP (4.0.2) or UMEP for processing (2.0.8) available here on GitHub.

Cheers,
Nils
