### ISSUE TITLE
Error installing umep for processing

### ISSUE THREAD

**Issue by AlexKDo** [UMEP-dev/UMEP#557]
Helloo.

I had to format my pc so I had to download and reinstall everything. I downloaded the latest qgis version and installed umep + umep for processing. I installed manually all missing python libraries but still got a problem. I attache to image file. Thanks 
![image](https://github.com/UMEP-dev/UMEP/assets/81244161/44eea248-b233-4dfd-bfc9-c87b1ff16f7a)

**Comment by j3r3m1** [comment]
What version of numba and numpy do you use ? It seems they have to be updated.

**Comment by j3r3m1** [comment]
I consider it solved. Feel free to reopen if not the case

**Comment by AlexKDo** [comment]
Hello!
I didnt solve the problem i just abandonded it.. But I would like to use UMEP again and I am facing the same problem. I am using QGIS version 3.32.3

**Comment by j3r3m1** [comment]
I think it is due to a numba / numpy version that are in conflict. Can you please tell us the numpy and numba versions ? I suppose you have installed missing libraries using pip ?
If so can you open a Python console in QGIS (Plugin -> Python console) and then type:
```python
import pip
pip.main(["show", "numpy"])
```
and then report to us the version of numpy it returns. And same for numba:
```python
pip.main(["show", "numba"])
```

**Comment by AlexKDo** [comment]
![numba   numoy version version](https://github.com/UMEP-dev/UMEP/assets/81244161/c146841f-a8e4-4dac-9118-c1a5336aa840)

**Comment by j3r3m1** [comment]
It seems to be the same as #543. You should install a lower version of numpy.
In the same python console can you do:
```python
pip.main(["install", "numpy==1.23.3"])
```

And then after it runs reopen QGIS.

**Comment by AlexKDo** [comment]
Hello I uninstalled and reinstalled umep from zip file see here: https://github.com/UMEP-dev/UMEP/discussions/514#discussioncomment-9506804
No erroes occur while opening qgis.
i will make some tests and if anything occur I will post it again. Thank you!
