### ISSUE TITLE
Error to create DSM 

### ISSUE THREAD

**Issue by lizbethsofia** [UMEP-dev/UMEP#560]
When trying to create a DSM with the pre-processor Spatial Data: DSM Generator, we introduce a DEM and a spatial shape layer with the information of the buildings, however, when running, two errors are encountered:
 1.IndexError: index 303 is out of bounds for axis 1 with size 303.
2. Error! The raster projection is not in meters or feet. Please reproject.

1. Pre-processor>Spatial Data: DSM Generator
2. Click on parameters
3. Introduce DEM 
4. Introduce spatial shape with buildings
5. Define height information 
6.Take  DEM raster size
7.Run
7. See error

*Desktop
 - Windows 11
 - QGIS Version Desktop 3.32.2 
 - UMEP Version 4.0.2
 - 
**Screenshots**
![image](https://github.com/UMEP-dev/UMEP/assets/147743206/24fd8f23-37b4-4e72-aadd-1040befa0079)
![image](https://github.com/UMEP-dev/UMEP/assets/147743206/67f3e2e9-6573-425b-bda4-803af31c0dbf)

**Data**
If applicable, add data files to help us reproduce your problem.

**Additional context**
We are trying to create a study of a place that has no cloud information, city of Nacaome, Valle, Honduras.
[DSM-DEM-Lizbeth Alvarado.zip](https://github.com/UMEP-dev/UMEP/files/13034684/DSM-DEM-Lizbeth.Alvarado.zip)

**Comment by nilswallenberg** [comment]
Hi,

Are you aware that your extent is ~3x3 cm? Your pixel resolution in meters is 0.0005. I think you should check your dem.

Best regards,
Nils
