### ISSUE TITLE
SOLWEIG Analyzer : Python error

### ISSUE THREAD

**Issue by CDelasse** [UMEP-dev/UMEP#598]
I am trying to run SOLWEIG Analyser to plot POI data but I get the following error :
WARNING    Traceback (most recent call last):
              File "C:\Users/cdelasse01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SolweigAnalyzer\solweig_analyzer.py", line 315, in plotpoi
              dates.append(dt.datetime.datetime(int(data1[i, 0]), 1, 1) + datetime.timedelta(days=data1[i, 1] - 1, hours=data1[i, 2], minutes=data1[i, 3]))
             IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Any ideas?
Thanks in advance

**Comment by biglimp** [comment]
Could you please zip and attach your output folder for us to test.

**Comment by CDelasse** [comment]
[With_POI.zip](https://github.com/UMEP-dev/UMEP/files/14905499/With_POI.zip)

**Comment by biglimp** [comment]
Thanks. To be able to use "Point if Interest data" in SOLWEIG Analyzer you need to analyse more that one timestep i.e., use a meteorological file as input. 

I will close this issue as this is not a code error
