### ISSUE TITLE
Problem with MetData processor

### ISSUE THREAD

**Issue by arkouli** [UMEP-dev/UMEP#606]
Hello,

I am trying to process my meteorological data and I get the following error with all the parameters. I checked all the values and are between the ranges.
I would be very grateful if you could give me a hint. Attached is a picture,

best wishes,

![UMEP_Meteo](https://github.com/UMEP-dev/UMEP/assets/168199713/98e179fa-3b04-4010-b2a9-c4936ccf2894)

**Comment by Empanag** [comment]
You are using probably wrong scale, the values must be from 1 to 100, maybe you use from 0 to 1 scale. 
If they are normalized to 1 the probably the metdata processor doesn't accept them. If the problem continues 
you have to attach the metfile so i can see what's wrong.

**Comment by arkouli** [comment]
Hello,

thank you very much for your reply. The humidity values are from 1 to 100. it happens with all the parameters. Attached you can find the table. thank you.
[Meteo_umep.txt](https://github.com/UMEP-dev/UMEP/files/15146064/Meteo_umep.txt)

**Comment by nilswallenberg** [comment]
Hi,

Try to replace all your commas (,) with dots (.). 

Cheers,
Nils

**Comment by arkouli** [comment]
thank you! I will let you know if it works.
regards,
Marselina

Am Mo., 29. Apr. 2024 um 09:41 Uhr schrieb nilswallenberg <
***@***.***>:

**Comment by Empanag** [comment]
Okey i think i found something. You should change comma for decimal to dot.

[Meteo_umep.txt](https://github.com/UMEP-dev/UMEP/files/15146475/Meteo_umep.txt)

**Comment by biglimp** [comment]
I close this since it seem to have solved itself.
