### ISSUE TITLE
SUEWS Prepare - error 

### ISSUE THREAD

**Issue by marciaamatias** [UMEP-dev/UMEP#611]
When running the Suews Prepare I'm getting this error:

2024-05-07T10:24:12     CRITICAL    EXCEPTION IN C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\prepare_worker.py, 
             LINE 232 "if feat_id == int(split[0]):" 
             ERROR MESSAGE: invalid literal for int() with base 10: '0.458'

Can you help me with this error?

**Comment by biglimp** [comment]
Check your input metfile, so that it only consist of one space between each item.

**Comment by biglimp** [comment]
was this sloved? Can I close?

**Comment by marciaamatias** [comment]
No. it didn't solve the problem but you can close it.
