### ISSUE TITLE
SUEWS Simple cannot overwrite DailyState text file

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP#617]
Running SUEWSSimple multiple times creates error since a file cannot be created cos it already exists. @sunt05 , if I was to run outside of QGIS/UMEP, would it be possible to re-run same data with same setting without the issue below? If so, it is a QGIS issue that I could make a quick-fix by deleting all output before a new run is started.

**Desktop (please complete the following information):**
 - W10
 - QGIS Version 3.36.1
 - UMEP Version 4.04
 - SuPy Version 2023.5.26.dev0

![image](https://github.com/UMEP-dev/UMEP/assets/11908356/22e8cb78-dc94-4e06-ae73-89b4dc3d6ed1)

The window above comes from firstaid plugin which I recommend as a very competent debugger.

**Comment by sunt05** [comment]
So this is no longer an issue?

**Comment by biglimp** [comment]
Well I fixed it by removing the output folder before a new calculation is started. Maybe not the best way but it works...

**Comment by sunt05** [comment]
Sounds like a sensible workaround :)
