### ISSUE TITLE
Metdata processor : Wind speed - beyond what is expected

### ISSUE THREAD

**Issue by CDelasse** [UMEP-dev/UMEP#626]
Hi, 
I prepared this metdata space-delimited text file [meteo_txt_v4.txt](https://github.com/user-attachments/files/15741844/meteo_txt_v4.txt)
I got this error "Wind speed - beyond what is expected at line: [ 3 86]" even though wind speed at these lines is well within the accepted range. I suspect lines are not read properly. Can you help me spot the problem.
Thank you

**Comment by biglimp** [comment]
You cannot have zero wind speed. Change to 0.01.
