### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by martinhath** [UMEP-dev/UMEP#647]
Hi! I want to use code from this repository, but I can't find information about which license it's released under. 

I've looked around in this repo, and while some files (e.g. [this](https://github.com/UMEP-dev/UMEP/blob/SuPy-QGIS3/Utilities/f90nml/fpy.py)) has a license in its header, it also references files that don't exist. I've also checked the [readthedocs](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/index.html) pages, including the [FAQ](https://umep-docs.readthedocs.io/en/latest/FAQ.html), but haven't found anything regarding a license.

I'd really appreciate if the licensing situation was cleared up, so that I can figure out if I'm allowed to use this code, and under which circumstances, if any.

Thanks!

**Comment by biglimp** [comment]
Hi, Yes, very hidden. We should add this info in more places. You find the info in the About section, when the plugin is installed. We use GNU GPL 2.

**Comment by martinhath** [comment]
Great! Thanks for letting me know 😄

**Comment by biglimp** [comment]
Added as info in the documentation as well.
