### ISSUE TITLE
metdata_UMEP.txt not found

### ISSUE THREAD

**Issue by PranavSPandya** [UMEP-dev/UMEP#648]
Dear UMEP team.
I am really amazed at the processing capacity and data enrichment potential of UMEP. I am using it a lot in my PhD research and I would definitely cite it in my publications. However, in the UWG Analysis process, during this stage I am expecting to get "output raster from statistical analysis". But it is giving me this error that "metdata_UMEP.txt" is not found in UWG output folder. I ran all processes in sequence and the output received from Urban Weather Generator is all just .epw file. 

I read it in instruction manual (https://umep-docs.readthedocs.io/en/latest/post_processor/Urban%20Heat%20Island%20UWG%20Analyser.html#uwganalyser) that UWG output folder path is "Path that contains files generated by Urban Weather Generator. Only UMEP formatted output can be used here, not epw-files." 
But on running Urban Weather Generator I only received .epw files. And in my entire processing no file with name metdata_UMEP.txt is generated. 

Can you please tell me what to do, this output is very important to my research and I wish to complete it. 
Thank you.

![Untitled](https://github.com/user-attachments/assets/41c8d55c-098a-48b9-a43f-986f060b77ce)

**Comment by biglimp** [comment]
Thank you for your nice comments. This is a very new tool so there might be bugs still in the code. 
First question: Did you try yo follow the new [tutorial on UWG](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/UWGSpatial.html#uwgspatial)? If not, please do os and see if you get same error. Please report back.
Second Question: Did you successfully execute UWG for your area?
/Fredrik

**Comment by PranavSPandya** [comment]
I solved the problem:
Thank you for your response. I looked at this manual as well.
I eventually found the solution. I hope this helps others who encounter this difficulty in future.

In the Urban Heat Island: Urban Weather Generator tool, make sure to select "Save output in UMEP specific format. Leave ticked off to store in epw-format" This option when ticked generates the required "metdata_UMEP.txt" which is essential for UWG Analyzer. Without this file the UWG Analyzer cannot run. 

**Note:** If this option is ticked, epw files aren't generated and rather the output of Urban Weather Generator tool will only generate result in .txt files. So if you need to work with epw files (which was case for me), you need to run this tool two times once with tick and once without.
I hope this helps future research use of UMEP. 

![Image](https://github.com/user-attachments/assets/84ae5a0e-7d44-4110-b7bf-12f6965c62c1)
![Image](https://github.com/user-attachments/assets/99cb8a09-0a9a-4e70-9114-9e9ba74b320a)
