### ISSUE TITLE
Error when running Land Cover Fraction (grid) tool

### ISSUE THREAD

**Issue by gusbenjaho** [UMEP-dev/UMEP#660]
I get the following error when runnning the Land Cover Fraction (grid) tool:

poly_field: ['id']
Number of grids to analyse: 49
idx: 0
Grid 1.0 being calculated.
Traceback (most recent call last):
File "C:\Users/bnhg/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\landcoverfraction_algorithm.py", line 255, in processAlgorithm
landcoverresult = land.landcover_v2(lcgrid, imid, degree, feedback, imp_point)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: landcover_v2() missing 1 required positional argument: 'num_of_class'

Execution failed after 0.06 seconds

I have reclassed NMD data with the Land Cover Reclassifier so I have data with UMEP classification and I have a 100x100m grid I want to calculate the land cover fraction for. I tried with multiple differend land cover rasters but get the same error every time.

Are there any steps that I missed?

**Comment by biglimp** [comment]
What version of UMEP fro Processing are you using. Use the latest, 2.0.31

**Comment by gusbenjaho** [comment]
I have 2.0.31 installed

**Comment by biglimp** [comment]
Fixed
