### ISSUE TITLE
TARGET tutorial suggestions

### ISSUE THREAD

**Issue by mothlight** [UMEP-dev/UMEP#676]
**Describe the bug**

Some suggested improvements for the Target tutorial document
https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/TARGETTutorial.html#targettutorial

Load the vector layer gbgcity_grid_300m.shp into your QGIS project. In the Style tab in layer Properties, choose a Simple fill and set Fill style to No Brush, to be able to see the spatial data within each grid.

_In my QGIS, this is the Symbology tab (not Style)_

First, try to plot grid 11 between May 7 and 17 by opening UMEP -> Post Processor -> Urban Heat Island -> TARGETAnalyzer and use the settings below beofre clicking Plot:

_I was slightly confused by this step since it is in the UMEP menu. I know it says that but I still searched the processing menu over and over._ 

_Ok, I see, the last paragraph says there are two different analysers. Can you move this paragraph to before the analyser section?_

Spelling mistakes:
TARGET land cover **infromation**
**Downlaod** data (ERA5) tool
**beofre** clicking Plot
other has **benn** moved
from your model **reults**
there are **possibilites**

**Comment by biglimp** [comment]
Thanks! Changes will be available next time I update the webpage...
