### ISSUE TITLE
Metdata processor is printing wrong years when using .epw files

### ISSUE THREAD

**Issue by gusbacos** [UMEP-dev/UMEP#680]
When using a .epw file in metdata processor the year of the data in the output file becomes 1985. I Tried with a few different areas and years but all becomes same.

**Desktop (please complete the following information):**
 - Windows 11
 - QGIS Version 3.38.3
 - UMEP Version 4.3
 - SuPy Version 2024.8.2.dev

**Comment by biglimp** [comment]
That is because a epw-file can take monthly data from different years so 1985 is hard coded into the tool.

**Comment by CsillaVG** [comment]
1985 seem to have been accidentally hardcoded into metdata_processor.py.

**Comment by biglimp** [comment]
> 1985 seem to have been accidentally hardcoded into metdata_processor.py.

Yes, as stated above this is how epw-files look like if you use typical meteorological years. I will see if I can fix this...
