### ISSUE TITLE
Download data (ERA5), comments

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#686]
Hi Team,

This is not an issue, rather a user observation and a request. 

Observation ::
There is a UI glitch when trying to run the ERA5 downloader using binary QGIS installs of QGIS (both under 3.40.1-Bratislava and 3.34.12-Prizren) in the macOS (13.2) environment:. When clicking on the three dots next to the Point of interest input, the initial window remains hanging on the screen and the pointer also remains unchanged (the default arrow), giving the impression that the input process is hanging/broken. Nevertheless, one can still move the window to the side and select the preferred location on the QGIS layer.

Request ::
There has been a few pointers, here and there, to use the Shiny weather data app as an alternative. Would it be possible to provide a few additional information at the bottom of the [relevant documentation page](https://umep-docs.readthedocs.io/en/latest/pre-processor/Meteorological%20Data%20Download%20data%20(ERA5).html )? Such as, the preferred file format (csv vs epw) and UTC specification (no offset vs local time). It would both improve UMEP's accessibility and reduce future modeling errors. 

Thank you!
Csilla

**Comment by biglimp** [comment]
Hi Csilla,

Your first glitch is coming from the QGIS main API and not in our hands to fix. I cannot replicate on other OS systems. Submit an issue to qgis.org instead.

Shinyweather link is already provided in the manual. I will make more clear.

Please suggest the text to pout in and I will do it.

/Fredrik

**Comment by CsillaVG** [comment]
Sure. I'll submit a bug report to QGIS as well, and write up a few lines regarding Shiny weather app use.

FYI, the metadata processor is also buggy (writeup is coming). At the moment, it's only compatible with shiny weather's epw format.

**Comment by biglimp** [comment]
And this data from EnergyPlus: https://energyplus.net/weather

**Comment by biglimp** [comment]
Fixed in #687
