### ISSUE TITLE
TARGET tutorial additional suggestions

### ISSUE THREAD

**Issue by bartpannemans** [UMEP-dev/UMEP#689]
**Describe the bug**
linked to [issue 676](https://github.com/UMEP-dev/UMEP/issues/676).
Some additional remarks:

**Section: Initial Steps**

- installation instructions: It's not enough to install the UMEP-plugins, also Target should be installed. It would be better to mention this explicitly, because I thought it was installed together with the UMEP-plugin (as a dependency). I also had it already installed on my system, but in a different environment. I was struggling to understand why Target in UMEP did not work, and later on how to get it installed in the UMEP-environment. Eventually I noted the note in the Processor help section, where was mentioned: "_NOTE: This plugin requires the target-py python library. If missing on your system, instructions on how to install missing python libraries using the pip command can be found here: https://umep-docs.readthedocs.io/en/latest/Getting_Started.html._ This link led me in the right direction. For Windows, in the Target tutorial you could point directly to the subsection to install it via the OSGeo Shell (because target is not available in the OSGeo Setup). Thus: _"Type OSGeoGW Shell in the Windows search bar. In the Shell type following command: python -m pip install target-py."_

- The Target tutorial refers to the other tutorial _Getting Started_. The latter also need updating on some points:
  - the text still refers to the old location of UMEP in the Menu Bar, while this has been moved to 'processing'.
  - the name of the Shadow Generator has changed to Processing > Processor > Solar Radiation: shadow generator
  - the screen shots do no longer correspond.

- Duplicated word in "Note for example **that** that CDSM..."
- "TARGET has no bare soil **cless**" -> class

** Section: Preparing input data **
- "We start to calculate roughness parameters based on the building geometry within each grid**s**" (remove s)
- "Header abbreviations are explained [here](http://umep-docs.readthedocs.io/en/latest/Abbreviations.html)." . Not all headers are found in this list; zH, zHmax, zHstd, wai are missing, but can be found in another list (see https://umep-docs.readthedocs.io/en/latest/pre-processor/Urban%20Morphology%20Morphometric%20Calculator%20(Point).html)
- "Open UMEP > Pre-Processor > Urban Land Cover > Land Cover Fraction (Grid)." -> change to new location: processing > pre-processor > Urban Land Cover: Land Cover Fraction (grid)

** Section: Preparing input data for the Target model **
- "Open TARGET Prepare (UMEP > Pre-Processor > Urban Heat Island > TARGET prepare)" -> change to the new location: processing > UMEP > Pre-processor > Urban Heat Island: TARGET prepare
- this step creates a file GBGMay > input > LC > lc_target.txt. For the first two gridcells parameter W has a value of 8890 and 3391. This seems unexpectedly high (for gridcells of 300x300m). Probably due to the fact that these gridcells are mainly water. 

** Section: Meteorological forcing data **
- Target-specific format: Pressure should be in hPa (in GBGMay > input > MET > gbg1_metdata.txt), but is in kPa (as in UMEP-standard format)
- "In this tutorial, you are provided with **s** dataset" -> missing word?
- "This data could have been **dowmnload**"

** Section: Executing the model **
- "Open UMEP -> Processor -> Urban Heat Island: TARGET" -> change to new location: Processing > UMEP > Processor > Urban Heat Island: Target
- In Python console I got an error "logging error". However, the simulation seems OK, and resultfiles are present, so not really a problem. 

_--- Logging error --- Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users/happy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\target_algorithm.py", line 246, in processAlgorithm
    tar.save_simulation_parameters()
  File "C:\Users\happy\AppData\Roaming\Python\Python312\site-packages\target_py\scripts\toolkit.py", line 535, in save_simulation_parameters
    LOG.info("saving simulation parameters")
Message: 'saving simulation parameters'_

**Comment by biglimp** [comment]
Many thanks for this. It help us improve the tool. We will make appropriate changes.
