### ISSUE TITLE
UMEP couldn't install Python packages! See 'General' tab in 'Log Messages' panel for details.

### ISSUE THREAD

**Issue by kun-creator** [UMEP-dev/UMEP#690]
![Image](https://github.com/user-attachments/assets/0c3465a7-e285-4627-9807-a4c151e19e33)

How to solve this problem?

**Comment by biglimp** [comment]
We need more info to help you (OS, versions of QGIS, UMEP etc.). My guess is that you have way too old QGIS version on your system (IOS?). Try to update. I will convert to a Discussion item as I dont think this is an actual UMEP issue...
